# Generated by Django 4.2.20 on 2026-06-04 12:51

from django.db import migrations, models
import generics.validators
import laboratories.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioAltriDipartimenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_dip_lab', models.CharField(blank=True, db_column='DESCR_DIP_LAB', max_length=400, null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_ALTRI_DIPARTIMENTI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioAttivita',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_finalita_it', models.TextField(db_column='DESCR_FINALITA_IT', null=True)),
                ('descr_finalita_en', models.TextField(db_column='DESCR_FINALITA_EN', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_ATTIVITA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioAttrezzature',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipologia', models.CharField(db_column='TIPOLOGIA', max_length=500, null=True)),
                ('descrizione', models.TextField(db_column='DESCRIZIONE', null=True)),
                ('costo_unitario', models.FloatField(db_column='COSTO_UNITARIO', null=True)),
                ('quantita', models.IntegerField(db_column='QUANTITA', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_ATTREZZATURE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioAttrezzatureFondi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_ATTREZZATURE_FONDI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioAttrezzatureRischi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_ATTREZZATURE_RISCHI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioDatiBase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_sottomissione', models.DateTimeField(blank=True, db_column='DT_SOTTOMISSIONE', null=True)),
                ('referente_compilazione', models.CharField(blank=True, db_column='REFERENTE_COMPILAZIONE', max_length=200, null=True)),
                ('email_compilazione', models.CharField(blank=True, db_column='EMAIL_COMPILAZIONE', max_length=200, null=True)),
                ('nome_laboratorio', models.CharField(db_column='NOME_LABORATORIO', max_length=400, null=True)),
                ('acronimo', models.CharField(blank=True, db_column='ACRONIMO', max_length=100, null=True)),
                ('logo_laboratorio', models.CharField(blank=True, db_column='LOGO_LABORATORIO', max_length=400, null=True)),
                ('dipartimento_riferimento_nome', models.CharField(blank=True, db_column='DIPARTIMENTO_RIFERIMENTO', max_length=400, null=True)),
                ('laboratorio_interdipartimentale', models.CharField(blank=True, db_column='LABORATORIO_INTERDIPARTIMENTALE', max_length=400, null=True)),
                ('altre_strutture_riferimento', models.CharField(blank=True, db_column='ALTRE_STRUTTURE_RIFERIMENTO', max_length=400, null=True)),
                ('descr_altre_strutture_riferimento_it', models.TextField(blank=True, db_column='DESCR_ALTRE_STRUTTURE_RIFERIMENTO_IT', null=True)),
                ('descr_altre_strutture_riferimento_en', models.TextField(blank=True, db_column='DESCR_ALTRE_STRUTTURE_RIFERIMENTO_EN', null=True)),
                ('ambito', models.CharField(blank=True, db_column='AMBITO', max_length=100, null=True)),
                ('finalita_ricerca_it', models.TextField(blank=True, db_column='FINALITA_RICERCA_IT', null=True)),
                ('finalita_ricerca_en', models.TextField(blank=True, db_column='FINALITA_RICERCA_EN', null=True)),
                ('finalita_didattica_it', models.TextField(blank=True, db_column='FINALITA_DIDATTICA_IT', null=True)),
                ('finalita_didattica_en', models.TextField(blank=True, db_column='FINALITA_DIDATTICA_EN', null=True)),
                ('finalita_servizi_it', models.TextField(blank=True, db_column='FINALITA_SERVIZI_IT', null=True)),
                ('finalita_servizi_en', models.TextField(blank=True, db_column='FINALITA_SERVIZI_EN', null=True)),
                ('responsabile_scientifico', models.CharField(blank=True, db_column='RESPONSABILE_SCIENTIFICO', max_length=200, null=True)),
                ('sede_dimensione', models.CharField(blank=True, db_column='SEDE_DIMENSIONE', max_length=100, null=True)),
                ('sede_note_descrittive', models.TextField(blank=True, db_column='SEDE_NOTE_DESCRITTIVE', null=True)),
                ('strumentazione_descrizione', models.TextField(db_column='STRUMENTAZIONE_DESCRIZIONE')),
                ('strumentazione_valore', models.DecimalField(blank=True, db_column='STRUMENTAZIONE_VALORE', decimal_places=2, max_digits=20, null=True)),
                ('preposto_sicurezza', models.CharField(blank=True, db_column='PREPOSTO_SICUREZZA', max_length=200, null=True)),
                ('sito_web', models.CharField(blank=True, db_column='SITO_WEB', max_length=1024, null=True)),
                ('nome_file_logo', models.FileField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True, upload_to=laboratories.settings.laboratories_media_path, validators=[generics.validators.validate_image_file_extension, generics.validators.validate_file_size])),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=False)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_DATI_BASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioDatiErc1',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LABORATORIO_DATI_ERC1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioFondo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_fondo', models.CharField(db_column='NOME_FONDO', max_length=500)),
            ],
            options={
                'db_table': 'LABORATORIO_FONDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioInfrastruttura',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=1000)),
            ],
            options={
                'db_table': 'LABORATORIO_INFRASTRUTTURA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioPersonaleRicerca',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cognomenome_origine', models.CharField(blank=True, db_column='COGNOMENOME_ORIGINE', max_length=200, null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_PERSONALE_RICERCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioPersonaleTecnico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ruolo', models.CharField(blank=True, db_column='RUOLO', max_length=400, null=True)),
                ('percentuale_impegno', models.FloatField(blank=True, db_column='PERCENTUALE_IMPEGNO', null=True)),
                ('cognomenome_origine', models.CharField(blank=True, db_column='COGNOMENOME_ORIGINE', max_length=200, null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_PERSONALE_TECNICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioServiziErogati',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.TextField(db_column='DESCRIZIONE', null=True)),
                ('matricola_responsabile', models.CharField(blank=True, db_column='MATRICOLA_RESPONSABILE', max_length=20, null=True)),
                ('responsabile_origine', models.CharField(blank=True, db_column='RESPONSABILE_ORIGINE', max_length=500, null=True)),
                ('committenti', models.CharField(db_column='COMMITTENTI', max_length=500, null=True)),
                ('anno', models.IntegerField(db_column='ANNO', null=True)),
                ('durata_mesi', models.IntegerField(db_column='DURATA_MESI', null=True)),
                ('importo_euro', models.FloatField(db_column='IMPORTO_EURO', null=True)),
                ('strumentazione', models.TextField(db_column='STRUMENTAZIONE', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_SERVIZI_EROGATI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioServiziOfferti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_servizio', models.TextField(db_column='NOME_SERVIZIO', null=True)),
                ('descrizione_servizio', models.TextField(db_column='DESCRIZIONE_SERVIZIO', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_SERVIZI_OFFERTI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioTipologiaAttivita',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=1000)),
            ],
            options={
                'db_table': 'LABORATORIO_TIPOLOGIA_ATTIVITA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioTipologiaRischio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipologia_rischio_origine', models.CharField(blank=True, db_column='TIPOLOGIA_RISCHIO_ORIGINE', max_length=500, null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_TIPOLOGIA_RISCHIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioUbicazione',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('edificio', models.CharField(db_column='EDIFICIO', max_length=200, null=True)),
                ('piano', models.CharField(db_column='PIANO', max_length=100, null=True)),
                ('sede_principale', models.CharField(db_column='SEDE_PRINCIPALE', max_length=10, null=True)),
                ('note', models.TextField(blank=True, db_column='NOTE', null=True)),
            ],
            options={
                'db_table': 'LABORATORIO_UBICAZIONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipologiaRischio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_tipologia', models.CharField(db_column='DESCR_TIPOLOGIA', max_length=1000)),
            ],
            options={
                'db_table': 'TIPOLOGIA_RISCHIO',
                'managed': False,
            },
        ),
    ]
