# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generics.validators
import laboratories.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
        ("research_lines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaboratorioAttivita",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_finalita_it",
                    models.TextField(db_column="DESCR_FINALITA_IT", null=True),
                ),
                (
                    "descr_finalita_en",
                    models.TextField(db_column="DESCR_FINALITA_EN", null=True),
                ),
            ],
            options={
                "db_table": "LABORATORIO_ATTIVITA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioAttrezzature",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "tipologia",
                    models.CharField(db_column="TIPOLOGIA", max_length=500, null=True),
                ),
                ("descrizione", models.TextField(db_column="DESCRIZIONE", null=True)),
                (
                    "costo_unitario",
                    models.FloatField(db_column="COSTO_UNITARIO", null=True),
                ),
                ("quantita", models.IntegerField(db_column="QUANTITA", null=True)),
            ],
            options={
                "db_table": "LABORATORIO_ATTREZZATURE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioDatiBase",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dt_sottomissione",
                    models.DateTimeField(
                        blank=True, db_column="DT_SOTTOMISSIONE", null=True
                    ),
                ),
                (
                    "referente_compilazione",
                    models.CharField(
                        blank=True,
                        db_column="REFERENTE_COMPILAZIONE",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "email_compilazione",
                    models.CharField(
                        blank=True,
                        db_column="EMAIL_COMPILAZIONE",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "nome_laboratorio",
                    models.CharField(
                        db_column="NOME_LABORATORIO", max_length=400, null=True
                    ),
                ),
                (
                    "acronimo",
                    models.CharField(
                        blank=True, db_column="ACRONIMO", max_length=100, null=True
                    ),
                ),
                (
                    "logo_laboratorio",
                    models.CharField(
                        blank=True,
                        db_column="LOGO_LABORATORIO",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "dipartimento_riferimento_nome",
                    models.CharField(
                        blank=True,
                        db_column="DIPARTIMENTO_RIFERIMENTO",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "laboratorio_interdipartimentale",
                    models.CharField(
                        blank=True,
                        db_column="LABORATORIO_INTERDIPARTIMENTALE",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "altre_strutture_riferimento",
                    models.CharField(
                        blank=True,
                        db_column="ALTRE_STRUTTURE_RIFERIMENTO",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "descr_altre_strutture_riferimento_it",
                    models.TextField(
                        blank=True,
                        db_column="DESCR_ALTRE_STRUTTURE_RIFERIMENTO_IT",
                        null=True,
                    ),
                ),
                (
                    "descr_altre_strutture_riferimento_en",
                    models.TextField(
                        blank=True,
                        db_column="DESCR_ALTRE_STRUTTURE_RIFERIMENTO_EN",
                        null=True,
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        blank=True, db_column="AMBITO", max_length=100, null=True
                    ),
                ),
                (
                    "finalita_ricerca_it",
                    models.TextField(
                        blank=True, db_column="FINALITA_RICERCA_IT", null=True
                    ),
                ),
                (
                    "finalita_ricerca_en",
                    models.TextField(
                        blank=True, db_column="FINALITA_RICERCA_EN", null=True
                    ),
                ),
                (
                    "finalita_didattica_it",
                    models.TextField(
                        blank=True, db_column="FINALITA_DIDATTICA_IT", null=True
                    ),
                ),
                (
                    "finalita_didattica_en",
                    models.TextField(
                        blank=True, db_column="FINALITA_DIDATTICA_EN", null=True
                    ),
                ),
                (
                    "finalita_servizi_it",
                    models.TextField(
                        blank=True, db_column="FINALITA_SERVIZI_IT", null=True
                    ),
                ),
                (
                    "finalita_servizi_en",
                    models.TextField(
                        blank=True, db_column="FINALITA_SERVIZI_EN", null=True
                    ),
                ),
                (
                    "responsabile_scientifico",
                    models.CharField(
                        blank=True,
                        db_column="RESPONSABILE_SCIENTIFICO",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "sede_dimensione",
                    models.CharField(
                        blank=True,
                        db_column="SEDE_DIMENSIONE",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sede_note_descrittive",
                    models.TextField(
                        blank=True, db_column="SEDE_NOTE_DESCRITTIVE", null=True
                    ),
                ),
                (
                    "strumentazione_descrizione",
                    models.TextField(db_column="STRUMENTAZIONE_DESCRIZIONE"),
                ),
                (
                    "strumentazione_valore",
                    models.DecimalField(
                        blank=True,
                        db_column="STRUMENTAZIONE_VALORE",
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "preposto_sicurezza",
                    models.CharField(
                        blank=True,
                        db_column="PREPOSTO_SICUREZZA",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "sito_web",
                    models.CharField(
                        blank=True, db_column="SITO_WEB", max_length=1024, null=True
                    ),
                ),
                (
                    "nome_file_logo",
                    models.FileField(
                        blank=True,
                        db_column="NOME_FILE_LOGO",
                        max_length=1000,
                        null=True,
                        upload_to=laboratories.settings.laboratories_media_path,
                        validators=[
                            generics.validators.validate_image_file_extension,
                            generics.validators.validate_file_size,
                        ],
                    ),
                ),
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "dipartimento_riferimento",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_DIPARTIMENTO_RIFERIMENTO",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="structures.didatticadipartimento",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_DATI_BASE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioFondo",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_fondo",
                    models.CharField(db_column="NOME_FONDO", max_length=500),
                ),
            ],
            options={
                "db_table": "LABORATORIO_FONDO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioInfrastruttura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=1000),
                ),
            ],
            options={
                "db_table": "LABORATORIO_INFRASTRUTTURA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioTipologiaAttivita",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=1000),
                ),
            ],
            options={
                "db_table": "LABORATORIO_TIPOLOGIA_ATTIVITA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TipologiaRischio",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_tipologia",
                    models.CharField(db_column="DESCR_TIPOLOGIA", max_length=1000),
                ),
            ],
            options={
                "db_table": "TIPOLOGIA_RISCHIO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioUbicazione",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "edificio",
                    models.CharField(db_column="EDIFICIO", max_length=200, null=True),
                ),
                (
                    "piano",
                    models.CharField(db_column="PIANO", max_length=100, null=True),
                ),
                (
                    "sede_principale",
                    models.CharField(
                        db_column="SEDE_PRINCIPALE", max_length=10, null=True
                    ),
                ),
                ("note", models.TextField(blank=True, db_column="NOTE", null=True)),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_UBICAZIONE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioTipologiaRischio",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "tipologia_rischio_origine",
                    models.CharField(
                        blank=True,
                        db_column="TIPOLOGIA_RISCHIO_ORIGINE",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
                (
                    "tipologia_rischio",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_TIPOLOGIA_RISCHIO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.tipologiarischio",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_TIPOLOGIA_RISCHIO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioServiziOfferti",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_servizio",
                    models.TextField(db_column="NOME_SERVIZIO", null=True),
                ),
                (
                    "descrizione_servizio",
                    models.TextField(db_column="DESCRIZIONE_SERVIZIO", null=True),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_SERVIZI_OFFERTI",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioServiziErogati",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("descrizione", models.TextField(db_column="DESCRIZIONE", null=True)),
                (
                    "matricola_responsabile",
                    models.CharField(
                        blank=True,
                        db_column="MATRICOLA_RESPONSABILE",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "responsabile_origine",
                    models.CharField(
                        blank=True,
                        db_column="RESPONSABILE_ORIGINE",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "committenti",
                    models.CharField(
                        db_column="COMMITTENTI", max_length=500, null=True
                    ),
                ),
                ("anno", models.IntegerField(db_column="ANNO", null=True)),
                (
                    "durata_mesi",
                    models.IntegerField(db_column="DURATA_MESI", null=True),
                ),
                (
                    "importo_euro",
                    models.FloatField(db_column="IMPORTO_EURO", null=True),
                ),
                (
                    "strumentazione",
                    models.TextField(db_column="STRUMENTAZIONE", null=True),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_SERVIZI_EROGATI",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioPersonaleTecnico",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "ruolo",
                    models.CharField(
                        blank=True, db_column="RUOLO", max_length=400, null=True
                    ),
                ),
                (
                    "percentuale_impegno",
                    models.FloatField(
                        blank=True, db_column="PERCENTUALE_IMPEGNO", null=True
                    ),
                ),
                (
                    "cognomenome_origine",
                    models.CharField(
                        blank=True,
                        db_column="COGNOMENOME_ORIGINE",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
                (
                    "matricola_personale_tecnico",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE_MATRICOLA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_PERSONALE_TECNICO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioPersonaleRicerca",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "cognomenome_origine",
                    models.CharField(
                        blank=True,
                        db_column="COGNOMENOME_ORIGINE",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
                (
                    "matricola_personale_ricerca",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE_MATRICOLA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_PERSONALE_RICERCA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioDatiErc1",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
                (
                    "ricerca_erc1",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_RICERCA_ERC1",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research_lines.ricercaerc1",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_DATI_ERC1",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="infrastruttura_riferimento",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_INFRASTRUTTURA_RIFERIMENTO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="laboratories.laboratorioinfrastruttura",
            ),
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="matricola_preposto_sicurezza",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_PERSONALE_MATRICOLA_PREPOSTO_SICUREZZA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matricola_preposto_sicurezza_personale",
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="matricola_referente_compilazione",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_PERSONALE_MATRICOLA_REFERENTE_COMPILAZIONE",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matricola_referente_compilazione_personale",
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="matricola_responsabile_scientifico",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_PERSONALE_MATRICOLA_RESPONSABILE_SCIENTIFICO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matricola_responsabile_scientifico_personale",
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="tipologia_attivita",
            field=models.ManyToManyField(
                through="laboratories.LaboratorioAttivita",
                to="laboratories.laboratoriotipologiaattivita",
            ),
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="tipologia_rischio",
            field=models.ManyToManyField(
                through="laboratories.LaboratorioTipologiaRischio",
                to="laboratories.tipologiarischio",
            ),
        ),
        migrations.AddField(
            model_name="laboratoriodatibase",
            name="user_mod",
            field=models.ForeignKey(
                blank=True,
                db_column="user_mod_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LaboratorioAttrezzatureRischi",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "laboratorio_attrezzature",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_ATTREZZATURE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratorioattrezzature",
                    ),
                ),
                (
                    "tipologia_rischio",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_TIPOLOGIA_RISCHIO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.tipologiarischio",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_ATTREZZATURE_RISCHI",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LaboratorioAttrezzatureFondi",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "laboratorio_attrezzature",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_ATTREZZATURE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratorioattrezzature",
                    ),
                ),
                (
                    "laboratorio_fondo",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_FONDO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriofondo",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_ATTREZZATURE_FONDI",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="laboratorioattrezzature",
            name="laboratorio_dati_base",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_LABORATORIO_DATI",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="laboratories.laboratoriodatibase",
            ),
        ),
        migrations.AddField(
            model_name="laboratorioattivita",
            name="laboratorio_dati_base",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_LABORATORIO_DATI",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="laboratories.laboratoriodatibase",
            ),
        ),
        migrations.AddField(
            model_name="laboratorioattivita",
            name="tipologia_attivita",
            field=models.ForeignKey(
                db_column="ID_TIPOLOGIA_ATTIVITA",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="laboratories.laboratoriotipologiaattivita",
            ),
        ),
        migrations.CreateModel(
            name="LaboratorioAltriDipartimenti",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_dip_lab",
                    models.CharField(
                        blank=True, db_column="DESCR_DIP_LAB", max_length=400, null=True
                    ),
                ),
                (
                    "didattica_dipartimento",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_DIDATTICA_DIPARTIMENTO",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="structures.didatticadipartimento",
                    ),
                ),
                (
                    "laboratorio_dati_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_LABORATORIO_DATI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratories.laboratoriodatibase",
                    ),
                ),
            ],
            options={
                "db_table": "LABORATORIO_ALTRI_DIPARTIMENTI",
                "managed": True,
            },
        ),
    ]
