# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
        ("companies", "0001_initial"),
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgettoAmbitoTerritoriale",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "ambito_territoriale",
                    models.CharField(db_column="AMBITO_TERRITORIALE", max_length=100),
                ),
            ],
            options={
                "db_table": "PROGETTO_AMBITO_TERRITORIALE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProgettoDatiBase",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "anno_avvio",
                    models.IntegerField(blank=True, db_column="ANNO_AVVIO", null=True),
                ),
                (
                    "titolo",
                    models.CharField(
                        blank=True, db_column="TITOLO", max_length=4000, null=True
                    ),
                ),
                (
                    "descr_breve",
                    models.TextField(blank=True, db_column="DESCR_BREVE", null=True),
                ),
                (
                    "url_immagine",
                    models.URLField(
                        blank=True, db_column="URL_IMMAGINE", max_length=1000, null=True
                    ),
                ),
                (
                    "abstract_ita",
                    models.TextField(blank=True, db_column="ABSTRACT_ITA", null=True),
                ),
                (
                    "abstract_eng",
                    models.TextField(blank=True, db_column="ABSTRACT_ENG", null=True),
                ),
                (
                    "url_sito_web",
                    models.URLField(
                        blank=True, db_column="URL_SITO_WEB", max_length=1000, null=True
                    ),
                ),
                (
                    "call",
                    models.CharField(
                        blank=True, db_column="CALL", max_length=1000, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_column="ATTIVO", default=True)),
                ("ordinamento", models.IntegerField(db_column="ORDINE", default=10)),
                (
                    "ambito_territoriale",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_AMBITO_TERRITORIALE",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.progettoambitoterritoriale",
                    ),
                ),
                (
                    "area_tecnologica",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_AREA_TECNOLOGICA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.tipologiaareatecnologica",
                    ),
                ),
            ],
            options={
                "db_table": "PROGETTO_DATI_BASE",
                "ordering": ["ordinamento"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProgettoTipologiaProgramma",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_programma",
                    models.CharField(db_column="NOME_PROGRAMMA", max_length=1000),
                ),
            ],
            options={
                "db_table": "PROGETTO_TIPOLOGIA_PROGRAMMA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProgettoRicercatore",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_origine",
                    models.CharField(db_column="NOME_ORIGINE", max_length=1000),
                ),
                (
                    "matricola",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE_MATRICOLA",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
                (
                    "progetto",
                    models.ForeignKey(
                        db_column="ID_PROGETTO",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.progettodatibase",
                    ),
                ),
            ],
            options={
                "db_table": "PROGETTO_RICERCATORE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProgettoResponsabileScientifico",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_origine",
                    models.CharField(db_column="NOME_ORIGINE", max_length=1000),
                ),
                (
                    "matricola",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE_MATRICOLA",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
                (
                    "progetto",
                    models.ForeignKey(
                        db_column="ID_PROGETTO",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.progettodatibase",
                    ),
                ),
            ],
            options={
                "db_table": "PROGETTO_RESPONSABILE_SCIENTIFICO",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="progettodatibase",
            name="tipologia_programma",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_TIPOLOGIA_PROGRAMMA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.progettotipologiaprogramma",
            ),
        ),
        migrations.AddField(
            model_name="progettodatibase",
            name="uo",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_UNITA_ORGANIZZATIVA",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="structures.unitaorganizzativa",
            ),
        ),
    ]
