# Generated by Django 4.2.20 on 2026-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgettoAmbitoTerritoriale',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ambito_territoriale', models.CharField(db_column='AMBITO_TERRITORIALE', max_length=100)),
            ],
            options={
                'db_table': 'PROGETTO_AMBITO_TERRITORIALE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgettoDatiBase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('anno_avvio', models.IntegerField(blank=True, db_column='ANNO_AVVIO', null=True)),
                ('titolo', models.CharField(blank=True, db_column='TITOLO', max_length=4000, null=True)),
                ('descr_breve', models.TextField(blank=True, db_column='DESCR_BREVE', null=True)),
                ('url_immagine', models.URLField(blank=True, db_column='URL_IMMAGINE', max_length=1000, null=True)),
                ('abstract_ita', models.TextField(blank=True, db_column='ABSTRACT_ITA', null=True)),
                ('abstract_eng', models.TextField(blank=True, db_column='ABSTRACT_ENG', null=True)),
                ('url_sito_web', models.URLField(blank=True, db_column='URL_SITO_WEB', max_length=1000, null=True)),
                ('call', models.CharField(blank=True, db_column='CALL', max_length=1000, null=True)),
                ('is_active', models.BooleanField(db_column='ATTIVO', default=True)),
                ('ordinamento', models.IntegerField(db_column='ORDINE', default=10)),
            ],
            options={
                'db_table': 'PROGETTO_DATI_BASE',
                'ordering': ['ordinamento'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgettoResponsabileScientifico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_origine', models.CharField(db_column='NOME_ORIGINE', max_length=1000)),
            ],
            options={
                'db_table': 'PROGETTO_RESPONSABILE_SCIENTIFICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgettoRicercatore',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_origine', models.CharField(db_column='NOME_ORIGINE', max_length=1000)),
            ],
            options={
                'db_table': 'PROGETTO_RICERCATORE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgettoTipologiaProgramma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_programma', models.CharField(db_column='NOME_PROGRAMMA', max_length=1000)),
            ],
            options={
                'db_table': 'PROGETTO_TIPOLOGIA_PROGRAMMA',
                'managed': False,
            },
        ),
    ]
