# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                ("id_ab", models.IntegerField(db_column="ID_AB", unique=True)),
                (
                    "cd_esterno",
                    models.CharField(
                        blank=True, db_column="CD_ESTERNO", max_length=60, null=True
                    ),
                ),
                (
                    "matricola",
                    models.CharField(db_column="MATRICOLA", max_length=6, unique=True),
                ),
                (
                    "matricola_sp",
                    models.CharField(
                        blank=True, db_column="MATRICOLA_SP", max_length=255, null=True
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="NOME", max_length=100, null=True
                    ),
                ),
                (
                    "cognome",
                    models.CharField(
                        blank=True, db_column="COGNOME", max_length=100, null=True
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, db_column="MIDDLE_NAME", max_length=100, null=True
                    ),
                ),
                (
                    "cod_fis",
                    models.CharField(
                        blank=True,
                        db_column="COD_FIS",
                        max_length=16,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "cd_genere",
                    models.CharField(
                        blank=True, db_column="CD_GENERE", max_length=1, null=True
                    ),
                ),
                (
                    "dt_nascita",
                    models.DateField(blank=True, db_column="DT_NASCITA", null=True),
                ),
                (
                    "id_comu_nasc",
                    models.IntegerField(
                        blank=True, db_column="ID_COMU_NASC", null=True
                    ),
                ),
                (
                    "ds_cittstra_nasc",
                    models.CharField(
                        blank=True,
                        db_column="DS_CITTSTRA_NASC",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ds_comune_nasc",
                    models.CharField(
                        blank=True,
                        db_column="DS_COMUNE_NASC",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ds_prov_nasc",
                    models.CharField(
                        blank=True, db_column="DS_PROV_NASC", max_length=255, null=True
                    ),
                ),
                (
                    "cd_sigla_nasc",
                    models.CharField(
                        blank=True, db_column="CD_SIGLA_NASC", max_length=2, null=True
                    ),
                ),
                (
                    "id_nazione_nasc",
                    models.IntegerField(
                        blank=True, db_column="ID_NAZIONE_NASC", null=True
                    ),
                ),
                (
                    "ds_nazi_nasc",
                    models.CharField(
                        blank=True, db_column="DS_NAZI_NASC", max_length=100, null=True
                    ),
                ),
                (
                    "ds_nazi_breve_nasc",
                    models.CharField(
                        blank=True,
                        db_column="DS_NAZI_BREVE_NASC",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ds_comune_res",
                    models.CharField(
                        blank=True, db_column="DS_COMUNE_RES", max_length=255, null=True
                    ),
                ),
                (
                    "cd_cap_res",
                    models.CharField(
                        blank=True, db_column="CD_CAP_RES", max_length=5, null=True
                    ),
                ),
                (
                    "indirizzo_res",
                    models.CharField(
                        blank=True, db_column="INDIRIZZO_RES", max_length=255, null=True
                    ),
                ),
                (
                    "num_civico_res",
                    models.CharField(
                        blank=True, db_column="NUM_CIVICO_RES", max_length=15, null=True
                    ),
                ),
                (
                    "cd_sigla_res",
                    models.CharField(
                        blank=True, db_column="CD_SIGLA_RES", max_length=2, null=True
                    ),
                ),
                (
                    "id_comu_dom",
                    models.IntegerField(blank=True, db_column="ID_COMU_DOM", null=True),
                ),
                (
                    "ds_comune_dom",
                    models.CharField(
                        blank=True, db_column="DS_COMUNE_DOM", max_length=255, null=True
                    ),
                ),
                (
                    "cd_cap_dom",
                    models.CharField(
                        blank=True, db_column="CD_CAP_DOM", max_length=5, null=True
                    ),
                ),
                (
                    "indirizzo_dom",
                    models.CharField(
                        blank=True, db_column="INDIRIZZO_DOM", max_length=255, null=True
                    ),
                ),
                (
                    "num_civico_dom",
                    models.CharField(
                        blank=True, db_column="NUM_CIVICO_DOM", max_length=15, null=True
                    ),
                ),
                (
                    "cd_sigla_dom",
                    models.CharField(
                        blank=True, db_column="CD_SIGLA_DOM", max_length=2, null=True
                    ),
                ),
                (
                    "cd_comparto",
                    models.CharField(db_column="CD_COMPARTO", max_length=1),
                ),
                (
                    "ds_comparto",
                    models.CharField(
                        blank=True, db_column="DS_COMPARTO", max_length=40, null=True
                    ),
                ),
                ("cd_ruolo", models.CharField(db_column="CD_RUOLO", max_length=4)),
                (
                    "ds_ruolo",
                    models.CharField(
                        blank=True, db_column="DS_RUOLO", max_length=40, null=True
                    ),
                ),
                (
                    "ds_ruolo_locale",
                    models.CharField(
                        blank=True,
                        db_column="DS_RUOLO_LOCALE",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "peso_ruolo",
                    models.DecimalField(
                        blank=True,
                        db_column="PESO_RUOLO",
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dt_rap_ini",
                    models.DateField(blank=True, db_column="DT_RAP_INI", null=True),
                ),
                (
                    "dt_rap_fin",
                    models.DateField(blank=True, db_column="DT_RAP_FIN", null=True),
                ),
                (
                    "cd_ssd",
                    models.CharField(
                        blank=True, db_column="CD_SSD", max_length=12, null=True
                    ),
                ),
                (
                    "ds_ssd",
                    models.CharField(
                        blank=True, db_column="DS_SSD", max_length=100, null=True
                    ),
                ),
                (
                    "cd_fac",
                    models.CharField(
                        blank=True, db_column="CD_FAC", max_length=10, null=True
                    ),
                ),
                (
                    "ds_fac",
                    models.CharField(
                        blank=True, db_column="DS_FAC", max_length=255, null=True
                    ),
                ),
                (
                    "ds_aff_org",
                    models.CharField(
                        blank=True, db_column="DS_AFF_ORG", max_length=255, null=True
                    ),
                ),
                (
                    "ds_aff_org_breve",
                    models.CharField(
                        blank=True,
                        db_column="DS_AFF_ORG_BREVE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cd_csa_aff_org2",
                    models.CharField(
                        blank=True, db_column="CD_CSA_AFF_ORG2", max_length=6, null=True
                    ),
                ),
                (
                    "ds_aff_org2",
                    models.CharField(
                        blank=True, db_column="DS_AFF_ORG2", max_length=255, null=True
                    ),
                ),
                (
                    "ds_aff_org2_breve",
                    models.CharField(
                        blank=True,
                        db_column="DS_AFF_ORG2_BREVE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cd_csa_aff_org3",
                    models.CharField(
                        blank=True, db_column="CD_CSA_AFF_ORG3", max_length=6, null=True
                    ),
                ),
                (
                    "ds_aff_org3",
                    models.CharField(
                        blank=True, db_column="DS_AFF_ORG3", max_length=255, null=True
                    ),
                ),
                (
                    "ds_aff_org3_breve",
                    models.CharField(
                        blank=True,
                        db_column="DS_AFF_ORG3_BREVE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cd_csa_aff_org4",
                    models.CharField(
                        blank=True, db_column="CD_CSA_AFF_ORG4", max_length=6, null=True
                    ),
                ),
                (
                    "ds_aff_org4",
                    models.CharField(
                        blank=True, db_column="DS_AFF_ORG4", max_length=255, null=True
                    ),
                ),
                (
                    "ds_aff_org4_breve",
                    models.CharField(
                        blank=True,
                        db_column="DS_AFF_ORG4_BREVE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sede",
                    models.CharField(
                        blank=True, db_column="SEDE", max_length=6, null=True
                    ),
                ),
                (
                    "ds_sede",
                    models.CharField(
                        blank=True, db_column="DS_SEDE", max_length=255, null=True
                    ),
                ),
                (
                    "ds_sede_breve",
                    models.CharField(
                        blank=True, db_column="DS_SEDE_BREVE", max_length=50, null=True
                    ),
                ),
                (
                    "profilo",
                    models.CharField(
                        blank=True, db_column="PROFILO", max_length=11, null=True
                    ),
                ),
                (
                    "ds_profilo",
                    models.CharField(
                        blank=True, db_column="DS_PROFILO", max_length=100, null=True
                    ),
                ),
                (
                    "ds_profilo_breve",
                    models.CharField(
                        blank=True,
                        db_column="DS_PROFILO_BREVE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cd_ateneo_corr",
                    models.CharField(
                        blank=True, db_column="CD_ATENEO_CORR", max_length=10, null=True
                    ),
                ),
                (
                    "ds_ateneo_corr",
                    models.CharField(
                        blank=True,
                        db_column="DS_ATENEO_CORR",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dt_ini_rap_univ",
                    models.DateField(
                        blank=True, db_column="DT_INI_RAP_UNIV", null=True
                    ),
                ),
                (
                    "dt_fin_rap_univ",
                    models.DateField(
                        blank=True, db_column="DT_FIN_RAP_UNIV", null=True
                    ),
                ),
                (
                    "telrif",
                    models.CharField(
                        blank=True, db_column="TELRIF", max_length=255, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="EMAIL", max_length=255, null=True
                    ),
                ),
                (
                    "urlcv",
                    models.URLField(
                        blank=True, db_column="URLCV", max_length=255, null=True
                    ),
                ),
                (
                    "fl_docente",
                    models.PositiveIntegerField(
                        blank=True, db_column="FL_DOCENTE", null=True
                    ),
                ),
                (
                    "cd_anagrafico",
                    models.CharField(
                        blank=True, db_column="CD_ANAGRAFICO", max_length=20, null=True
                    ),
                ),
                (
                    "inquadr",
                    models.CharField(
                        blank=True, db_column="INQUADR", max_length=50, null=True
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True, db_column="BADGE", max_length=255, null=True
                    ),
                ),
                (
                    "tempo",
                    models.CharField(
                        blank=True, db_column="TEMPO", max_length=1, null=True
                    ),
                ),
                (
                    "id_contratto",
                    models.IntegerField(
                        blank=True, db_column="ID_CONTRATTO", null=True
                    ),
                ),
                (
                    "flg_cessato",
                    models.IntegerField(blank=True, db_column="FLG_CESSATO", null=True),
                ),
                (
                    "cv_full_it",
                    models.TextField(blank=True, db_column="CV_FULL_IT", null=True),
                ),
                (
                    "cv_short_it",
                    models.TextField(blank=True, db_column="CV_SHORT_IT", null=True),
                ),
                (
                    "cv_full_eng",
                    models.TextField(blank=True, db_column="CV_FULL_ENG", null=True),
                ),
                (
                    "cv_short_eng",
                    models.TextField(blank=True, db_column="CV_SHORT_ENG", null=True),
                ),
            ],
            options={
                "db_table": "PERSONALE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PersonaleAttivoTuttiRuoli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "id_ab",
                    models.BigIntegerField(blank=True, db_column="ID_AB", null=True),
                ),
                (
                    "matricola",
                    models.CharField(
                        blank=True, db_column="MATRICOLA", max_length=6, null=True
                    ),
                ),
                (
                    "cod_fis",
                    models.CharField(
                        blank=True, db_column="COD_FIS", max_length=16, null=True
                    ),
                ),
                (
                    "cd_ruolo",
                    models.CharField(
                        blank=True, db_column="CD_RUOLO", max_length=4, null=True
                    ),
                ),
                (
                    "ds_ruolo",
                    models.CharField(
                        blank=True, db_column="DS_RUOLO", max_length=40, null=True
                    ),
                ),
                (
                    "ds_ruolo_breve",
                    models.CharField(
                        blank=True, db_column="DS_RUOLO_BREVE", max_length=20, null=True
                    ),
                ),
                (
                    "cd_tipo_ruolo",
                    models.CharField(
                        blank=True, db_column="CD_TIPO_RUOLO", max_length=2, null=True
                    ),
                ),
                (
                    "ds_tipo_ruolo",
                    models.CharField(
                        blank=True, db_column="DS_TIPO_RUOLO", max_length=80, null=True
                    ),
                ),
                (
                    "cd_inquadr",
                    models.CharField(
                        blank=True, db_column="CD_INQUADR", max_length=50, null=True
                    ),
                ),
                (
                    "ds_inquadr",
                    models.CharField(
                        blank=True, db_column="DS_INQUADR", max_length=80, null=True
                    ),
                ),
                (
                    "ds_aff_org",
                    models.CharField(
                        blank=True, db_column="DS_AFF_ORG", max_length=255, null=True
                    ),
                ),
                (
                    "ds_aff_org_breve",
                    models.CharField(
                        blank=True,
                        db_column="DS_AFF_ORG_BREVE",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "fl_tipo_rap",
                    models.FloatField(blank=True, db_column="FL_TIPO_RAP", null=True),
                ),
                (
                    "cd_ssd",
                    models.CharField(
                        blank=True, db_column="CD_SSD", max_length=12, null=True
                    ),
                ),
                (
                    "ds_ssd",
                    models.CharField(
                        blank=True, db_column="DS_SSD", max_length=100, null=True
                    ),
                ),
                (
                    "ds_ssd_breve",
                    models.CharField(
                        blank=True, db_column="DS_SSD_BREVE", max_length=20, null=True
                    ),
                ),
                (
                    "area_ssd",
                    models.CharField(
                        blank=True, db_column="AREA_SSD", max_length=2, null=True
                    ),
                ),
                (
                    "ds_area_ssd",
                    models.CharField(
                        blank=True, db_column="DS_AREA_SSD", max_length=100, null=True
                    ),
                ),
                (
                    "cd_riferimento",
                    models.CharField(
                        blank=True, db_column="CD_RIFERIMENTO", max_length=10, null=True
                    ),
                ),
                (
                    "ds_riferimento",
                    models.CharField(
                        blank=True,
                        db_column="DS_RIFERIMENTO",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "peso_inc",
                    models.IntegerField(blank=True, db_column="PESO_INC", null=True),
                ),
                (
                    "peso_ric",
                    models.IntegerField(blank=True, db_column="PESO_RIC", null=True),
                ),
                (
                    "sede",
                    models.CharField(
                        blank=True, db_column="SEDE", max_length=6, null=True
                    ),
                ),
                (
                    "ds_sede",
                    models.CharField(
                        blank=True, db_column="DS_SEDE", max_length=255, null=True
                    ),
                ),
                (
                    "dt_rap_ini",
                    models.DateTimeField(blank=True, db_column="DT_RAP_INI", null=True),
                ),
                (
                    "cd_profilo",
                    models.CharField(
                        blank=True, db_column="CD_PROFILO", max_length=11, null=True
                    ),
                ),
                (
                    "ds_profilo",
                    models.CharField(
                        blank=True, db_column="DS_PROFILO", max_length=100, null=True
                    ),
                ),
                (
                    "fl_docente",
                    models.IntegerField(blank=True, db_column="FL_DOCENTE", null=True),
                ),
                (
                    "cd_onorifico",
                    models.CharField(
                        blank=True, db_column="CD_ONORIFICO", max_length=4, null=True
                    ),
                ),
                (
                    "ds_onorifico",
                    models.CharField(
                        blank=True, db_column="DS_ONORIFICO", max_length=100, null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "user_mod_id",
                    models.CharField(
                        blank=True, db_column="USER_MOD_ID", max_length=32, null=True
                    ),
                ),
            ],
            options={
                "db_table": "PERSONALE_ATTIVO_TUTTI_RUOLI",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PersonalePrioritaRuolo",
            fields=[
                (
                    "cd_ruolo",
                    models.CharField(
                        db_column="CD_RUOLO",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ds_ruolo",
                    models.CharField(
                        blank=True, db_column="DS_RUOLO", max_length=1000, null=True
                    ),
                ),
                (
                    "priorita",
                    models.IntegerField(blank=True, db_column="PRIORITA", null=True),
                ),
            ],
            options={
                "db_table": "PERSONALE_PRIORITA_RUOLO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PersonaleUoTipoContatto",
            fields=[
                (
                    "cod_contatto",
                    models.CharField(
                        db_column="COD_CONTATTO",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descr_contatto",
                    models.CharField(db_column="DESCR_CONTATTO", max_length=200),
                ),
            ],
            options={
                "db_table": "PERSONALE_UO_TIPO_CONTATTO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PersonaleContatti",
            fields=[
                (
                    "id_ab",
                    models.IntegerField(
                        db_column="ID_AB", primary_key=True, serialize=False
                    ),
                ),
                (
                    "contatto",
                    models.CharField(
                        blank=True, db_column="CONTATTO", max_length=255, null=True
                    ),
                ),
                ("prg_priorita", models.IntegerField(db_column="PRG_PRIORITA")),
                (
                    "dt_ins_mod",
                    models.DateField(blank=True, db_column="DT_INS_MOD", null=True),
                ),
                (
                    "cd_tipo_cont",
                    models.ForeignKey(
                        db_column="CD_TIPO_CONT",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="addressbook.personaleuotipocontatto",
                    ),
                ),
                (
                    "cod_fis",
                    models.ForeignKey(
                        blank=True,
                        db_column="COD_FIS",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="personalecontatti",
                        to="addressbook.personale",
                        to_field="cod_fis",
                    ),
                ),
            ],
            options={
                "db_table": "PERSONALE_CONTATTI",
                "managed": True,
            },
        ),
    ]
