# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
        ("addressbook", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personaleattivotuttiruoli",
            name="cd_uo_aff_org",
            field=models.ForeignKey(
                blank=True,
                db_column="CD_UO_AFF_ORG",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="structures.unitaorganizzativa",
            ),
        ),
        migrations.AddField(
            model_name="personale",
            name="cd_uo_aff_org",
            field=models.ForeignKey(
                blank=True,
                db_column="CD_UO_AFF_ORG",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="structures.unitaorganizzativa",
            ),
        ),
        migrations.AddField(
            model_name="personale",
            name="comu_res",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_COMU_RES",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="structures.comuniall",
            ),
        ),
        migrations.AddField(
            model_name="personale",
            name="user_ins",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_ins_personale",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personale",
            name="user_mod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_mod_personale",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalecontatti",
            unique_together={("id_ab", "cd_tipo_cont", "prg_priorita")},
        ),
    ]
