# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaleattivotuttiruoli',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personaleattivotuttiruoli', to='addressbook.personale', to_field='matricola'),
        ),
    ]
