# Generated by Django 4.2.20 on 2026-06-04 12:51

from django.db import migrations, models
import generics.validators
import patents.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrevettoDatiBase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_univoco', models.CharField(db_column='ID_UNIVOCO', max_length=500, unique=True)),
                ('titolo', models.TextField(db_column='TITOLO')),
                ('url_immagine', models.URLField(blank=True, db_column='URL_IMMAGINE', max_length=2000, null=True)),
                ('breve_descrizione', models.TextField(db_column='BREVE_DESCRIZIONE')),
                ('url_knowledge_share', models.URLField(blank=True, db_column='URL_KNOWLEDGE_SHARE', max_length=2000, null=True)),
                ('applicazioni', models.TextField(blank=True, db_column='APPLICAZIONI', null=True)),
                ('vantaggi', models.TextField(blank=True, db_column='VANTAGGI', null=True)),
                ('trl_iniziale', models.PositiveSmallIntegerField(blank=True, db_column='TRL_INIZIALE', null=True)),
                ('trl_aggiornato', models.PositiveSmallIntegerField(blank=True, db_column='TRL_AGGIORNATO', null=True)),
                ('proprieta', models.TextField(db_column='PROPRIETA')),
                ('data_priorita', models.DateField(blank=True, db_column='DATA_PRIORITA', null=True)),
                ('area_ks', models.CharField(blank=True, db_column='AREA_KS', max_length=2000, null=True)),
                ('nome_file_logo', models.FileField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True, upload_to=patents.settings.patents_media_path, validators=[generics.validators.validate_image_file_extension, generics.validators.validate_file_size])),
                ('valorizzazione', models.CharField(blank=True, db_column='VALORIZZAZIONE', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='ATTIVO', default=True)),
                ('ordinamento', models.IntegerField(db_column='ORDINE', default=10)),
            ],
            options={
                'db_table': 'BREVETTO_DATI_BASE',
                'ordering': ['ordinamento'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrevettoDirittiCommerciali',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_diritto', models.CharField(db_column='DESCR_DIRITTO', max_length=1000)),
            ],
            options={
                'db_table': 'BREVETTO_DIRITTI_COMMERCIALI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrevettoDisponibilita',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_disponibilita', models.CharField(db_column='DESCR_DISPONIBILITA', max_length=1000)),
            ],
            options={
                'db_table': 'BREVETTO_DISPONIBILITA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrevettoInventori',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cognomenome_origine', models.CharField(db_column='COGNOMENOME_ORIGINE', max_length=200)),
            ],
            options={
                'db_table': 'BREVETTO_INVENTORI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrevettoStatusLegale',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_status', models.CharField(db_column='DESCR_STATUS', max_length=1000)),
            ],
            options={
                'db_table': 'BREVETTO_STATUS_LEGALE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrevettoTerritori',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('territorio', models.CharField(db_column='TERRITORIO', max_length=80)),
            ],
            options={
                'db_table': 'BREVETTO_TERRITORI',
                'managed': False,
            },
        ),
    ]
