# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion
import generics.validators
import patents.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrevettoDatiBase",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "id_univoco",
                    models.CharField(
                        db_column="ID_UNIVOCO", max_length=500, unique=True
                    ),
                ),
                ("titolo", models.TextField(db_column="TITOLO")),
                (
                    "url_immagine",
                    models.URLField(
                        blank=True, db_column="URL_IMMAGINE", max_length=2000, null=True
                    ),
                ),
                ("breve_descrizione", models.TextField(db_column="BREVE_DESCRIZIONE")),
                (
                    "url_knowledge_share",
                    models.URLField(
                        blank=True,
                        db_column="URL_KNOWLEDGE_SHARE",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "applicazioni",
                    models.TextField(blank=True, db_column="APPLICAZIONI", null=True),
                ),
                (
                    "vantaggi",
                    models.TextField(blank=True, db_column="VANTAGGI", null=True),
                ),
                (
                    "trl_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, db_column="TRL_INIZIALE", null=True
                    ),
                ),
                (
                    "trl_aggiornato",
                    models.PositiveSmallIntegerField(
                        blank=True, db_column="TRL_AGGIORNATO", null=True
                    ),
                ),
                ("proprieta", models.TextField(db_column="PROPRIETA")),
                (
                    "data_priorita",
                    models.DateField(blank=True, db_column="DATA_PRIORITA", null=True),
                ),
                (
                    "area_ks",
                    models.CharField(
                        blank=True, db_column="AREA_KS", max_length=2000, null=True
                    ),
                ),
                (
                    "nome_file_logo",
                    models.FileField(
                        blank=True,
                        db_column="NOME_FILE_LOGO",
                        max_length=1000,
                        null=True,
                        upload_to=patents.settings.patents_media_path,
                        validators=[
                            generics.validators.validate_image_file_extension,
                            generics.validators.validate_file_size,
                        ],
                    ),
                ),
                (
                    "valorizzazione",
                    models.CharField(
                        blank=True,
                        db_column="VALORIZZAZIONE",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_column="ATTIVO", default=True)),
                ("ordinamento", models.IntegerField(db_column="ORDINE", default=10)),
                (
                    "area_tecnologica",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_AREA_TECNOLOGICA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.tipologiaareatecnologica",
                    ),
                ),
            ],
            options={
                "db_table": "BREVETTO_DATI_BASE",
                "ordering": ["ordinamento"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BrevettoDirittiCommerciali",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_diritto",
                    models.CharField(db_column="DESCR_DIRITTO", max_length=1000),
                ),
            ],
            options={
                "db_table": "BREVETTO_DIRITTI_COMMERCIALI",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BrevettoDisponibilita",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_disponibilita",
                    models.CharField(db_column="DESCR_DISPONIBILITA", max_length=1000),
                ),
            ],
            options={
                "db_table": "BREVETTO_DISPONIBILITA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BrevettoStatusLegale",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_status",
                    models.CharField(db_column="DESCR_STATUS", max_length=1000),
                ),
            ],
            options={
                "db_table": "BREVETTO_STATUS_LEGALE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BrevettoTerritori",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("territorio", models.CharField(db_column="TERRITORIO", max_length=80)),
            ],
            options={
                "db_table": "BREVETTO_TERRITORI",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BrevettoInventori",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "cognomenome_origine",
                    models.CharField(db_column="COGNOMENOME_ORIGINE", max_length=200),
                ),
                (
                    "brevetto",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_BREVETTO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patents.brevettodatibase",
                    ),
                ),
                (
                    "matricola_inventore",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE_MATRICOLA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
            ],
            options={
                "db_table": "BREVETTO_INVENTORI",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="brevettodatibase",
            name="diritto_commerciale",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_DIRITTO_COMMERCIALE",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patents.brevettodiritticommerciali",
            ),
        ),
        migrations.AddField(
            model_name="brevettodatibase",
            name="disponibilita",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_DISPONIBILITA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patents.brevettodisponibilita",
            ),
        ),
        migrations.AddField(
            model_name="brevettodatibase",
            name="status_legale",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_STATUS_LEGALE",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patents.brevettostatuslegale",
            ),
        ),
        migrations.AddField(
            model_name="brevettodatibase",
            name="territorio",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_BREVETTO_TERRITORI",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patents.brevettoterritori",
            ),
        ),
    ]
