# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettoinventori',
            name='brevetto',
            field=models.ForeignKey(blank=True, db_column='ID_BREVETTO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brevettoinventori', to='patents.brevettodatibase'),
        ),
    ]
