from django.conf import settings

ALLOWED_PROFILE_ID = getattr(settings, 'ALLOWED_PROFILE_ID', [])
ADDRESSBOOK_FRIENDLY_URL_MAIN_EMAIL_DOMAIN = getattr(settings, 'ADDRESSBOOK_FRIENDLY_URL_MAIN_EMAIL_DOMAIN', '')
PERSON_CONTACTS_TO_TAKE = getattr(settings, 'PERSON_CONTACTS_TO_TAKE', [])
PERSON_CONTACTS_EXCLUDE_STRINGS = getattr(settings, 'PERSON_CONTACTS_EXCLUDE_STRINGS', [])
