# Generated by Django 4.2.20 on 2026-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RicercaAster1',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.TextField(db_column='DESCRIZIONE')),
            ],
            options={
                'db_table': 'RICERCA_ASTER1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaAster2',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=200)),
            ],
            options={
                'db_table': 'RICERCA_ASTER2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaDocenteLineaApplicata',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_inizio', models.DateField(blank=True, db_column='DT_INIZIO', null=True)),
                ('dt_fine', models.DateField(blank=True, db_column='DT_FINE', null=True)),
            ],
            options={
                'db_table': 'RICERCA_DOCENTE_LINEA_APPLICATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaDocenteLineaBase',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_inizio', models.DateField(blank=True, db_column='DT_INIZIO', null=True)),
                ('dt_fine', models.DateField(blank=True, db_column='DT_FINE', null=True)),
            ],
            options={
                'db_table': 'RICERCA_DOCENTE_LINEA_BASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaErc0',
            fields=[
                ('erc0_cod', models.CharField(db_column='ERC0_COD', max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=100)),
                ('description_en', models.CharField(blank=True, db_column='DESCRIPTION_EN', max_length=100, null=True)),
            ],
            options={
                'db_table': 'RICERCA_ERC0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaErc1',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cod_erc1', models.CharField(db_column='COD_ERC1', max_length=40, unique=True)),
                ('descrizione', models.TextField(db_column='DESCRIZIONE')),
            ],
            options={
                'db_table': 'RICERCA_ERC1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaErc2',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cod_erc2', models.CharField(db_column='COD_ERC2', max_length=60, unique=True)),
                ('descrizione', models.TextField(db_column='DESCRIZIONE')),
            ],
            options={
                'db_table': 'RICERCA_ERC2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaLineaApplicata',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=False)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=400)),
                ('descr_pubblicaz_prog_brevetto', models.TextField(blank=True, db_column='DESCR_PUBBLICAZ_PROG_BREVETTO', null=True)),
                ('anno', models.IntegerField(blank=True, db_column='ANNO', null=True)),
            ],
            options={
                'db_table': 'RICERCA_LINEA_APPLICATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaLineaBase',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=False)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=400)),
                ('descr_pubblicaz_prog_brevetto', models.TextField(blank=True, db_column='DESCR_PUBBLICAZ_PROG_BREVETTO', null=True)),
                ('anno', models.IntegerField(blank=True, db_column='ANNO', null=True)),
            ],
            options={
                'db_table': 'RICERCA_LINEA_BASE',
                'managed': False,
            },
        ),
    ]
