# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addressbook", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RicercaAster1",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("descrizione", models.TextField(db_column="DESCRIZIONE")),
            ],
            options={
                "db_table": "RICERCA_ASTER1",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaAster2",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=200),
                ),
                (
                    "ricerca_aster1",
                    models.ForeignKey(
                        db_column="ID_RICERCA_ASTER1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="research_lines.ricercaaster1",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_ra2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_ra2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_ASTER2",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaErc0",
            fields=[
                (
                    "erc0_cod",
                    models.CharField(
                        db_column="ERC0_COD",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="DESCRIPTION", max_length=100),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        db_column="DESCRIPTION_EN",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_ERC0",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaErc1",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "cod_erc1",
                    models.CharField(db_column="COD_ERC1", max_length=40, unique=True),
                ),
                ("descrizione", models.TextField(db_column="DESCRIZIONE")),
                (
                    "ricerca_erc0_cod",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_RICERCA_ERC0",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research_lines.ricercaerc0",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_re1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_re1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_ERC1",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaErc2",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "cod_erc2",
                    models.CharField(db_column="COD_ERC2", max_length=60, unique=True),
                ),
                ("descrizione", models.TextField(db_column="DESCRIZIONE")),
                (
                    "ricerca_erc1",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_RICERCA_ERC1",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research_lines.ricercaerc1",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_re2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_re2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_ERC2",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaLineaBase",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=400),
                ),
                (
                    "descr_pubblicaz_prog_brevetto",
                    models.TextField(
                        blank=True, db_column="DESCR_PUBBLICAZ_PROG_BREVETTO", null=True
                    ),
                ),
                ("anno", models.IntegerField(blank=True, db_column="ANNO", null=True)),
                (
                    "ricerca_erc2",
                    models.ForeignKey(
                        db_column="ID_RICERCA_ERC2",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="research_lines.ricercaerc2",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_rlb",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_rlb",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_LINEA_BASE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaLineaApplicata",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=400),
                ),
                (
                    "descr_pubblicaz_prog_brevetto",
                    models.TextField(
                        blank=True, db_column="DESCR_PUBBLICAZ_PROG_BREVETTO", null=True
                    ),
                ),
                ("anno", models.IntegerField(blank=True, db_column="ANNO", null=True)),
                (
                    "ricerca_aster2",
                    models.ForeignKey(
                        db_column="ID_RICERCA_ASTER2",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="research_lines.ricercaaster2",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_rla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_rla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_LINEA_APPLICATA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaDocenteLineaBase",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dt_inizio",
                    models.DateField(blank=True, db_column="DT_INIZIO", null=True),
                ),
                (
                    "dt_fine",
                    models.DateField(blank=True, db_column="DT_FINE", null=True),
                ),
                (
                    "personale",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressbook.personale",
                    ),
                ),
                (
                    "ricerca_linea_base",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_RICERCA_LINEA_BASE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research_lines.ricercalineabase",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_rdlb",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_rdlb",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_DOCENTE_LINEA_BASE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaDocenteLineaApplicata",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dt_inizio",
                    models.DateField(blank=True, db_column="DT_INIZIO", null=True),
                ),
                (
                    "dt_fine",
                    models.DateField(blank=True, db_column="DT_FINE", null=True),
                ),
                (
                    "personale",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressbook.personale",
                    ),
                ),
                (
                    "ricerca_linea_applicata",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_RICERCA_LINEA_APPLICATA",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research_lines.ricercalineaapplicata",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_rdla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_rdla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_DOCENTE_LINEA_APPLICATA",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="ricercaaster1",
            name="ricerca_erc0_cod",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_RICERCA_ERC0",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="research_lines.ricercaerc0",
            ),
        ),
        migrations.AddField(
            model_name="ricercaaster1",
            name="user_ins",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_ins_ra1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ricercaaster1",
            name="user_mod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_mod_ra1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
