# Generated by Django 4.2.20 on 2026-06-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComuniAll',
            fields=[
                ('id_comune', models.IntegerField(db_column='ID_COMUNE', primary_key=True, serialize=False)),
                ('ds_comune', models.CharField(blank=True, db_column='DS_COMUNE', max_length=255, null=True)),
                ('cd_catasto', models.CharField(blank=True, db_column='CD_CATASTO', max_length=255, null=True, unique=True)),
                ('cd_istat', models.CharField(blank=True, db_column='CD_ISTAT', max_length=6, null=True)),
                ('dt_costituzione', models.DateTimeField(blank=True, db_column='DT_COSTITUZIONE', null=True)),
                ('dt_cessazione', models.DateTimeField(blank=True, db_column='DT_CESSAZIONE', null=True)),
                ('id_prov', models.IntegerField(blank=True, db_column='ID_PROV', null=True)),
                ('cd_sigla', models.CharField(blank=True, db_column='CD_SIGLA', max_length=2, null=True)),
                ('ds_prov', models.CharField(blank=True, db_column='DS_PROV', max_length=255, null=True)),
                ('id_nazione', models.IntegerField(blank=True, db_column='ID_NAZIONE', null=True)),
                ('cd_iso3166_1_a2_nazione', models.CharField(blank=True, db_column='CD_ISO3166_1_A2_NAZIONE', max_length=2, null=True)),
                ('ds_nazione', models.CharField(blank=True, db_column='DS_NAZIONE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'COMUNI_ALL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDipartimento',
            fields=[
                ('dip_id', models.IntegerField(db_column='DIP_ID', primary_key=True, serialize=False)),
                ('id_dip_gda', models.IntegerField(db_column='ID_DIP_GDA', unique=True)),
                ('dip_cod', models.CharField(blank=True, db_column='DIP_COD', max_length=40, null=True, unique=True)),
                ('dip_des_it', models.CharField(blank=True, db_column='DIP_DESC_ITA', max_length=255, null=True)),
                ('dip_des_eng', models.CharField(blank=True, db_column='DIP_DESC_ENG', max_length=255, null=True)),
                ('dip_nome_breve', models.CharField(blank=True, db_column='DIP_DESC_BREVE_ITA', max_length=100, null=True)),
                ('dt_ins', models.DateTimeField(blank=True, db_column='DT_INS', null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDipartimentoGruppi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_breve_it', models.CharField(db_column='DESCR_BREVE_IT', max_length=1000)),
                ('descr_breve_en', models.CharField(blank=True, db_column='DESCR_BREVE_EN', max_length=1000, null=True)),
                ('descr_lunga_it', models.TextField(blank=True, db_column='DESCR_LUNGA_IT', null=True)),
                ('descr_lunga_en', models.TextField(blank=True, db_column='DESCR_LUNGA_EN', null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE', default=10)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=True)),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO_GRUPPI',
                'ordering': ('ordine',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDipartimentoGruppiComponenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cognome', models.CharField(blank=True, db_column='COGNOME', max_length=100, null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('funzione_it', models.CharField(blank=True, db_column='FUNZIONE_IT', max_length=1000, null=True)),
                ('funzione_en', models.CharField(blank=True, db_column='FUNZIONE_EN', max_length=1000, null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE', default=10)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=True)),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO_GRUPPI_COMPONENTI',
                'ordering': ('ordine',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitaOrganizzativa',
            fields=[
                ('uo', models.CharField(db_column='UO', max_length=40, primary_key=True, serialize=False)),
                ('id_ab', models.IntegerField(blank=True, db_column='ID_AB', null=True, unique=True)),
                ('cd_tipo_nodo', models.CharField(db_column='CD_TIPO_NODO', default='000', max_length=10)),
                ('ds_tipo_nodo', models.CharField(db_column='DS_TIPO_NODO', default='Non assegnato', max_length=255)),
                ('denominazione', models.CharField(db_column='DENOMINAZIONE', default='Non assegnato', max_length=255)),
                ('nome_esteso', models.CharField(db_column='NOME_ESTESO', default='Non assegnato', max_length=255)),
                ('nome_breve', models.CharField(db_column='NOME_BREVE', default='Non assegnato', max_length=50)),
                ('dt_inizio_val', models.DateTimeField(blank=True, db_column='DT_INIZIO_VAL', null=True)),
                ('dt_fine_val', models.DateTimeField(blank=True, db_column='DT_FINE_VAL', null=True)),
                ('dt_creazione', models.DateTimeField(blank=True, db_column='DT_CREAZIONE', null=True)),
                ('uo_padre', models.CharField(blank=True, db_column='UO_PADRE', max_length=40, null=True)),
                ('id_ab_padre', models.IntegerField(blank=True, db_column='ID_AB_PADRE', null=True)),
                ('cd_tipo_nodo_padre', models.CharField(blank=True, db_column='CD_TIPO_NODO_PADRE', max_length=10, null=True)),
                ('ds_tipo_nodo_padre', models.CharField(blank=True, db_column='DS_TIPO_NODO_PADRE', max_length=255, null=True)),
                ('cd_macrotipo_nodo_padre', models.CharField(blank=True, db_column='CD_MACROTIPO_NODO_PADRE', max_length=10, null=True)),
                ('denominazione_padre', models.CharField(blank=True, db_column='DENOMINAZIONE_PADRE', max_length=255, null=True)),
                ('nome_esteso_padre', models.CharField(blank=True, db_column='NOME_ESTESO_PADRE', max_length=255, null=True)),
                ('nome_breve_padre', models.CharField(blank=True, db_column='NOME_BREVE_PADRE', max_length=50, null=True)),
                ('dt_inizio_val_padre', models.DateTimeField(blank=True, db_column='DT_INIZIO_VAL_PADRE', null=True)),
                ('dt_fine_val_padre', models.DateTimeField(blank=True, db_column='DT_FINE_VAL_PADRE', null=True)),
                ('dt_creazione_padre', models.DateTimeField(blank=True, db_column='DT_CREAZIONE_PADRE', null=True)),
                ('cd_csa', models.CharField(blank=True, db_column='CD_CSA', max_length=40, null=True, unique=True)),
                ('ds_mission', models.TextField(blank=True, db_column='DS_MISSION', null=True)),
            ],
            options={
                'db_table': 'UNITA_ORGANIZZATIVA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitaOrganizzativaFunzioni',
            fields=[
                ('matricola', models.CharField(db_column='MATRICOLA', max_length=6, primary_key=True, serialize=False)),
                ('comparto', models.CharField(blank=True, db_column='COMPARTO', max_length=1, null=True)),
                ('ruolo', models.CharField(blank=True, db_column='RUOLO', max_length=4, null=True)),
                ('funzione', models.CharField(blank=True, db_column='FUNZIONE', max_length=6, null=True)),
                ('decorrenza', models.DateTimeField(blank=True, db_column='DECORRENZA', null=True)),
                ('termine', models.DateTimeField(blank=True, db_column='TERMINE', null=True)),
                ('ds_funzione', models.CharField(blank=True, db_column='DS_FUNZIONE', max_length=100, null=True)),
                ('fl_posorg', models.FloatField(blank=True, db_column='FL_POSORG', null=True)),
                ('fl_responsabile', models.FloatField(blank=True, db_column='FL_RESPONSABILE', null=True)),
                ('cd_funzbase', models.CharField(blank=True, db_column='CD_FUNZBASE', max_length=6, null=True)),
                ('id_ab', models.IntegerField(blank=True, db_column='ID_AB', null=True)),
            ],
            options={
                'db_table': 'UNITA_ORGANIZZATIVA_FUNZIONI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitaOrganizzativaTipoFunzioni',
            fields=[
                ('cd_tipo_nod', models.CharField(db_column='CD_TIPO_NOD', max_length=100, primary_key=True, serialize=False)),
                ('funzione', models.CharField(db_column='FUNZIONE', max_length=100)),
                ('descr_funzione', models.CharField(db_column='DESCR_FUNZIONE', max_length=1000)),
            ],
            options={
                'db_table': 'UNITA_ORGANIZZATIVA_TIPO_FUNZIONI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDipartimentoUrl',
            fields=[
                ('dip_cod', models.OneToOneField(db_column='ID_DIDATTICA_DIPARTIMENTO_COD', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='structures.didatticadipartimento', to_field='dip_cod')),
                ('dip_url', models.URLField(db_column='DIP_URL', max_length=4000)),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO_URL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerritorioIt',
            fields=[
                ('cd_catasto', models.OneToOneField(db_column='CD_CATASTO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='structures.comuniall')),
                ('cd_istat', models.CharField(blank=True, db_column='CD_ISTAT', max_length=6, null=True)),
                ('ds_comune', models.CharField(blank=True, db_column='DS_COMUNE', max_length=255, null=True)),
                ('cd_sigla', models.CharField(blank=True, db_column='CD_SIGLA', max_length=2, null=True)),
                ('ds_provincia', models.CharField(blank=True, db_column='DS_PROVINCIA', max_length=255, null=True)),
                ('cd_770_regio', models.CharField(blank=True, db_column='CD_770_REGIO', max_length=2, null=True)),
                ('ds_regione', models.CharField(blank=True, db_column='DS_REGIONE', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TERRITORIO_IT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitaOrganizzativaContatti',
            fields=[
                ('ab', models.OneToOneField(db_column='ID_AB', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='unitaorganizzativacontatti', serialize=False, to='structures.unitaorganizzativa', to_field='id_ab')),
                ('contatto', models.CharField(blank=True, db_column='CONTATTO', max_length=255, null=True)),
                ('prg_priorita', models.IntegerField(db_column='PRG_PRIORITA')),
                ('denominazione', models.CharField(blank=True, db_column='DENOMINAZIONE', max_length=255, null=True)),
                ('dt_fine_val', models.DateTimeField(blank=True, db_column='DT_FINE_VAL', null=True)),
            ],
            options={
                'db_table': 'UNITA_ORGANIZZATIVA_CONTATTI',
                'managed': False,
            },
        ),
    ]
