# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitaorganizzativafunzioni',
            name='id',
        ),
        migrations.AlterField(
            model_name='unitaorganizzativacontatti',
            name='ab',
            field=models.OneToOneField(db_column='ID_AB', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='unitaorganizzativacontatti', serialize=False, to='structures.unitaorganizzativa', to_field='id_ab'),
        ),
        migrations.AlterField(
            model_name='unitaorganizzativafunzioni',
            name='cd_csa',
            field=models.ForeignKey(blank=True, db_column='CD_CSA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unitaorganizzativafunzioni', to='structures.unitaorganizzativa', to_field='cd_csa'),
        ),
        migrations.AlterField(
            model_name='unitaorganizzativafunzioni',
            name='matricola',
            field=models.CharField(db_column='MATRICOLA', max_length=6, primary_key=True, serialize=False),
        ),
    ]
