# Generated by Django 3.0.8 on 2020-08-02 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('nome', models.CharField(db_column='NOME', max_length=200)),
                ('cognome', models.CharField(db_column='COGNOME', max_length=200)),
                ('cod_fis', models.CharField(db_column='COD_FIS', max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('matricola', models.CharField(blank=True, db_column='MATRICOLA', max_length=100, null=True)),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_doc', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Docente',
                'db_table': 'DOCENTE',
            },
        ),
        migrations.CreateModel(
            name='RicercaAster1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=200)),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_aster1', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_aster1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aster 1',
                'db_table': 'RICERCA_ASTER1',
            },
        ),
        migrations.CreateModel(
            name='RicercaAster2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=200)),
                ('ricerca_aster1', models.ForeignKey(db_column='RICERCA_ASTER1_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaAster1')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_aster2', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_aster2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aster 2',
                'db_table': 'RICERCA_ASTER2',
            },
        ),
        migrations.CreateModel(
            name='RicercaErc1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('cod_erc1', models.CharField(db_column='COD_ERC1', max_length=40, unique=True)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=200)),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_erc1', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_erc1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Erc 1',
                'db_table': 'RICERCA_ERC1',
            },
        ),
        migrations.CreateModel(
            name='RicercaErc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('cod_erc2', models.CharField(db_column='COD_ERC2', max_length=60, unique=True)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=200)),
                ('ricerca_erc1', models.ForeignKey(blank=True, db_column='RICERCA_ERC1_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaErc1')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_erc2', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_erc2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Erc 2',
                'db_table': 'RICERCA_ERC2',
            },
        ),
        migrations.CreateModel(
            name='RicercaLineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=400)),
                ('descr_pubblicaz_prog_brevetto', models.CharField(blank=True, db_column='DESCR_PUBBLICAZ_PROG_BREVETTO', max_length=1000, null=True)),
                ('anno', models.IntegerField(blank=True, db_column='ANNO', null=True)),
                ('ricerca_erc2', models.ForeignKey(db_column='RICERCA_ERC2_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaErc2')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_lb', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_lb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Linea di Base',
                'db_table': 'RICERCA_LINEA_BASE',
            },
        ),
        migrations.CreateModel(
            name='RicercaLineaApplicata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=400)),
                ('descr_pubblicaz_prog_brevetto', models.CharField(blank=True, db_column='DESCR_PUBBLICAZ_PROG_BREVETTO', max_length=1000, null=True)),
                ('anno', models.IntegerField(blank=True, db_column='ANNO', null=True)),
                ('ricerca_aster2', models.ForeignKey(db_column='RICERCA_ASTER2_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaAster2')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_la', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_la', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Linea Applicata',
                'db_table': 'RICERCA_LINEA_APPLICATA',
            },
        ),
        migrations.CreateModel(
            name='RicercaGruppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('nome', models.CharField(db_column='NOME', max_length=200)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=2000)),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_rg', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_rg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gruppo di Ricerca',
                'db_table': 'RICERCA_GRUPPO',
            },
        ),
        migrations.CreateModel(
            name='RicercaDocenteLineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('dt_inizio', models.DateTimeField(blank=True, db_column='DT_INIZIO', null=True)),
                ('dt_fine', models.DateTimeField(blank=True, db_column='DT_FINE', null=True)),
                ('docente', models.ForeignKey(blank=True, db_column='DOCENTE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.Docente')),
                ('ricerca_linea_base', models.ForeignKey(blank=True, db_column='RICERCA_LINEA_BASE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaLineaBase')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_dlb', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_dlb', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Docente Linea Base',
                'db_table': 'RICERCA_DOCENTE_LINEA_BASE',
            },
        ),
        migrations.CreateModel(
            name='RicercaDocenteLineaApplicata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('dt_inizio', models.DateTimeField(blank=True, db_column='DT_INIZIO', null=True)),
                ('dt_fine', models.DateTimeField(blank=True, db_column='DT_FINE', null=True)),
                ('docente', models.ForeignKey(blank=True, db_column='DOCENTE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.Docente')),
                ('ricerca_linea_applicata', models.ForeignKey(blank=True, db_column='RICERCA_LINEA_APPLICATA_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaLineaApplicata')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_dla', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_dla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Docente Linea Applicata',
                'db_table': 'RICERCA_DOCENTE_LINEA_APPLICATA',
            },
        ),
        migrations.CreateModel(
            name='RicercaDocenteGruppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('dt_inizio', models.DateTimeField(blank=True, db_column='DT_INIZIO', null=True)),
                ('dt_fine', models.DateTimeField(blank=True, db_column='DT_FINE', null=True)),
                ('docente', models.ForeignKey(blank=True, db_column='DOCENTE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.Docente')),
                ('ricerca_gruppo', models.ForeignKey(db_column='RICERCA_GRUPPO_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.RicercaGruppo')),
                ('user_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ins_dg', to=settings.AUTH_USER_MODEL)),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mod_dg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Docente Gruppi di Ricerca',
                'db_table': 'RICERCA_DOCENTE_GRUPPO',
            },
        ),
    ]
