# Generated by Django 3.1.5 on 2021-02-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RicercaErc0',
            fields=[
                ('erc0_cod', models.CharField(db_column='ERC0_COD', max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=100)),
            ],
            options={
                'db_table': 'ricerca_erc0',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ricercaaster1',
            name='ricerca_erc0_cod',
            field=models.ForeignKey(blank=True, db_column='RICERCA_ERC0_COD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.ricercaerc0'),
        ),
        migrations.AddField(
            model_name='ricercaerc1',
            name='ricerca_erc0_cod',
            field=models.ForeignKey(blank=True, db_column='RICERCA_ERC0_COD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.ricercaerc0'),
        ),
    ]
