# Generated by Django 3.2 on 2021-06-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaleTipoContatto',
            fields=[
                ('cod_contatto', models.CharField(db_column='COD_CONTATTO', max_length=20, primary_key=True, serialize=False)),
                ('descr_contatto', models.CharField(db_column='DESCR_CONTATTO', max_length=200)),
            ],
            options={
                'db_table': 'PERSONALE_TIPO_CONTATTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaleContatti',
            fields=[
                ('id_ab', models.IntegerField(db_column='ID_AB', primary_key=True, serialize=False)),
                ('cod_fis', models.CharField(blank=True, db_column='COD_FIS', max_length=16, null=True)),
                ('contatto', models.CharField(blank=True, db_column='CONTATTO', max_length=255, null=True)),
                ('prg_priorita', models.IntegerField(db_column='PRG_PRIORITA')),
                ('dt_ins_mod', models.DateField(blank=True, db_column='DT_INS_MOD', null=True)),
                ('cd_tipo_cont', models.ForeignKey(db_column='CD_TIPO_CONT', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personaletipocontatto')),
            ],
            options={
                'db_table': 'PERSONALE_CONTATTI',
                'managed': True,
                'unique_together': {('id_ab', 'cd_tipo_cont', 'prg_priorita')},
            },
        ),
    ]
