# Generated by Django 3.1.5 on 2021-02-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticacdslingua',
            name='cdsord',
            field=models.ForeignKey(blank=True, db_column='CDSORD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticacds', to_field='cdsord_id'),
        ),
    ]
