# Generated by Django 3.2.4 on 2021-06-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0004_alter_personalecontatti_cod_fis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='breve',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='data_fin',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='data_in',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='data_ins',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='data_mod',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='descr_tipo',
        ),
        migrations.RemoveField(
            model_name='unitaorganizzativa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='cd_macrotipo_nodo_padre',
            field=models.CharField(blank=True, db_column='CD_MACROTIPO_NODO_PADRE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='cd_tipo_nodo',
            field=models.CharField(db_column='CD_TIPO_NODO', default='000', max_length=10),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='cd_tipo_nodo_padre',
            field=models.CharField(blank=True, db_column='CD_TIPO_NODO_PADRE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='denominazione',
            field=models.CharField(db_column='DENOMINAZIONE', default='Non assegnato', max_length=255),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='denominazione_padre',
            field=models.CharField(blank=True, db_column='DENOMINAZIONE_PADRE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='ds_tipo_nodo',
            field=models.CharField(db_column='DS_TIPO_NODO', default='Non assegnato', max_length=255),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='ds_tipo_nodo_padre',
            field=models.CharField(blank=True, db_column='DS_TIPO_NODO_PADRE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='dt_creazione',
            field=models.DateTimeField(blank=True, db_column='DT_CREAZIONE', null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='dt_creazione_padre',
            field=models.DateTimeField(blank=True, db_column='DT_CREAZIONE_PADRE', null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='dt_fine_val',
            field=models.DateTimeField(blank=True, db_column='DT_FINE_VAL', null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='dt_fine_val_padre',
            field=models.DateTimeField(blank=True, db_column='DT_FINE_VAL_PADRE', null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='dt_inizio_val',
            field=models.DateTimeField(blank=True, db_column='DT_INIZIO_VAL', null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='dt_inizio_val_padre',
            field=models.DateTimeField(blank=True, db_column='DT_INIZIO_VAL_PADRE', null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='nome_breve',
            field=models.CharField(db_column='NOME_BREVE', default='Non assegnato', max_length=50),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='nome_breve_padre',
            field=models.CharField(blank=True, db_column='NOME_BREVE_PADRE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='nome_esteso',
            field=models.CharField(db_column='NOME_ESTESO', default='Non assegnato', max_length=255),
        ),
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='nome_esteso_padre',
            field=models.CharField(blank=True, db_column='NOME_ESTESO_PADRE', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitaorganizzativa',
            name='id_ab',
            field=models.IntegerField(blank=True, db_column='ID_AB', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unitaorganizzativa',
            name='uo_padre',
            field=models.CharField(blank=True, db_column='UO_PADRE', max_length=40, null=True),
        ),
        migrations.RenameModel(
            old_name='PersonaleTipoContatto',
            new_name='PersonaleUoTipoContatto',
        ),
        migrations.AlterModelTable(
            name='personaleuotipocontatto',
            table='PERSONALE_UO_TIPO_CONTATTO',
        ),
        migrations.CreateModel(
            name='UnitaOrganizzativaContatti',
            fields=[
                ('id_ab', models.OneToOneField(db_column='ID_AB', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ricerca_app.unitaorganizzativa')),
                ('contatto', models.CharField(blank=True, db_column='CONTATTO', max_length=255, null=True)),
                ('prg_priorita', models.IntegerField(db_column='PRG_PRIORITA')),
                ('denominazione', models.CharField(blank=True, db_column='DENOMINAZIONE', max_length=255, null=True)),
                ('dt_fine_val', models.DateTimeField(blank=True, db_column='DT_FINE_VAL', null=True)),
                ('cd_tipo_cont', models.ForeignKey(db_column='CD_TIPO_CONT', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personaleuotipocontatto')),
            ],
            options={
                'db_table': 'UNITA_ORGANIZZATIVA_CONTATTI',
                'managed': True,
                'unique_together': {('id_ab', 'cd_tipo_cont', 'prg_priorita')},
            },
        ),
    ]
