# Generated by Django 3.0.8 on 2020-09-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0004_auto_20200912_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricercaaster2',
            name='descrizione',
            field=models.CharField(db_column='DESCRIZIONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='ricercalineaapplicata',
            name='descrizione',
            field=models.CharField(db_column='DESCRIZIONE', max_length=400),
        ),
        migrations.AlterField(
            model_name='ricercalineabase',
            name='descr_pubblicaz_prog_brevetto',
            field=models.TextField(blank=True, db_column='DESCR_PUBBLICAZ_PROG_BREVETTO', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ricercalineabase',
            name='descrizione',
            field=models.CharField(db_column='DESCRIZIONE', max_length=400),
        ),
    ]
