# Generated by Django 3.2.4 on 2021-07-09 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0006_alter_didatticacdslingua_cdsord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funzioniunitaorganizzativa',
            name='cod_fis',
            field=models.ForeignKey(blank=True, db_column='COD_FIS', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='cod_fis'),
        ),
        migrations.AlterField(
            model_name='personalecontatti',
            name='cod_fis',
            field=models.ForeignKey(blank=True, db_column='COD_FIS', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personalecontatti', to='ricerca_app.personale', to_field='cod_fis'),
        ),
    ]
