# Generated by Django 3.2.4 on 2021-07-19 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0007_auto_20210709_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaorganizzativacontatti',
            name='id_ab',
            field=models.OneToOneField(db_column='ID_AB', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ricerca_app.unitaorganizzativa', to_field='id_ab'),
        ),
    ]
