# Generated by Django 3.2 on 2021-07-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0011_auto_20210720_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoriodatibase',
            name='matricola_preposto_sicurezza',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_PREPOSTO_SICUREZZA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricola_preposto_sicurezza_personale', to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='laboratoriodatibase',
            name='matricola_referente_compilazione',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_REFERENTE_COMPILAZIONE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricola_referente_compilazione_personale', to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='laboratoriodatibase',
            name='matricola_responsabile_scientifico',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_RESPONSABILE_SCIENTIFICO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricola_responsabile_scientifico_personale', to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='laboratoriopersonalericerca',
            name='matricola_personale_ricerca',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_PERSONALE_RICERCA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='laboratoriopersonaletecnico',
            name='matricola_personale_tecnico',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_PERSONALE_TECNICO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
