# Generated by Django 3.2 on 2021-07-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0012_auto_20210721_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticatestiregolamento',
            name='testo_regdid_url',
            field=models.CharField(blank=True, db_column='TESTO_REGDID_URL', max_length=1024, null=True),
        ),
    ]
