# Generated by Django 3.2 on 2021-08-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0014_auto_20210730_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubblicazioneCollection',
            fields=[
                ('collection_id', models.IntegerField(db_column='COLLECTION_ID', primary_key=True, serialize=False)),
                ('collection_name', models.CharField(blank=True, db_column='COLLECTION_NAME', max_length=512, null=True)),
                ('type_miur', models.CharField(blank=True, db_column='TYPE_MIUR', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PUBBLICAZIONE_COLLECTION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PubblicazioneCommunity',
            fields=[
                ('community_id', models.IntegerField(db_column='COMMUNITY_ID', primary_key=True, serialize=False)),
                ('community_name', models.CharField(blank=True, db_column='COMMUNITY_NAME', max_length=512, null=True)),
                ('parent_community_id', models.IntegerField(blank=True, db_column='PARENT_COMMUNITY_ID', null=True)),
                ('parent_community_name', models.CharField(blank=True, db_column='PARENT_COMMUNITY_NAME', max_length=512, null=True)),
            ],
            options={
                'db_table': 'PUBBLICAZIONE_COMMUNITY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PubblicazioneDatiBase',
            fields=[
                ('item_id', models.IntegerField(db_column='ITEM_ID', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='TITLE', null=True)),
                ('des_abstract', models.TextField(blank=True, db_column='DES_ABSTRACT', null=True)),
                ('des_abstracteng', models.TextField(blank=True, db_column='DES_ABSTRACTENG', null=True)),
                ('lan_iso', models.CharField(blank=True, db_column='LAN_ISO', max_length=200, null=True)),
                ('lan_iso_i18n', models.CharField(blank=True, db_column='LAN_ISO_I18N', max_length=400, null=True)),
                ('date_issued_year', models.IntegerField(blank=True, db_column='DATE_ISSUED_YEAR', null=True)),
                ('pubblicazione', models.CharField(blank=True, db_column='PUBBLICAZIONE', max_length=1024, null=True)),
                ('label_pubblicazione', models.CharField(blank=True, db_column='LABEL_PUBBLICAZIONE', max_length=100, null=True)),
                ('contributors', models.TextField(blank=True, db_column='CONTRIBUTORS', null=True)),
                ('collection', models.ForeignKey(blank=True, db_column='COLLECTION_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.pubblicazionecollection')),
            ],
            options={
                'db_table': 'PUBBLICAZIONE_DATI_BASE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pubblicazionecollection',
            name='community',
            field=models.ForeignKey(blank=True, db_column='COMMUNITY_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.pubblicazionecommunity'),
        ),
        migrations.CreateModel(
            name='PubblicazioneAutori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(blank=True, db_column='CODICE_FISCALE', max_length=16, null=True)),
                ('first_name', models.CharField(blank=True, db_column='FIRST_NAME', max_length=1020, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=1020, null=True)),
                ('id_ab', models.ForeignKey(blank=True, db_column='ID_AB', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
                ('item', models.ForeignKey(db_column='ITEM_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.pubblicazionedatibase')),
            ],
            options={
                'db_table': 'PUBBLICAZIONE_AUTORI',
                'managed': True,
            },
        ),
    ]
