# Generated by Django 3.2 on 2021-08-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0015_auto_20210811_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personale',
            name='id_ab',
            field=models.IntegerField(db_column='ID_AB', unique=True),
        ),
        migrations.AlterField(
            model_name='pubblicazioneautori',
            name='id_ab',
            field=models.ForeignKey(blank=True, db_column='ID_AB', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='id_ab'),
        ),
    ]
