# Generated by Django 3.2.4 on 2021-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0017_pubblicazionedatibase_url_pubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='personale',
            name='cv_full_eng',
            field=models.TextField(blank=True, db_column='CV_FULL_ENG', null=True),
        ),
        migrations.AddField(
            model_name='personale',
            name='cv_full_it',
            field=models.TextField(blank=True, db_column='CV_FULL_IT', null=True),
        ),
        migrations.AddField(
            model_name='personale',
            name='cv_short_eng',
            field=models.TextField(blank=True, db_column='CV_SHORT_ENG', null=True),
        ),
        migrations.AddField(
            model_name='personale',
            name='cv_short_it',
            field=models.TextField(blank=True, db_column='CV_SHORT_IT', null=True),
        ),
    ]
