# Generated by Django 3.2.7 on 2021-09-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0018_auto_20210903_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacopertura',
            name='fat_part_stu_cod',
            field=models.CharField(blank=True, db_column='FAT_PART_STU_COD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='fat_part_stu_des',
            field=models.CharField(blank=True, db_column='FAT_PART_STU_DES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='part_fine',
            field=models.CharField(blank=True, db_column='PART_FINE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='part_ini',
            field=models.CharField(blank=True, db_column='PART_INI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='part_stu_cod',
            field=models.CharField(blank=True, db_column='PART_STU_COD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='part_stu_des',
            field=models.CharField(blank=True, db_column='PART_STU_DES', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='tipo_fat_stu_cod',
            field=models.CharField(blank=True, db_column='TIPO_FAT_STU_COD', max_length=20, null=True),
        ),
    ]
