# Generated by Django 3.2.7 on 2021-09-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0019_auto_20210914_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='didatticacopertura',
            name='aa_id',
        ),
        migrations.RemoveField(
            model_name='didatticacopertura',
            name='ore',
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='aa_ord_id',
            field=models.IntegerField(blank=True, db_column='AA_ORD_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='aa_regdid_id',
            field=models.IntegerField(blank=True, db_column='AA_REGDID_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='af_gen_cod',
            field=models.CharField(blank=True, db_column='AF_GEN_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='af_gen_des',
            field=models.CharField(blank=True, db_column='AF_GEN_DES', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='af_gen_des_eng',
            field=models.CharField(blank=True, db_column='AF_GEN_DES_ENG', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='af_gen_id',
            field=models.IntegerField(blank=True, db_column='AF_GEN_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='amb_id',
            field=models.IntegerField(blank=True, db_column='AMB_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='ambito_des',
            field=models.CharField(blank=True, db_column='AMBITO_DES', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='anno_corso',
            field=models.IntegerField(blank=True, db_column='ANNO_CORSO', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cds_cod',
            field=models.CharField(blank=True, db_column='CDS_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cds_des',
            field=models.CharField(blank=True, db_column='CDS_DES', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cds_id',
            field=models.IntegerField(blank=True, db_column='CDS_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cdsord_cod',
            field=models.CharField(blank=True, db_column='CDSORD_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cdsord_id',
            field=models.IntegerField(blank=True, db_column='CDSORD_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='ciclo_des',
            field=models.CharField(blank=True, db_column='CICLO_DES', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cod_fis_resp_did',
            field=models.CharField(blank=True, db_column='COD_FIS_RESP_DID', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='cognome_titolare',
            field=models.CharField(blank=True, db_column='COGNOME_TITOLARE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='des_tipo_ciclo',
            field=models.CharField(blank=True, db_column='DES_TIPO_CICLO', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='matricola_resp_did',
            field=models.CharField(blank=True, db_column='MATRICOLA_RESP_DID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='matricola_titolare',
            field=models.CharField(blank=True, db_column='MATRICOLA_TITOLARE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='nome_titolare',
            field=models.CharField(blank=True, db_column='NOME_TITOLARE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='non_erogabile_flg',
            field=models.IntegerField(blank=True, db_column='NON_EROGABILE_FLG', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='nota',
            field=models.TextField(blank=True, db_column='NOTA', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='of_id',
            field=models.IntegerField(blank=True, db_column='OF_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='ore_att_front',
            field=models.IntegerField(blank=True, db_column='ORE_ATT_FRONT', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='pds_cod',
            field=models.CharField(blank=True, db_column='PDS_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='pds_des',
            field=models.CharField(blank=True, db_column='PDS_DES', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='pds_regdid_id',
            field=models.IntegerField(blank=True, db_column='PDS_REGDID_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='peso',
            field=models.IntegerField(blank=True, db_column='PESO', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='regdid_cod',
            field=models.CharField(blank=True, db_column='REGDID_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='regdid_id',
            field=models.IntegerField(blank=True, db_column='REGDID_ID', null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='ruolo_resp_did_cod',
            field=models.CharField(blank=True, db_column='RUOLO_RESP_DID_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='sett_cod',
            field=models.CharField(blank=True, db_column='SETT_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='sett_des',
            field=models.CharField(blank=True, db_column='SETT_DES', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='stato_of_cod',
            field=models.CharField(blank=True, db_column='STATO_OF_COD', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='tipo_af_cod',
            field=models.CharField(blank=True, db_column='TIPO_AF_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='tipo_af_des',
            field=models.CharField(blank=True, db_column='TIPO_AF_DES', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='tipo_ciclo_cod',
            field=models.CharField(blank=True, db_column='TIPO_CICLO_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='tipo_comp_af_cod',
            field=models.CharField(blank=True, db_column='TIPO_COMP_AF_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='tipo_ins_cod',
            field=models.CharField(blank=True, db_column='TIPO_INS_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='um_peso_cod',
            field=models.CharField(blank=True, db_column='UM_PESO_COD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='didatticacopertura',
            name='dt_ins',
            field=models.DateTimeField(blank=True, db_column='DT_INS', null=True),
        ),
        migrations.AlterField(
            model_name='didatticacopertura',
            name='dt_mod',
            field=models.DateTimeField(blank=True, db_column='DT_MOD', null=True),
        ),
        migrations.AlterField(
            model_name='didatticacopertura',
            name='fat_part_stu_cod',
            field=models.CharField(blank=True, db_column='FAT_PART_STU_COD', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='didatticacopertura',
            name='fat_part_stu_des',
            field=models.CharField(blank=True, db_column='FAT_PART_STU_DES', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='didatticacopertura',
            name='part_stu_cod',
            field=models.CharField(blank=True, db_column='PART_STU_COD', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='didatticacopertura',
            name='part_stu_des',
            field=models.CharField(blank=True, db_column='PART_STU_DES', max_length=400, null=True),
        ),
    ]
