# Generated by Django 3.2.7 on 2021-11-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0021_auto_20210924_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personale',
            name='aff_org',
        ),
        migrations.RemoveField(
            model_name='personale',
            name='aff_org2',
        ),
        migrations.RemoveField(
            model_name='personale',
            name='aff_org3',
        ),
        migrations.RemoveField(
            model_name='personale',
            name='aff_org4',
        ),
        migrations.AddField(
            model_name='personale',
            name='cd_csa_aff_org2',
            field=models.CharField(blank=True, db_column='CD_CSA_AFF_ORG2', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='personale',
            name='cd_csa_aff_org3',
            field=models.CharField(blank=True, db_column='CD_CSA_AFF_ORG3', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='personale',
            name='cd_csa_aff_org4',
            field=models.CharField(blank=True, db_column='CD_CSA_AFF_ORG4', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='personale',
            name='cd_uo_aff_org',
            field=models.ForeignKey(blank=True, db_column='CD_UO_AFF_ORG', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.unitaorganizzativa'),
        ),
    ]
