# Generated by Django 3.2.7 on 2021-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0022_auto_20211105_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='personale',
            name='cd_csa',
            field=models.CharField(blank=True, db_column='CD_CSA', max_length=40, null=True),
        ),
    ]
