# Generated by Django 3.2.7 on 2021-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0023_personale_cd_csa'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitaorganizzativa',
            name='ds_mission',
            field=models.TextField(blank=True, db_column='DS_MISSION', null=True),
        ),
    ]
