# Generated by Django 3.2.7 on 2021-11-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0024_unitaorganizzativa_ds_mission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunzioniUnitaOrganizzativa',
            new_name='UnitaOrganizzativaFunzioni',
        ),
        migrations.AlterModelTable(
            name='unitaorganizzativafunzioni',
            table='UNITA_ORGANIZZATIVA_FUNZIONI',
        ),
    ]
