# Generated by Django 3.2.7 on 2021-11-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0026_auto_20211117_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioTipologiaAttivita',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=1000)),
            ],
            options={
                'db_table': 'LABORATORIO_TIPOLOGIA_ATTIVITA',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='laboratorioattivita',
            name='tipologia_attivita',
        ),
        migrations.AddField(
            model_name='laboratorioattivita',
            name='id_tipologia_attivita',
            field=models.ForeignKey(db_column='ID_TIPOLOGIA_ATTIVITA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.laboratoriotipologiaattivita'),
        ),
    ]
