# Generated by Django 3.2.7 on 2021-11-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0029_spinoffareainnovaziones3calabria_spinoffdatibase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpinoffAreaInnovazioneS3Calabria',
            new_name='SpinoffStartupAreaInnovazioneS3Calabria',
        ),
        migrations.RenameModel(
            old_name='SpinoffDatiBase',
            new_name='SpinoffStartupDatiBase',
        ),
        migrations.AlterModelTable(
            name='spinoffstartupareainnovaziones3calabria',
            table='SPINOFF_STARTUP_AREA_INNOVAZIONE_S3_CALABRIA',
        ),
        migrations.AlterModelTable(
            name='spinoffstartupdatibase',
            table='SPINOFF_STARTUP_DATI_BASE',
        ),
    ]
