# Generated by Django 3.2.7 on 2021-11-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0030_auto_20211125_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettoinventori',
            name='matricola_inventore',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_INVENTORE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
