# Generated by Django 3.2.7 on 2021-11-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0031_alter_brevettoinventori_matricola_inventore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgettoAmbitoTerritoriale',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ambito_territoriale', models.CharField(db_column='AMBITO_TERRITORIALE', max_length=100)),
            ],
            options={
                'db_table': 'PROGETTO_AMBITO_TERRITORIALE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgettoTipologiaProgramma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_programma', models.CharField(db_column='NOME_PROGRAMMA', max_length=1000)),
            ],
            options={
                'db_table': 'PROGETTO_TIPOLOGIA_PROGRAMMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgettoResponsabileScientifico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_origine', models.CharField(blank=True, db_column='NOME_ORIGINE', max_length=1000, null=True)),
                ('id_progetto', models.IntegerField(db_column='ID_PROGETTO')),
                ('matricola', models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'PROGETTO_RESPONSABILE_SCIENTIFICO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgettoDatiBase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('anno_avvio', models.IntegerField(blank=True, db_column='ANNO_AVVIO', null=True)),
                ('id_dipartimento', models.IntegerField(blank=True, db_column='ID_DIPARTIMENTO', null=True)),
                ('titolo', models.CharField(blank=True, db_column='TITOLO', max_length=4000, null=True)),
                ('descr_breve', models.TextField(blank=True, db_column='DESCR_BREVE', null=True)),
                ('url_immagine', models.CharField(blank=True, db_column='URL_IMMAGINE', max_length=1000, null=True)),
                ('abstract_ita', models.TextField(blank=True, db_column='ABSTRACT_ITA', null=True)),
                ('abstract_eng', models.TextField(blank=True, db_column='ABSTRACT_ENG', null=True)),
                ('url_sito_web', models.CharField(blank=True, db_column='URL_SITO_WEB', max_length=1000, null=True)),
                ('id_ambito_territoriale', models.ForeignKey(blank=True, db_column='ID_AMBITO_TERRITORIALE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.progettoambitoterritoriale')),
                ('id_area_tecnologica', models.ForeignKey(blank=True, db_column='ID_AREA_TECNOLOGICA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.tipologiaareatecnologica')),
                ('id_tipologia_programma', models.ForeignKey(blank=True, db_column='ID_TIPOLOGIA_PROGRAMMA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.progettotipologiaprogramma')),
            ],
            options={
                'db_table': 'PROGETTO_DATI_BASE',
                'managed': True,
            },
        ),
    ]
