# Generated by Django 3.2.7 on 2021-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0032_progettoambitoterritoriale_progettodatibase_progettoresponsabilescientifico_progettotipologiaprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitaOrganizzativaTipoFunzioni',
            fields=[
                ('cd_tipo_nod', models.CharField(db_column='CD_TIPO_NOD', max_length=100, primary_key=True, serialize=False)),
                ('funzione', models.CharField(db_column='FUNZIONE', max_length=100)),
                ('descr_funzione', models.CharField(db_column='DESCR_FUNZIONE', max_length=1000)),
            ],
            options={
                'db_table': 'UNITA_ORGANIZZATIVA_TIPO_FUNZIONI',
                'managed': True,
                'unique_together': {('cd_tipo_nod', 'funzione')},
            },
        ),
    ]
