# Generated by Django 3.2.7 on 2021-11-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0033_unitaorganizzativatipofunzioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progettodatibase',
            name='id_dipartimento',
            field=models.ForeignKey(blank=True, db_column='ID_DIPARTIMENTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticadipartimento'),
        ),
    ]
