# Generated by Django 3.2.7 on 2021-12-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0034_alter_progettodatibase_id_dipartimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinoffstartupdatibase',
            name='url_immagine',
        ),
        migrations.AddField(
            model_name='spinoffstartupdatibase',
            name='nome_file_logo',
            field=models.CharField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True),
        ),
    ]
