# Generated by Django 3.2.7 on 2021-12-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0035_auto_20211201_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoriodatibase',
            name='nome_file_logo',
            field=models.CharField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True),
        ),
    ]
