# Generated by Django 3.2.7 on 2021-12-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0037_auto_20211202_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personale',
            name='cd_csa',
        ),
    ]