# Generated by Django 3.2.7 on 2021-12-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0038_remove_personale_cd_csa'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevettodatibase',
            name='nome_file_logo',
            field=models.CharField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True),
        ),
    ]
