# Generated by Django 3.2.7 on 2021-12-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0040_alter_unitaorganizzativafunzioni_cd_csa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progettodatibase',
            name='id_dipartimento',
        ),
        migrations.AddField(
            model_name='progettodatibase',
            name='uo',
            field=models.ForeignKey(blank=True, db_column='UO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.unitaorganizzativa'),
        ),
    ]
