# Generated by Django 3.2.7 on 2021-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0041_auto_20211217_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacds',
            name='area_cds',
            field=models.CharField(blank=True, db_column='AREA_CDS', max_length=1000, null=True),
        ),
    ]
