# Generated by Django 3.2.7 on 2022-01-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0042_didatticacds_area_cds'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacds',
            name='area_cds_en',
            field=models.CharField(blank=True, db_column='AREA_CDS_EN', max_length=1000, null=True),
        ),
    ]
