# Generated by Django 3.2.7 on 2022-01-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0043_didatticacds_area_cds_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgettoRicercatore',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_origine', models.CharField(blank=True, db_column='NOME_ORIGINE', max_length=1000, null=True)),
                ('id_progetto', models.ForeignKey(db_column='ID_PROGETTO', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.progettodatibase')),
                ('matricola', models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'PROGETTO_RICERCATORE',
                'managed': True,
            },
        ),
    ]
