# Generated by Django 3.2.8 on 2022-01-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0043_didatticacds_area_cds_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaDipartimentoUrl',
            fields=[
                ('dip_cod', models.OneToOneField(db_column='DIP_COD', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ricerca_app.didatticadipartimento')),
                ('dip_url', models.CharField(db_column='DIP_URL', max_length=4000)),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO_URL',
                'managed': True,
            },
        ),
    ]
