# Generated by Django 3.2.8 on 2022-01-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0044_didatticadipartimentourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadipartimentourl',
            name='dip_cod',
            field=models.OneToOneField(db_column='DIP_COD', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ricerca_app.didatticadipartimento', to_field='dip_cod'),
        ),
    ]
