# Generated by Django 3.2.7 on 2022-02-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0048_auto_20220209_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaCdsAltriDati',
            fields=[
                ('cds', models.OneToOneField(db_column='CDS_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ricerca_app.didatticacds')),
                ('nome_origine_coordinatore', models.CharField(blank=True, db_column='NOME_ORIGINE_COORDINATORE', max_length=1000, null=True)),
                ('nome_origine_vice_coordinatore', models.CharField(blank=True, db_column='NOME_ORIGINE_VICE_COORDINATORE', max_length=1000, null=True)),
                # ('num_posti', models.IntegerField(blank=True, db_column='NUM_POSTI', null=True)),
                # ('modalita_iscrizione', models.TextField(blank=True, db_column='MODALITA_ISCRIZIONE', null=True)),
                ('matricola_coordinatore', models.ForeignKey(blank=True, db_column='MATRICOLA_COORDINATORE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinatore', to='ricerca_app.personale')),
                ('matricola_vice_coordinatore', models.ForeignKey(blank=True, db_column='MATRICOLA_VICE_COORDINATORE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_coordinatore', to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'DIDATTICA_CDS_ALTRI_DATI',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='anno_rilevazione',
            field=models.IntegerField(blank=True, db_column='ANNO_RILEVAZIONE', null=True),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='id_dipartiento_riferimento',
            field=models.ForeignKey(blank=True, db_column='ID_DIPARTIENTO_RIFERIMENTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticadipartimento'),
        ),
        migrations.CreateModel(
            name='DidatticaCdsAltriDatiUfficio',
            fields=[
                ('cds', models.OneToOneField(db_column='CDS_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ricerca_app.didatticacdsaltridati')),
                ('ordine', models.IntegerField(db_column='ORDINE')),
                ('nome_ufficio', models.CharField(blank=True, db_column='NOME_UFFICIO', max_length=1000, null=True)),
                ('nome_origine_riferimento', models.CharField(blank=True, db_column='NOME_ORIGINE_RIFERIMENTO', max_length=1000, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=1000, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=1000, null=True)),
                ('edificio', models.CharField(blank=True, db_column='EDIFICIO', max_length=1000, null=True)),
                ('piano', models.CharField(blank=True, db_column='PIANO', max_length=1000, null=True)),
                ('orari', models.CharField(blank=True, db_column='ORARI', max_length=1000, null=True)),
                ('sportello_online', models.CharField(blank=True, db_column='SPORTELLO_ONLINE', max_length=2000, null=True)),
                ('matricola_riferimento', models.ForeignKey(blank=True, db_column='MATRICOLA_RIFERIMENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'DIDATTICA_CDS_ALTRI_DATI_UFFICIO',
                'managed': True,
                'unique_together': {('cds', 'ordine')},
            },
        ),
    ]
