# Generated by Django 3.2.7 on 2022-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0049_auto_20220218_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='tipo_af_intercla_cod',
            field=models.CharField(blank=True, db_column='TIPO_AF_INTERCLA_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='tipo_af_intercla_des',
            field=models.CharField(blank=True, db_column='TIPO_AF_INTERCLA_DES', max_length=200, null=True),
        ),
    ]
