# Generated by Django 3.2.7 on 2022-02-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0051_didatticacoperturadettaglioore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaAttivitaFormativaModalita',
            fields=[
                ('mod_did_af_id', models.IntegerField(db_column='MOD_DID_AF_ID', primary_key=True, serialize=False)),
                ('mod_did_cod', models.CharField(db_column='MOD_DID_COD', max_length=40)),
                ('mod_did_des', models.CharField(db_column='MOD_DID_DES', max_length=1000)),
                ('af', models.ForeignKey(db_column='AF_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticaattivitaformativa')),
            ],
            options={
                'db_table': 'DIDATTICA_ATTIVITA_FORMATIVA_MODALITA',
                'managed': True,
            },
        ),
    ]
