# Generated by Django 3.2.7 on 2022-03-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0052_didatticaattivitaformativamodalita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='didatticapdsregolamento',
            name='aa_ord_id',
        ),
    ]
