# Generated by Django 3.2.7 on 2022-03-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0053_remove_didatticapdsregolamento_aa_ord_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unitaorganizzativafunzioni',
            table='FUNZIONI_UNITA_ORGANIZZATIVA',
        ),
    ]
