# Generated by Django 3.2.7 on 2022-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0056_alter_unitaorganizzativafunzioni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaorganizzativafunzioni',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
