# Generated by Django 3.2.7 on 2022-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0057_alter_unitaorganizzativafunzioni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitaorganizzativafunzioni',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
