# Generated by Django 3.2.7 on 2022-04-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0059_alter_altaformazionedatibase_matricola_direttore_scientifico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaDottoratoAttivitaFormativaAltriDocenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_didattica_dottorato_attivita_formativa', models.IntegerField(blank=True, db_column='ID_DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA', null=True)),
                ('matricola', models.CharField(blank=True, db_column='MATRICOLA', max_length=20, null=True)),
                ('cognome_nome_origine', models.CharField(blank=True, db_column='COGNOME_NOME_ORIGINE', max_length=200, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA_ALTRI_DOCENTI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDottoratoAttivitaFormativaDocente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_didattica_dottorato_attivita_formativa', models.IntegerField(blank=True, db_column='ID_DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA', null=True)),
                ('matricola', models.CharField(blank=True, db_column='MATRICOLA', max_length=20, null=True)),
                ('cognome_nome_origine', models.CharField(blank=True, db_column='COGNOME_NOME_ORIGINE', max_length=200, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA_DOCENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDottoratoAttivitaFormativa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_af', models.CharField(blank=True, db_column='NOME_AF', max_length=1000, null=True)),
                ('ssd', models.CharField(blank=True, db_column='SSD', max_length=1000, null=True)),
                ('numero_ore', models.IntegerField(blank=True, db_column='NUMERO_ORE', null=True)),
                ('cfu', models.IntegerField(blank=True, db_column='CFU', null=True)),
                ('tipo_af', models.CharField(blank=True, db_column='TIPO_AF', max_length=500, null=True)),
                ('rif_dottorato', models.CharField(blank=True, db_column='RIF_DOTTORATO', max_length=1000, null=True)),
                ('ciclo', models.IntegerField(db_column='CICLO')),
                ('struttura_proponente_origine', models.TextField(blank=True, db_column='STRUTTURA_PROPONENTE_ORIGINE')),
                ('contenuti_af', models.TextField(blank=True, db_column='CONTENUTI_AF', null=True)),
                ('prerequisiti', models.TextField(blank=True, db_column='PREREQUISITI', null=True)),
                ('num_min_studenti', models.IntegerField(blank=True, db_column='NUM_MIN_STUDENTI', null=True)),
                ('num_max_studenti', models.IntegerField(blank=True, db_column='NUM_MAX_STUDENTI', null=True)),
                ('verifica_finale', models.CharField(blank=True, db_column='VERIFICA_FINALE', max_length=2, null=True)),
                ('modalita_verifica', models.CharField(blank=True, db_column='MODALITA_VERIFICA', max_length=1000, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
                ('id_struttura_proponente', models.ForeignKey(blank=True, db_column='ID_STRUTTURA_PROPONENTE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.unitaorganizzativa')),
            ],
            options={
                'db_table': 'DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA',
                'managed': True,
            },
        ),
    ]
