# Generated by Django 3.2.7 on 2022-05-22 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0061_spinoffstartupdipartimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaleAttivoTuttiRuoli',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_ab', models.BigIntegerField(blank=True, db_column='ID_AB', null=True)),
                ('cod_fis', models.CharField(blank=True, db_column='COD_FIS', max_length=16, null=True)),
                ('cd_ruolo', models.CharField(blank=True, db_column='CD_RUOLO', max_length=4, null=True)),
                ('ds_ruolo', models.CharField(blank=True, db_column='DS_RUOLO', max_length=40, null=True)),
                ('ds_ruolo_breve', models.CharField(blank=True, db_column='DS_RUOLO_BREVE', max_length=20, null=True)),
                ('cd_tipo_ruolo', models.CharField(blank=True, db_column='CD_TIPO_RUOLO', max_length=2, null=True)),
                ('ds_tipo_ruolo', models.CharField(blank=True, db_column='DS_TIPO_RUOLO', max_length=80, null=True)),
                ('cd_inquadr', models.CharField(blank=True, db_column='CD_INQUADR', max_length=50, null=True)),
                ('ds_inquadr', models.CharField(blank=True, db_column='DS_INQUADR', max_length=80, null=True)),
                ('cd_uo_aff_org', models.CharField(blank=True, db_column='CD_UO_AFF_ORG', max_length=6, null=True)),
                ('ds_aff_org', models.CharField(blank=True, db_column='DS_AFF_ORG', max_length=255, null=True)),
                ('ds_aff_org_breve', models.CharField(blank=True, db_column='DS_AFF_ORG_BREVE', max_length=50, null=True)),
                ('fl_tipo_rap', models.FloatField(blank=True, db_column='FL_TIPO_RAP', null=True)),
                ('cd_ssd', models.CharField(blank=True, db_column='CD_SSD', max_length=12, null=True)),
                ('ds_ssd', models.CharField(blank=True, db_column='DS_SSD', max_length=100, null=True)),
                ('ds_ssd_breve', models.CharField(blank=True, db_column='DS_SSD_BREVE', max_length=20, null=True)),
                ('area_ssd', models.CharField(blank=True, db_column='AREA_SSD', max_length=2, null=True)),
                ('ds_area_ssd', models.CharField(blank=True, db_column='DS_AREA_SSD', max_length=100, null=True)),
                ('cd_riferimento', models.CharField(blank=True, db_column='CD_RIFERIMENTO', max_length=10, null=True)),
                ('ds_riferimento', models.CharField(blank=True, db_column='DS_RIFERIMENTO', max_length=120, null=True)),
                ('peso_inc', models.IntegerField(blank=True, db_column='PESO_INC', null=True)),
                ('peso_ric', models.IntegerField(blank=True, db_column='PESO_RIC', null=True)),
                ('sede', models.CharField(blank=True, db_column='SEDE', max_length=6, null=True)),
                ('ds_sede', models.CharField(blank=True, db_column='DS_SEDE', max_length=255, null=True)),
                ('dt_rap_ini', models.DateTimeField(blank=True, db_column='DT_RAP_INI', null=True)),
                ('cd_profilo', models.CharField(blank=True, db_column='CD_PROFILO', max_length=11, null=True)),
                ('ds_profilo', models.CharField(blank=True, db_column='DS_PROFILO', max_length=100, null=True)),
                ('fl_docente', models.IntegerField(blank=True, db_column='FL_DOCENTE', null=True)),
                ('cd_onorifico', models.CharField(blank=True, db_column='CD_ONORIFICO', max_length=4, null=True)),
                ('ds_onorifico', models.CharField(blank=True, db_column='DS_ONORIFICO', max_length=100, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.CharField(blank=True, db_column='USER_MOD_ID', max_length=32, null=True)),
                ('matricola', models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'PERSONALE_ATTIVO_TUTTI_RUOLI',
                'managed': True,
            },
        ),
    ]
