# Generated by Django 3.2.7 on 2022-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0062_personaleattivotuttiruoli'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalePrioritaRuolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_ruolo', models.CharField(blank=True, db_column='CD_RUOLO', max_length=50, null=True)),
                ('ds_ruolo', models.CharField(blank=True, db_column='DS_RUOLO', max_length=1000, null=True)),
                ('ds_ruolo_breve', models.CharField(blank=True, db_column='DS_RUOLO_BREVE', max_length=1000, null=True)),
                ('cd_tipo_ruolo', models.IntegerField(blank=True, db_column='CD_TIPO_RUOLO', null=True)),
                ('ds_tipo_ruolo', models.CharField(blank=True, db_column='DS_TIPO_RUOLO', max_length=1000, null=True)),
                ('cd_inquadr', models.CharField(blank=True, db_column='CD_INQUADR', max_length=100, null=True)),
                ('ds_inquadr', models.CharField(blank=True, db_column='DS_INQUADR', max_length=1000, null=True)),
                ('priorita', models.IntegerField(blank=True, db_column='PRIORITA', null=True)),
            ],
            options={
                'db_table': 'PERSONALE_PRIORITA_RUOLO',
                'managed': True,
            },
        ),
    ]
