# Generated by Django 3.2.7 on 2022-05-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0063_personaleprioritaruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaleattivotuttiruoli',
            name='matricola',
            field=models.CharField(blank=True, db_column='MATRICOLA', max_length=6, null=True),
        ),
    ]
