# Generated by Django 3.2.7 on 2022-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0064_alter_personaleattivotuttiruoli_matricola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaleprioritaruolo',
            name='cd_inquadr',
        ),
        migrations.RemoveField(
            model_name='personaleprioritaruolo',
            name='cd_tipo_ruolo',
        ),
        migrations.RemoveField(
            model_name='personaleprioritaruolo',
            name='ds_inquadr',
        ),
        migrations.RemoveField(
            model_name='personaleprioritaruolo',
            name='ds_ruolo_breve',
        ),
        migrations.RemoveField(
            model_name='personaleprioritaruolo',
            name='ds_tipo_ruolo',
        ),
        migrations.RemoveField(
            model_name='personaleprioritaruolo',
            name='id',
        ),
        migrations.AlterField(
            model_name='personaleprioritaruolo',
            name='cd_ruolo',
            field=models.CharField(db_column='CD_RUOLO', max_length=50, primary_key=True, serialize=False),
        ),
    ]
