# Generated by Django 3.2.13 on 2022-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0065_auto_20220601_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricercadocentelineaapplicata',
            name='dt_ins',
            field=models.DateTimeField(auto_now_add=True, db_column='DT_INS'),
        ),
    ]
