# Generated by Django 3.2.13 on 2022-07-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0065_auto_20220601_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricercadocentegruppo',
            name='personale',
            field=models.ForeignKey(blank=True, db_column='PERSONALE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.personale'),
        ),
        migrations.AlterField(
            model_name='ricercadocentegruppo',
            name='ricerca_gruppo',
            field=models.ForeignKey(db_column='RICERCA_GRUPPO_ID', on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.ricercagruppo'),
        ),
    ]
