# Generated by Django 3.2.13 on 2022-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0066_auto_20220706_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricercadocentelineaapplicata',
            name='dt_ins',
            field=models.DateTimeField(auto_now_add=True, db_column='DT_INS'),
        ),
        migrations.AlterField(
            model_name='ricercadocentelineaapplicata',
            name='dt_mod',
            field=models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True),
        ),
    ]
