# Generated by Django 3.2.13 on 2022-07-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0067_auto_20220712_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaleattivotuttiruoli',
            name='cd_uo_aff_org',
            field=models.ForeignKey(blank=True, db_column='CD_UO_AFF_ORG', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.unitaorganizzativa'),
        ),
    ]
