# Generated by Django 3.2.13 on 2022-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0068_alter_personaleattivotuttiruoli_cd_uo_aff_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacopertura',
            name='stato_coper_cod',
            field=models.CharField(blank=True, db_column='STATO_COPER_COD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='didatticacopertura',
            name='stato_coper_des',
            field=models.CharField(blank=True, db_column='STATO_COPER_DES', max_length=100, null=True),
        ),
    ]
