# Generated by Django 3.2.13 on 2022-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0069_auto_20220726_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='fat_part_stu_cod',
            field=models.CharField(blank=True, db_column='FAT_PART_STU_COD', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='fat_part_stu_des',
            field=models.CharField(blank=True, db_column='FAT_PART_STU_DES', max_length=500, null=True),
        ),
    ]
