# Generated by Django 3.2.13 on 2022-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0070_auto_20220726_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='af_pdr_id',
            field=models.IntegerField(blank=True, db_column='AF_PDR_ID', null=True),
        ),
    ]
