# Generated by Django 3.2.13 on 2022-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0071_didatticaattivitaformativa_af_pdr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='part_stu_cod',
            field=models.CharField(blank=True, db_column='PART_STU_COD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='part_stu_des',
            field=models.CharField(blank=True, db_column='PART_STU_DES', max_length=500, null=True),
        ),
    ]
