# Generated by Django 3.2.13 on 2022-08-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0072_auto_20220726_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='didatticaattivitaformativa',
            name='dt_ins',
        ),
        migrations.RemoveField(
            model_name='didatticaattivitaformativa',
            name='dt_mod',
        ),
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='non_erogabile_flg',
            field=models.PositiveIntegerField(blank=True, db_column='NON_EROGABILE_FLG', null=True),
        ),
        migrations.AddField(
            model_name='didatticaattivitaformativa',
            name='part_stu_id',
            field=models.IntegerField(blank=True, db_column='PART_STU_ID', null=True),
        ),
        migrations.AlterField(
            model_name='didatticaattivitaformativa',
            name='matricola_resp_did',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_RESP_DID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
