# Generated by Django 3.2.13 on 2022-09-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0073_auto_20220831_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticacdsaltridati',
            name='matricola_coordinatore',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_COORDINATORE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinatore', to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='didatticacdsaltridati',
            name='matricola_vice_coordinatore',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_VICE_COORDINATORE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vice_coordinatore', to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
