# Generated by Django 3.2.13 on 2022-09-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0074_auto_20220901_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didatticacdsaltridatiufficio',
            options={'managed': False},
        ),
    ]
