# Generated by Django 3.2.13 on 2022-09-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0075_alter_didatticacdsaltridatiufficio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didatticacdsaltridatiufficio',
            options={'managed': True},
        ),
    ]
