# Generated by Django 3.2.13 on 2022-09-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0076_alter_didatticacdsaltridatiufficio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacdsaltridatiufficio',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='didatticacdsaltridatiufficio',
            name='cds',
            field=models.ForeignKey(db_column='CDS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticacdsaltridati'),
        ),
        migrations.AlterField(
            model_name='didatticacdsaltridatiufficio',
            name='matricola_riferimento',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_RIFERIMENTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
