# Generated by Django 3.2.13 on 2022-09-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0077_auto_20220908_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='didatticacdsaltridatiufficio',
            unique_together=set(),
        ),
    ]
