# Generated by Django 3.2.13 on 2022-09-29 11:39

from django.db import migrations, models
import ricerca_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0081_auto_20220909_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettodatibase',
            name='nome_file_logo',
            field=models.FileField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True, upload_to=ricerca_app.models.patents_media_path),
        ),
    ]
