# Generated by Django 3.2.13 on 2022-09-29 12:49

from django.db import migrations, models
import django.db.models.deletion
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0082_alter_brevettodatibase_nome_file_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettodatibase',
            name='nome_file_logo',
            field=models.FileField(blank=True, db_column='NOME_FILE_LOGO', max_length=1000, null=True, upload_to=ricerca_app.models.patents_media_path, validators=[ricerca_app.validators.validate_image_file_extension, ricerca_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='brevettoinventori',
            name='id_brevetto',
            field=models.ForeignKey(blank=True, db_column='ID_BREVETTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.brevettodatibase'),
        ),
        migrations.AlterField(
            model_name='brevettoinventori',
            name='matricola_inventore',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_INVENTORE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
