# Generated by Django 3.2.13 on 2022-10-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0084_alter_spinoffstartupdatibase_nome_file_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='matricola_referente_unical',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_REFERENTE_UNICAL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
