# Generated by Django 3.2.13 on 2022-10-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0085_alter_spinoffstartupdatibase_matricola_referente_unical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffstartupdipartimento',
            name='id_didattica_dipartimento',
            field=models.ForeignKey(blank=True, db_column='ID_DIDATTICA_DIPARTIMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.didatticadipartimento'),
        ),
        migrations.AlterField(
            model_name='spinoffstartupdipartimento',
            name='id_spinoff_startup_dati_base',
            field=models.ForeignKey(db_column='ID_SPINOFF_STARTUP_DATI_BASE', on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.spinoffstartupdatibase'),
        ),
    ]
