# Generated by Django 3.2.13 on 2022-10-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0086_auto_20221005_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='progettodatibase',
            name='call',
            field=models.CharField(blank=True, db_column='CALL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='progettoresponsabilescientifico',
            name='id_progetto',
            field=models.ForeignKey(db_column='ID_PROGETTO', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.progettodatibase'),
        ),
    ]
