# Generated by Django 3.2.13 on 2022-10-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0088_auto_20221007_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progettoresponsabilescientifico',
            name='id_progetto',
            field=models.ForeignKey(db_column='ID_PROGETTO', on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.progettodatibase'),
        ),
        migrations.AlterField(
            model_name='progettoresponsabilescientifico',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='progettoricercatore',
            name='id_progetto',
            field=models.ForeignKey(db_column='ID_PROGETTO', on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.progettodatibase'),
        ),
        migrations.AlterField(
            model_name='progettoricercatore',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
