# Generated by Django 3.2.13 on 2022-10-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0089_auto_20221010_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentePtaBacheca',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_testo', models.CharField(db_column='TIPO_TESTO', max_length=100)),
                ('tipo_testo_en', models.CharField(blank=True, db_column='TIPO_TESTO_EN', max_length=100, null=True)),
                ('titolo', models.CharField(blank=True, db_column='TITOLO', max_length=200, null=True)),
                ('titolo_en', models.CharField(blank=True, db_column='TITOLO_EN', max_length=200, null=True)),
                ('testo', models.TextField(db_column='TESTO')),
                ('testo_en', models.TextField(blank=True, db_column='TESTO_EN', null=True)),
                ('url_testo', models.CharField(blank=True, db_column='URL_TESTO', max_length=400, null=True)),
                ('url_testo_en', models.CharField(blank=True, db_column='URL_TESTO_EN', max_length=400, null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE')),
                ('attivo', models.IntegerField(db_column='ATTIVO')),
                ('dt_pubblicazione', models.DateField(db_column='DT_PUBBLICAZIONE')),
                ('dt_inizio_validita', models.DateField(db_column='DT_INIZIO_VALIDITA')),
                ('dt_fine_validita', models.DateField(blank=True, db_column='DT_FINE_VALIDITA', null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('matricola', models.ForeignKey(db_column='MATRICOLA', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'DOCENTE_PTA_BACHECA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocentePtaAltriDati',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('path_foto', models.CharField(blank=True, db_column='PATH_FOTO', max_length=500, null=True)),
                ('path_cv_ita', models.CharField(blank=True, db_column='PATH_CV_ITA', max_length=500, null=True)),
                ('path_cv_en', models.CharField(blank=True, db_column='PATH_CV_EN', max_length=500, null=True)),
                ('breve_bio', models.TextField(blank=True, db_column='BREVE_BIO', null=True)),
                ('breve_bio_en', models.TextField(blank=True, db_column='BREVE_BIO_EN', null=True)),
                ('orario_ricevimento', models.TextField(blank=True, db_column='ORARIO_RICEVIMENTO', null=True)),
                ('orario_ricevimento_en', models.TextField(blank=True, db_column='ORARIO_RICEVIMENTO_EN', null=True)),
                ('orcid', models.CharField(blank=True, db_column='ORCID', max_length=100, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('matricola', models.OneToOneField(db_column='MATRICOLA', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'DOCENTE_PTA_ALTRI_DATI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocenteMaterialeDidattico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titolo', models.CharField(blank=True, db_column='TITOLO', max_length=200, null=True)),
                ('titolo_en', models.CharField(blank=True, db_column='TITOLO_EN', max_length=200, null=True)),
                ('testo', models.TextField(db_column='TESTO')),
                ('testo_en', models.TextField(blank=True, db_column='TESTO_EN', null=True)),
                ('url_testo', models.CharField(blank=True, db_column='URL_TESTO', max_length=400, null=True)),
                ('url_testo_en', models.CharField(blank=True, db_column='URL_TESTO_EN', max_length=400, null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE')),
                ('attivo', models.IntegerField(db_column='ATTIVO')),
                ('dt_pubblicazione', models.DateField(db_column='DT_PUBBLICAZIONE')),
                ('dt_inizio_validita', models.DateField(db_column='DT_INIZIO_VALIDITA')),
                ('dt_fine_validita', models.DateField(blank=True, db_column='DT_FINE_VALIDITA', null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('matricola', models.ForeignKey(db_column='MATRICOLA', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale')),
            ],
            options={
                'db_table': 'DOCENTE_MATERIALE_DIDATTICO',
                'managed': True,
            },
        ),
    ]
