# Generated by Django 3.2.13 on 2022-10-26 20:19

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0091_auto_20221025_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docenteptaaltridati',
            name='orcid',
            field=models.CharField(blank=True, db_column='ORCID', max_length=100, null=True, validators=[ricerca_app.validators.orcid_validator]),
        ),
        migrations.AlterField(
            model_name='docenteptaaltridati',
            name='path_cv_en',
            field=models.FileField(blank=True, db_column='PATH_CV_EN', max_length=1000, null=True, upload_to=ricerca_app.models.teacher_cv_en_media_path, validators=[ricerca_app.validators.validate_pdf_file_extension, ricerca_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='docenteptaaltridati',
            name='path_cv_ita',
            field=models.FileField(blank=True, db_column='PATH_CV_ITA', max_length=1000, null=True, upload_to=ricerca_app.models.teacher_cv_ita_media_path, validators=[ricerca_app.validators.validate_pdf_file_extension, ricerca_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='docenteptaaltridati',
            name='path_foto',
            field=models.FileField(blank=True, db_column='PATH_FOTO', max_length=1000, null=True, upload_to=ricerca_app.models.teacher_photo_media_path, validators=[ricerca_app.validators.validate_image_file_extension, ricerca_app.validators.validate_file_size]),
        ),
    ]
