# Generated by Django 3.2.13 on 2022-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0093_auto_20221027_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticadottoratoattivitaformativa',
            name='avvio',
            field=models.TextField(blank=True, db_column='AVVIO', null=True),
        ),
        migrations.AddField(
            model_name='didatticadottoratoattivitaformativa',
            name='fine',
            field=models.TextField(blank=True, db_column='FINE', null=True),
        ),
        migrations.AddField(
            model_name='didatticadottoratoattivitaformativa',
            name='note',
            field=models.TextField(blank=True, db_column='NOTE', null=True),
        ),
        migrations.AddField(
            model_name='didatticadottoratoattivitaformativa',
            name='orario_aule',
            field=models.TextField(blank=True, db_column='ORARIO_AULE', null=True),
        ),
        migrations.AddField(
            model_name='didatticadottoratoattivitaformativa',
            name='visualizza_orario',
            field=models.IntegerField(blank=True, db_column='VISUALIZZA_ORARIO', null=True),
        ),
    ]
