# Generated by Django 3.2.13 on 2022-11-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0094_auto_20221102_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativaaltridocenti',
            name='id_didattica_dottorato_attivita_formativa',
            field=models.ForeignKey(blank=True, db_column='ID_DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.didatticadottoratoattivitaformativa'),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativaaltridocenti',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativadocente',
            name='id_didattica_dottorato_attivita_formativa',
            field=models.ForeignKey(blank=True, db_column='ID_DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.didatticadottoratoattivitaformativa'),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativadocente',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.personale', to_field='matricola'),
        ),
    ]
