# Generated by Django 3.2.13 on 2022-12-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0095_auto_20221116_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='nome_af',
            field=models.CharField(db_column='NOME_AF', max_length=1000, null=True),
        ),
    ]
