# Generated by Django 3.2.13 on 2022-12-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0096_alter_didatticadottoratoattivitaformativa_nome_af'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='cfu',
            field=models.IntegerField(db_column='CFU', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='contenuti_af',
            field=models.TextField(db_column='CONTENUTI_AF', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='id_struttura_proponente',
            field=models.ForeignKey(db_column='ID_STRUTTURA_PROPONENTE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.unitaorganizzativa'),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='modalita_verifica',
            field=models.CharField(db_column='MODALITA_VERIFICA', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='numero_ore',
            field=models.IntegerField(db_column='NUMERO_ORE', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='rif_dottorato',
            field=models.CharField(db_column='RIF_DOTTORATO', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='ssd',
            field=models.CharField(db_column='SSD', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='tipo_af',
            field=models.CharField(db_column='TIPO_AF', max_length=500, null=True),
        ),
    ]
