# Generated by Django 3.2.13 on 2022-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0097_auto_20221207_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='avvio',
            field=models.DateTimeField(db_column='AVVIO', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='fine',
            field=models.DateTimeField(db_column='FINE', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='verifica_finale',
            field=models.IntegerField(db_column='VERIFICA_FINALE', null=True),
        ),
    ]
