# Generated by Django 3.2.13 on 2022-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0098_auto_20221216_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='verifica_finale',
            field=models.BooleanField(db_column='VERIFICA_FINALE', default=False),
        ),
    ]
