# Generated by Django 3.2.13 on 2022-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0099_alter_didatticadottoratoattivitaformativa_verifica_finale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='visualizza_orario',
            field=models.BooleanField(db_column='VISUALIZZA_ORARIO', default=False),
        ),
    ]
