# Generated by Django 3.2.13 on 2023-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0101_auto_20230328_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docenteptabacheca',
            name='attivo',
            field=models.BooleanField(db_column='ATTIVO'),
        ),
    ]
