# Generated by Django 3.2.13 on 2023-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0101_sitowebcdsdatibase_sitowebcdsdatiexceltmp_sitowebcdsexstudenti_sitowebcdslink_sitowebcdsslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitowebcdsdatibase',
            name='aa',
            field=models.PositiveIntegerField(blank=True, db_column='AA', null=True),
        ),
    ]
