# Generated by Django 3.2.13 on 2023-04-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0103_alter_docentematerialedidattico_attivo'),
        ('ricerca_app', '0103_sitowebcdsexstudenti_nome'),
    ]

    operations = [
    ]
