# Generated by Django 3.2.13 on 2023-04-19 15:40

from django.db import migrations, models
import django.db.models.deletion
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0104_merge_20230419_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitoWebCdsArticoliRegolamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(blank=True, db_column='NUMERO', null=True)),
                ('ordine', models.PositiveIntegerField(blank=True, db_column='ORDINE', null=True)),
                ('titolo', models.CharField(db_column='TITOLO', max_length=2000)),
                ('contenuto', models.TextField(db_column='CONTENUTO')),
                ('stato', models.CharField(blank=True, db_column='STATO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SITO_WEB_CDS_ARTICOLI_REGOLAMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SitoWebCdsTipologiaArticolo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cod_tipologia', models.CharField(db_column='COD_TIPOLOGIA', max_length=100)),
                ('descr_tipologia', models.CharField(db_column='DESCR_TIPOLOGIA', max_length=2000)),
                ('num_rif_articolo', models.PositiveIntegerField(blank=True, db_column='NUM_RIF_ARTICOLO', null=True)),
            ],
            options={
                'db_table': 'SITO_WEB_CDS_TIPOLOGIA_ARTICOLO',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='SitoWebCdsDatiExcelTmp',
            new_name='SitoWebCdsDatiExcelTmpOld',
        ),
        migrations.AddField(
            model_name='sitowebcdsdatibase',
            name='cds',
            field=models.ForeignKey(blank=True, db_column='CDS_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticacds'),
        ),
        migrations.AddField(
            model_name='sitowebcdsdatibase',
            name='id_didattica_regolamento',
            field=models.ForeignKey(blank=True, db_column='ID_DIDATTICA_REGOLAMENTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticaregolamento'),
        ),
        migrations.AddField(
            model_name='sitowebcdsexstudenti',
            name='foto',
            field=models.FileField(blank=True, db_column='FOTO', max_length=1000, null=True, upload_to=ricerca_app.models.cds_websites_exstudents_media_path, validators=[ricerca_app.validators.validate_image_file_extension, ricerca_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='sitowebcdsexstudenti',
            name='id_sito_web_cds_dati_base',
            field=models.ForeignKey(db_column='ID_SITO_WEB_CDS_DATI_BASE', on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.sitowebcdsdatibase'),
        ),
        migrations.AlterField(
            model_name='sitowebcdsexstudenti',
            name='profilo_it',
            field=models.TextField(blank=True, db_column='PROFILO_IT', null=True),
        ),
        migrations.AlterField(
            model_name='sitowebcdsslider',
            name='dt_mod',
            field=models.DateTimeField(blank=True, db_column='DT_MOD', null=True),
        ),
        migrations.AlterField(
            model_name='sitowebcdsslider',
            name='id_sito_web_cds_dati_base',
            field=models.ForeignKey(blank=True, db_column='ID_SITO_WEB_CDS_DATI_BASE', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.sitowebcdsdatibase'),
        ),
        migrations.AlterField(
            model_name='sitowebcdsslider',
            name='ordine',
            field=models.IntegerField(blank=True, db_column='ORDINE', null=True),
        ),
        migrations.AlterField(
            model_name='sitowebcdsslider',
            name='slider_it',
            field=models.TextField(blank=True, db_column='SLIDER_IT', null=True),
        ),
        migrations.AlterModelTable(
            name='sitowebcdsdatiexceltmpold',
            table='SITO_WEB_CDS_DATI_EXCEL_TMP_OLD',
        ),
    ]
