# Generated by Django 3.2.13 on 2023-04-21 12:40

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0105_auto_20230419_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docenteptaaltridati',
            name='path_foto',
            field=models.FileField(blank=True, db_column='PATH_FOTO', max_length=1000, null=True, upload_to=ricerca_app.models.teacher_photo_media_path, validators=[ricerca_app.validators.validate_image_file_extension, ricerca_app.validators.validate_file_size, ricerca_app.validators.validate_image_size_ratio]),
        ),
    ]
