# Generated by Django 3.2.13 on 2023-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0107_auto_20230424_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentematerialedidattico',
            name='dt_fine_validita',
            field=models.DateTimeField(blank=True, db_column='DT_FINE_VALIDITA', null=True),
        ),
        migrations.AlterField(
            model_name='docentematerialedidattico',
            name='dt_inizio_validita',
            field=models.DateTimeField(blank=True, db_column='DT_INIZIO_VALIDITA', null=True),
        ),
        migrations.AlterField(
            model_name='docentematerialedidattico',
            name='dt_pubblicazione',
            field=models.DateTimeField(blank=True, db_column='DT_PUBBLICAZIONE', null=True),
        ),
        migrations.AlterField(
            model_name='docenteptabacheca',
            name='dt_fine_validita',
            field=models.DateTimeField(blank=True, db_column='DT_FINE_VALIDITA', null=True),
        ),
        migrations.AlterField(
            model_name='docenteptabacheca',
            name='dt_inizio_validita',
            field=models.DateTimeField(blank=True, db_column='DT_INIZIO_VALIDITA', null=True),
        ),
        migrations.AlterField(
            model_name='docenteptabacheca',
            name='dt_pubblicazione',
            field=models.DateTimeField(blank=True, db_column='DT_PUBBLICAZIONE', null=True),
        ),
    ]
