# Generated by Django 3.2.13 on 2023-04-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0108_auto_20230424_1325'),
    ]

    operations = [
        # migrations.RemoveField(
            # model_name='sitowebcdsdatibase',
            # name='durata_en',
        # ),
        # migrations.RemoveField(
            # model_name='sitowebcdsdatibase',
            # name='durata_it',
        # ),
        # migrations.AddField(
            # model_name='sitowebcdsdatibase',
            # name='durata',
            # field=models.CharField(blank=True, db_column='DURATA', max_length=100, null=True),
        # ),
    ]
