# Generated by Django 3.2.13 on 2023-04-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0109_auto_20230426_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docentematerialedidattico',
            options={'managed': True, 'ordering': ('ordine', '-dt_pubblicazione', '-dt_inizio_validita')},
        ),
        migrations.AlterModelOptions(
            name='docenteptabacheca',
            options={'managed': True, 'ordering': ('ordine', '-dt_pubblicazione', '-dt_inizio_validita')},
        ),
    ]
