# Generated by Django 3.2.13 on 2023-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0110_auto_20230426_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettoinventori',
            name='cognomenome_origine',
            field=models.CharField(db_column='COGNOMENOME_ORIGINE', max_length=200),
        ),
    ]
