# Generated by Django 3.2.13 on 2023-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0111_alter_brevettoinventori_cognomenome_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='referente_unical',
            field=models.CharField(db_column='REFERENTE_UNICAL', max_length=1000),
        ),
    ]
