# Generated by Django 3.2.13 on 2023-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0112_alter_spinoffstartupdatibase_referente_unical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progettoresponsabilescientifico',
            name='nome_origine',
            field=models.CharField(db_column='NOME_ORIGINE', max_length=1000),
        ),
        migrations.AlterField(
            model_name='progettoricercatore',
            name='nome_origine',
            field=models.CharField(db_column='NOME_ORIGINE', max_length=1000),
        ),
    ]
