# Generated by Django 3.2.13 on 2023-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0113_auto_20230428_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativaaltridocenti',
            name='cognome_nome_origine',
            field=models.CharField(db_column='COGNOME_NOME_ORIGINE', max_length=200),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativadocente',
            name='cognome_nome_origine',
            field=models.CharField(db_column='COGNOME_NOME_ORIGINE', max_length=200),
        ),
    ]
