# Generated by Django 3.2.13 on 2023-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0114_auto_20230428_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitowebcdsdatibase',
            name='sito_web_cds_status',
            field=models.BooleanField(db_column='SITO_WEB_CDS_STATUS', default=False),
        ),
    ]
