# Generated by Django 3.2.13 on 2023-05-11 15:26

from django.db import migrations, models
import django.db.models.deletion
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0115_auto_20230508_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='descrizione_ita',
            field=models.TextField(db_column='DESCRIZIONE_ITA'),
        ),
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='id_area_tecnologica',
            field=models.ForeignKey(blank=True, db_column='ID_AREA_TECNOLOGICA', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.tipologiaareatecnologica'),
        ),
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='nome_azienda',
            field=models.CharField(db_column='NOME_AZIENDA', max_length=1000),
        ),
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='piva',
            field=models.CharField(db_column='PIVA', max_length=30, unique=True, validators=[ricerca_app.validators.validate_piva]),
        ),
    ]
