# Generated by Django 3.2.13 on 2023-05-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0116_auto_20230511_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='id_area_tecnologica',
            field=models.ForeignKey(db_column='ID_AREA_TECNOLOGICA', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.tipologiaareatecnologica'),
        ),
    ]
