# Generated by Django 3.2.13 on 2023-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0117_auto_20230511_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettodatibase',
            name='breve_descrizione',
            field=models.TextField(db_column='BREVE_DESCRIZIONE'),
        ),
        migrations.AlterField(
            model_name='brevettodatibase',
            name='id_univoco',
            field=models.CharField(db_column='ID_UNIVOCO', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='brevettodatibase',
            name='proprieta',
            field=models.TextField(db_column='PROPRIETA', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='brevettodatibase',
            name='titolo',
            field=models.TextField(db_column='TITOLO'),
        ),
    ]
