# Generated by Django 3.2.13 on 2023-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0118_auto_20230511_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettodatibase',
            name='proprieta',
            field=models.TextField(db_column='PROPRIETA'),
        ),
    ]
