# Generated by Django 3.2.13 on 2023-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0119_auto_20230511_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrevettoTerritori',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('territorio', models.CharField(db_column='TERRITORIO', max_length=80)),
            ],
            options={
                'db_table': 'BREVETTO_TERRITORI',
                'managed': True,
            },
        ),
    ]
