# Generated by Django 3.2.13 on 2023-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0121_auto_20230511_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docenteptabacheca',
            name='titolo',
            field=models.CharField(db_column='TITOLO', max_length=200),
        ),
    ]
