# Generated by Django 3.2.13 on 2023-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0123_auto_20230512_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='avvio',
            field=models.DateTimeField(blank=True, db_column='AVVIO', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='fine',
            field=models.DateTimeField(blank=True, db_column='FINE', null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='modalita_verifica',
            field=models.CharField(blank=True, db_column='MODALITA_VERIFICA', max_length=1000, null=True),
        ),
    ]
