# Generated by Django 3.2.13 on 2023-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0124_auto_20230512_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='avvio',
            field=models.CharField(blank=True, db_column='AVVIO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='didatticadottoratoattivitaformativa',
            name='fine',
            field=models.CharField(blank=True, db_column='FINE', max_length=255, null=True),
        ),
    ]
