# Generated by Django 3.2.13 on 2023-05-22 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricerca_app', '0128_auto_20230522_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitowebcdstopic',
            name='id_user_mod',
            field=models.ForeignKey(blank=True, db_column='ID_USER_MOD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
