# Generated by Django 3.2.13 on 2023-05-25 10:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0130_sitowebcdsarticoliregaltridati_sitowebcdsarticoliregolamento_sitowebcdstopicarticolireg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitowebcdstopicarticolireg',
            name='id_user_mod',
            field=models.IntegerField(blank=True, db_column='ID_USER_MOD', null=True, verbose_name=accounts.models.User),
        ),
    ]
