# Generated by Django 3.2.13 on 2023-05-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0132_alter_sitowebcdsoggettiportalealtridati_id_user_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitowebcdsoggettiportalealtridati',
            name='cds',
        ),
        migrations.AddField(
            model_name='sitowebcdsoggettiportalealtridati',
            name='id_sito_web_cds_articoli_regolamento',
            field=models.ForeignKey(db_column='ID_SITO_WEB_CDS_ARTICOLI_REGOLAMENTO', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.sitowebcdsarticoliregolamento'),
            preserve_default=False,
        ),
    ]
