# Generated by Django 3.2.13 on 2023-06-15 08:23

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0135_auto_20230606_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacdsaltridati',
            name='manifesto_studi',
            field=models.FileField(blank=True, db_column='MANIFESTO_STUDI', max_length=255, null=True, upload_to=ricerca_app.models.cds_manifesto_media_path, validators=[ricerca_app.validators.validate_pdf_file_extension, ricerca_app.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='didatticacdsaltridati',
            name='regolamento_didattico',
            field=models.FileField(blank=True, db_column='REGOLAMENTO_DIDATTICO', max_length=255, null=True, upload_to=ricerca_app.models.cds_regolamento_media_path, validators=[ricerca_app.validators.validate_pdf_file_extension, ricerca_app.validators.validate_file_size]),
        ),
    ]
