# Generated by Django 3.2.13 on 2023-06-20 13:22

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0137_auto_20230620_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brevettodatibase',
            options={'managed': True, 'ordering': ['ordinamento']},
        ),
        migrations.AddField(
            model_name='brevettodatibase',
            name='ordinamento',
            field=models.IntegerField(db_column='ORDINAMENTO', default=10),
        ),
    ]
