# Generated by Django 3.2.13 on 2023-06-20 14:08

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0138_auto_20230620_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinoffstartupdatibase',
            name='is_active',
            field=models.BooleanField(db_column='ATTIVO', default=True),
        ),
        migrations.AlterModelOptions(
            name='spinoffstartupdatibase',
            options={'managed': True, 'ordering': ['ordinamento']},
        ),
        migrations.AddField(
            model_name='spinoffstartupdatibase',
            name='ordinamento',
            field=models.IntegerField(db_column='ORDINAMENTO', default=10),
        ),
    ]
