# Generated by Django 3.2.13 on 2023-06-21 08:11

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0140_auto_20230620_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevettodatibase',
            name='ordinamento',
            field=models.IntegerField(db_column='ORDINE', default=10),
        ),
        migrations.AlterField(
            model_name='progettodatibase',
            name='ordinamento',
            field=models.IntegerField(db_column='ORDINE', default=10),
        ),
        migrations.AlterField(
            model_name='spinoffstartupdatibase',
            name='ordinamento',
            field=models.IntegerField(db_column='ORDINE', default=10),
        ),
    ]
