# Generated by Django 3.2.13 on 2023-06-26 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricerca_app', '0142_auto_20230626_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaCdsGruppi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_breve_it', models.CharField(db_column='DESCR_BREVE_IT', max_length=1000)),
                ('descr_breve_en', models.CharField(blank=True, db_column='DESCR_BREVE_EN', max_length=1000, null=True)),
                ('descr_lunga_it', models.TextField(blank=True, db_column='DESCR_LUNGA_IT', null=True)),
                ('descr_lunga_en', models.TextField(blank=True, db_column='DESCR_LUNGA_EN', null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE', default=10)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=True)),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
                ('id_didattica_cds', models.ForeignKey(db_column='ID_DIDATTICA_CDS', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticacds')),
                ('id_user_mod', models.ForeignKey(db_column='ID_USER_MOD', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DIDATTICA_CDS_GRUPPI',
                'ordering': ('ordine',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DidatticaCdsGruppiComponenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cognome', models.CharField(blank=True, db_column='COGNOME', max_length=100, null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('funzione_it', models.CharField(blank=True, db_column='FUNZIONE_IT', max_length=1000, null=True)),
                ('funzione_en', models.CharField(blank=True, db_column='FUNZIONE_EN', max_length=1000, null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE', default=10)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=True)),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
                ('id_didattica_cds_gruppi', models.ForeignKey(db_column='ID_DIDATTICA_CDS_GRUPPI', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticacdsgruppi')),
                ('id_user_mod', models.ForeignKey(db_column='ID_USER_MOD', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('matricola', models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola')),
            ],
            options={
                'db_table': 'DIDATTICA_CDS_GRUPPI_COMPONENTI',
                'ordering': ('ordine',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDipartimentoGruppi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_breve_it', models.CharField(db_column='DESCR_BREVE_IT', max_length=1000)),
                ('descr_breve_en', models.CharField(blank=True, db_column='DESCR_BREVE_EN', max_length=1000, null=True)),
                ('descr_lunga_it', models.TextField(blank=True, db_column='DESCR_LUNGA_IT', null=True)),
                ('descr_lunga_en', models.TextField(blank=True, db_column='DESCR_LUNGA_EN', null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE', default=10)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=True)),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
                ('id_didattica_dipartimento', models.ForeignKey(db_column='ID_DIDATTICA_DIPARTIMENTO', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticadipartimento')),
                ('id_user_mod', models.ForeignKey(db_column='ID_USER_MOD', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO_GRUPPI',
                'ordering': ('ordine',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DidatticaDipartimentoGruppiComponenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cognome', models.CharField(blank=True, db_column='COGNOME', max_length=100, null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('funzione_it', models.CharField(blank=True, db_column='FUNZIONE_IT', max_length=1000, null=True)),
                ('funzione_en', models.CharField(blank=True, db_column='FUNZIONE_EN', max_length=1000, null=True)),
                ('ordine', models.IntegerField(db_column='ORDINE', default=10)),
                ('visibile', models.BooleanField(db_column='VISIBILE', default=True)),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
                ('id_didattica_dipartimento_gruppi', models.ForeignKey(db_column='ID_DIDATTICA_DIPARTIMENTO_GRUPPI', on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.didatticadipartimentogruppi')),
                ('id_user_mod', models.ForeignKey(db_column='ID_USER_MOD', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('matricola', models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ricerca_app.personale', to_field='matricola')),
            ],
            options={
                'db_table': 'DIDATTICA_DIPARTIMENTO_GRUPPI_COMPONENTI',
                'ordering': ('ordine',),
                'managed': True,
            },
        ),
    ]
