# Generated by Django 3.2.13 on 2023-06-28 08:22

from django.db import migrations, models
import ricerca_app.models
import ricerca_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0144_auto_20230626_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='didatticacdsaltridati',
            name='visibile',
            field=models.BooleanField(db_column='VISIBILE', default=False),
        ),
    ]
