# Generated by Django 3.2.13 on 2023-07-12 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricerca_app', '0145_didatticaambiti_didatticapianoregolamento_didatticapianosceltaaf_didatticapianosceltafiland_didattic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didatticacdsgruppicomponenti',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='didatticadipartimentogruppicomponenti',
            name='matricola',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricerca_app.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='sitowebcdstopicarticolireg',
            name='id_user_mod',
            field=models.ForeignKey(blank=True, db_column='ID_USER_MOD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SitoWebCdsTopicArticoliRegAltriDati',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ordine', models.PositiveIntegerField(db_column='ORDINE')),
                ('id_sito_web_cds_tipo_dato', models.IntegerField(db_column='ID_SITO_WEB_CDS_TIPO_DATO')),
                ('titolo_en', models.CharField(blank=True, db_column='TITOLO_EN', max_length=1000, null=True)),
                ('titolo_it', models.CharField(blank=True, db_column='TITOLO_IT', max_length=1000, null=True)),
                ('testo_it', models.TextField(db_column='TESTO_IT')),
                ('testo_en', models.TextField(blank=True, db_column='TESTO_EN', null=True)),
                ('visibile', models.IntegerField(db_column='VISIBILE')),
                ('dt_mod', models.DateField(db_column='DT_MOD')),
                ('id_sito_web_cds_topic_articoli_reg', models.ForeignKey(db_column='ID_SITO_WEB_CDS_TOPIC_ARTICOLI_REG', on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.sitowebcdstopicarticolireg')),
                ('id_user_mod', models.ForeignKey(blank=True, db_column='ID_USER_MOD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SITO_WEB_CDS_TOPIC_ARTICOLI_REG_ALTRI_DATI',
                'managed': True,
            },
        ),
    ]
