# Generated by Django 3.2.13 on 2023-07-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0146_auto_20230712_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitoWebCdsTipoDato',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_breve', models.CharField(db_column='DESCR_BREVE', max_length=100)),
                ('descr_lunga', models.CharField(blank=True, db_column='DESCR_LUNGA', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'SITO_WEB_CDS_TIPO_DATO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sitowebcdstopicarticoliregaltridati',
            name='link',
            field=models.CharField(blank=True, db_column='LINK', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sitowebcdstopicarticoliregaltridati',
            name='id_sito_web_cds_tipo_dato',
            field=models.ForeignKey(db_column='ID_SITO_WEB_CDS_TIPO_DATO', on_delete=django.db.models.deletion.PROTECT, to='ricerca_app.sitowebcdstipodato'),
        ),
    ]
