# Generated by Django 3.2.20 on 2023-10-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0149_alter_laboratoriodatibase_nome_file_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaRischio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descr_tipologia', models.CharField(db_column='DESCR_TIPOLOGIA', max_length=1000)),
            ],
            options={
                'db_table': 'TIPOLOGIA_RISCHIO',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='laboratoriopersonaletecnico',
            name='field_impegno',
        ),
        migrations.RemoveField(
            model_name='laboratoriotipologiarischio',
            name='tipologia_rischio',
        ),
        migrations.AddField(
            model_name='laboratorioattivita',
            name='descr_finalita_en',
            field=models.TextField(blank=False, db_column='DESCR_FINALITA_EN', null=True),
        ),
        migrations.AddField(
            model_name='laboratorioattivita',
            name='descr_finalita_it',
            field=models.TextField(blank=False, db_column='DESCR_FINALITA_IT', null=True),
        ),
        migrations.AddField(
            model_name='laboratoriodatibase',
            name='tipologia_attivita',
            field=models.ManyToManyField(through='ricerca_app.LaboratorioAttivita', to='ricerca_app.LaboratorioTipologiaAttivita'),
        ),
        migrations.AddField(
            model_name='laboratoriopersonaletecnico',
            name='percentuale_impegno',
            field=models.FloatField(blank=True, db_column='PERCENTUALE_IMPEGNO', null=True),
        ),
        migrations.AddField(
            model_name='laboratoriotipologiarischio',
            name='tipologia_rischio_origine',
            field=models.CharField(blank=True, db_column='TIPOLOGIA_RISCHIO_ORIGINE', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioaltridipartimenti',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioattivita',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        # migrations.AlterField(
            # model_name='laboratorioattivita',
            # name='id_tipologia_attivita',
            # field=models.ForeignKey(db_column='ID_TIPOLOGIA_ATTIVITA', null=True, on_delete=django.db.models.deletion.PROTECT, to='ricerca_app.laboratoriotipologiaattivita'),
        # ),
        migrations.AlterField(
            model_name='laboratorioattrezzature',
            name='costo_unitario',
            field=models.FloatField(db_column='COSTO_UNITARIO', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioattrezzature',
            name='descrizione',
            field=models.TextField(db_column='DESCRIZIONE', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioattrezzature',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioattrezzature',
            name='quantita',
            field=models.IntegerField(db_column='QUANTITA', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioattrezzature',
            name='tipologia',
            field=models.CharField(db_column='TIPOLOGIA', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoriodatierc1',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratoriopersonalericerca',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratoriopersonaletecnico',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='anno',
            field=models.IntegerField(db_column='ANNO', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='committenti',
            field=models.CharField(db_column='COMMITTENTI', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='descrizione',
            field=models.TextField(db_column='DESCRIZIONE', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='durata_mesi',
            field=models.IntegerField(db_column='DURATA_MESI', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='importo_euro',
            field=models.FloatField(db_column='IMPORTO_EURO', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioserviziofferti',
            name='descrizione_servizio',
            field=models.TextField(db_column='DESCRIZIONE_SERVIZIO', null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioserviziofferti',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioserviziofferti',
            name='nome_servizio',
            field=models.TextField(db_column='NOME_SERVIZIO', null=True),
        ),
        migrations.AlterField(
            model_name='laboratoriotipologiarischio',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioubicazione',
            name='edificio',
            field=models.CharField(db_column='EDIFICIO', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioubicazione',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioubicazione',
            name='piano',
            field=models.CharField(db_column='PIANO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorioubicazione',
            name='sede_principale',
            field=models.CharField(db_column='SEDE_PRINCIPALE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='laboratoriodatibase',
            name='tipologia_rischio',
            field=models.ManyToManyField(through='ricerca_app.LaboratorioTipologiaRischio', to='ricerca_app.TipologiaRischio'),
        ),
        migrations.AddField(
            model_name='laboratoriotipologiarischio',
            name='id_tipologia_rischio',
            field=models.ForeignKey(blank=True, db_column='ID_TIPOLOGIA_RISCHIO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.tipologiarischio'),
        ),
    ]
