# Generated by Django 3.2.20 on 2023-09-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0150_alter_laboratoriodatibase_nome_file_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorioaltridipartimenti',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioattivita',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioattrezzature',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratoriodatierc1',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratoriopersonalericerca',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratoriopersonaletecnico',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioservizierogati',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioserviziofferti',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratoriotipologiarischio',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
        migrations.AlterField(
            model_name='laboratorioubicazione',
            name='id_laboratorio_dati',
            field=models.ForeignKey(blank=True, db_column='ID_LABORATORIO_DATI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriodatibase'),
        ),
    ]
