# Generated by Django 3.2.20 on 2023-10-12 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricerca_app', '0150_auto_20231011_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoriodatibase',
            name='dt_mod',
            field=models.DateField(blank=True, db_column='DT_MOD', null=True),
        ),
        migrations.AddField(
            model_name='laboratoriodatibase',
            name='user_mod_id',
            field=models.ForeignKey(blank=True, db_column='user_mod_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratoriodatibase',
            name='visibile',
            field=models.BooleanField(db_column='VISIBILE', default=False),
        ),
    ]
