# Generated by Django 3.2.20 on 2023-10-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricerca_app', '0151_auto_20231012_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioFondo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_fondo', models.CharField(db_column='NOME_FONDO', max_length=500)),
            ],
            options={
                'db_table': 'LABORATORIO_FONDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioAttrezzatureRischi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('id_laboratorio_attrezzature', models.ForeignKey(blank=True, db_column='ID_LABORATORIO_ATTREZZATURE', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratorioattrezzature')),
                ('id_tipologia_rischio', models.ForeignKey(blank=True, db_column='ID_TIPOLOGIA_RISCHIO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.tipologiarischio')),
                ('user_mod_id', models.ForeignKey(blank=True, db_column='user_mod_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LABORATORIO_ATTREZZATURE_RISCHI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioAttrezzatureFondi',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('id_laboratorio_attrezzature', models.ForeignKey(blank=True, db_column='ID_LABORATORIO_ATTREZZATURE', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratorioattrezzature')),
                ('id_laboratorio_fondo', models.ForeignKey(blank=True, db_column='ID_LABORATORIO_FONDO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ricerca_app.laboratoriofondo')),
                ('user_mod_id', models.ForeignKey(blank=True, db_column='user_mod_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LABORATORIO_ATTREZZATURE_FONDI',
                'managed': True,
            },
        ),
    ]
