# Generated by Django 4.2.5 on 2023-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0152_laboratorioattrezzaturefondi_laboratorioattrezzaturerischi_laboratoriofondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaCdsPeriodi',
            fields=[
                ('ciclo_id', models.IntegerField(db_column='CICLO_ID', primary_key=True, serialize=False)),
                ('aa_id', models.IntegerField(db_column='AA_ID')),
                ('cds_id', models.IntegerField(db_column='CDS_ID')),
                ('cds_cod', models.CharField(db_column='CDS_COD', max_length=10)),
                ('rag_tipi_ciclo_cod', models.CharField(db_column='RAG_TIPI_CICLO_COD', max_length=5)),
                ('rag_tipi_ciclo_des', models.CharField(blank=True, db_column='RAG_TIPI_CICLO_DES', max_length=40, null=True)),
                ('tipo_ciclo_cod', models.CharField(db_column='TIPO_CICLO_COD', max_length=5)),
                ('tipo_ciclo_des', models.CharField(db_column='TIPO_CICLO_DES', max_length=40)),
                ('tipo_ciclo_des_eng', models.CharField(blank=True, db_column='TIPO_CICLO_DES_ENG', max_length=4000, null=True)),
                ('org_did_sua_cod', models.IntegerField(blank=True, db_column='ORG_DID_SUA_COD', null=True)),
                ('ciclo_des', models.CharField(db_column='CICLO_DES', max_length=40)),
                ('data_inizio', models.DateField(db_column='DATA_INIZIO')),
                ('data_fine', models.DateField(db_column='DATA_FINE')),
                ('durata', models.DecimalField(blank=True, db_column='DURATA', decimal_places=2, max_digits=6, null=True)),
                ('csa_cod', models.CharField(blank=True, db_column='CSA_COD', max_length=2, null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_CDS_PERIODI',
                'managed': True,
            },
        ),
    ]
