# Generated by Django 4.2.6 on 2023-11-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0153_didatticacdsperiodi'),
    ]

    operations = []
