# Generated by Django 4.2.6 on 2023-11-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricerca_app', '0153_didatticacdsperiodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaSsd',
            fields=[
                ('ssd_id', models.CharField(db_column='SSD_ID', max_length=100, primary_key=True, serialize=False)),
                ('ssd_des', models.CharField(db_column='SSD_DES', max_length=2000)),
            ],
            options={
                'db_table': 'DIDATTICA_SSD',
                'managed': True,
            },
        ),
    ]
