# Generated by Django 4.2.7 on 2023-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ricerca_app", "0154_didatticassd_delete_didatticacdsperiodi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DidatticaAttivitaFormativaEsse3",
            fields=[
                (
                    "ad_id_esse3",
                    models.IntegerField(
                        db_column="AD_ID_ESSE3", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ad_cod",
                    models.CharField(
                        blank=True, db_column="AD_COD", max_length=10, null=True
                    ),
                ),
                (
                    "ad_des",
                    models.CharField(
                        blank=True, db_column="AD_DES", max_length=255, null=True
                    ),
                ),
                (
                    "tipo_entita",
                    models.IntegerField(blank=True, db_column="TIPO_ENTITA", null=True),
                ),
                ("peso", models.FloatField(blank=True, db_column="PESO", null=True)),
                (
                    "data_ins",
                    models.DateTimeField(blank=True, db_column="DATA_INS", null=True),
                ),
                (
                    "data_mod",
                    models.DateTimeField(blank=True, db_column="DATA_MOD", null=True),
                ),
            ],
            options={
                "db_table": "DIDATTICA_ATTIVITA_FORMATIVA_ESSE3",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsEsse3",
            fields=[
                (
                    "dip_id_esse3",
                    models.IntegerField(
                        blank=True, db_column="DIP_ID_ESSE3", null=True
                    ),
                ),
                (
                    "dip_cod",
                    models.CharField(
                        blank=True, db_column="DIP_COD", max_length=6, null=True
                    ),
                ),
                (
                    "cds_id_esse3",
                    models.IntegerField(
                        db_column="CDS_ID_ESSE3", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cds_cod",
                    models.CharField(
                        blank=True, db_column="CDS_COD", max_length=10, null=True
                    ),
                ),
                (
                    "nome_cds_it",
                    models.CharField(
                        blank=True, db_column="NOME_CDS_IT", max_length=255, null=True
                    ),
                ),
                (
                    "rif_cod",
                    models.CharField(
                        blank=True, db_column="RIF_COD", max_length=10, null=True
                    ),
                ),
                (
                    "rif_des",
                    models.CharField(
                        blank=True, db_column="RIF_DES", max_length=255, null=True
                    ),
                ),
                (
                    "tipo_corso_cod",
                    models.CharField(
                        blank=True, db_column="TIPO_CORSO_COD", max_length=10, null=True
                    ),
                ),
                (
                    "tipo_corso_des",
                    models.CharField(
                        blank=True, db_column="TIPO_CORSO_DES", max_length=80, null=True
                    ),
                ),
                (
                    "durata_anni",
                    models.IntegerField(blank=True, db_column="DURATA_ANNI", null=True),
                ),
                (
                    "valore_min",
                    models.IntegerField(blank=True, db_column="VALORE_MIN", null=True),
                ),
                (
                    "tipo_titit_cod",
                    models.CharField(
                        blank=True, db_column="TIPO_TITIT_COD", max_length=10, null=True
                    ),
                ),
                (
                    "tipo_titit_des",
                    models.CharField(
                        blank=True,
                        db_column="TIPO_TITIT_DES",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tipo_spec_cod",
                    models.CharField(
                        blank=True, db_column="TIPO_SPEC_COD", max_length=10, null=True
                    ),
                ),
                (
                    "tipo_spec_des",
                    models.CharField(
                        blank=True, db_column="TIPO_SPEC_DES", max_length=255, null=True
                    ),
                ),
                (
                    "istat_cod",
                    models.CharField(
                        blank=True, db_column="ISTAT_COD", max_length=10, null=True
                    ),
                ),
                (
                    "max_punti",
                    models.IntegerField(blank=True, db_column="MAX_PUNTI", null=True),
                ),
                (
                    "um_peso_cod",
                    models.CharField(
                        blank=True, db_column="UM_PESO_COD", max_length=5, null=True
                    ),
                ),
                (
                    "um_peso_des",
                    models.CharField(
                        blank=True, db_column="UM_PESO_DES", max_length=40, null=True
                    ),
                ),
                (
                    "aa_att_id",
                    models.IntegerField(blank=True, db_column="AA_ATT_ID", null=True),
                ),
                (
                    "aa_dis_id",
                    models.IntegerField(blank=True, db_column="AA_DIS_ID", null=True),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, db_column="URL", max_length=2000, null=True
                    ),
                ),
                (
                    "cds_url_info_web",
                    models.CharField(
                        blank=True,
                        db_column="CDS_URL_INFO_WEB",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "cds_vis_web_flg",
                    models.IntegerField(
                        blank=True, db_column="CDS_VIS_WEB_FLG", null=True
                    ),
                ),
                (
                    "cdsord_id_esse3",
                    models.IntegerField(
                        blank=True, db_column="CDSORD_ID_ESSE3", null=True
                    ),
                ),
                (
                    "cdsord_cod",
                    models.CharField(
                        blank=True, db_column="CDSORD_COD", max_length=10, null=True
                    ),
                ),
                (
                    "aa_ord_id",
                    models.IntegerField(blank=True, db_column="AA_ORD_ID", null=True),
                ),
                (
                    "cdsord_des",
                    models.CharField(
                        blank=True, db_column="CDSORD_DES", max_length=255, null=True
                    ),
                ),
                (
                    "stato_cdsord_cod",
                    models.CharField(
                        blank=True,
                        db_column="STATO_CDSORD_COD",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "dt_ins",
                    models.DateTimeField(blank=True, db_column="DT_INS", null=True),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_ESSE3",
                "managed": True,
            },
        ),
    ]
