# Generated by Django 4.2.7 on 2024-02-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ricerca_app", "0155_didatticaattivitaformativaesse3_didatticacdsesse3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="didatticacdsaltridatiufficio",
            options={"managed": True, "ordering": ("ordine",)},
        ),
    ]
