# Generated by Django 4.2.10 on 2024-03-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ricerca_app", "0157_didatticaregolamentoaltridati_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DidatticaDottoratoAttivitaFormativaTipologia",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("nome_it", models.CharField(db_column="NOME_IT", max_length=255)),
                (
                    "nome_en",
                    models.CharField(
                        blank=True, db_column="NOME_EN", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_DOTTORATO_ATTIVITA_FORMATIVA_TIPOLOGIA",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="didatticadottoratoattivitaformativa",
            name="tipologia",
            field=models.ForeignKey(
                db_column="TIPOLOGIA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ricerca_app.didatticadottoratoattivitaformativatipologia",
            ),
        ),
    ]
