# Generated by Django 4.2.10 on 2024-05-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ricerca_app", "0158_didatticadottoratoattivitaformativatipologia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoStatus",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "status_cod",
                    models.CharField(db_column="STATUS_COD", max_length=100),
                ),
                (
                    "status_desc",
                    models.TextField(blank=True, db_column="STATUS_DESC", null=True),
                ),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_STATUS",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoStruttura",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("aa", models.IntegerField(db_column="AA")),
                ("numero", models.PositiveIntegerField(db_column="NUMERO")),
                ("titolo_it", models.CharField(db_column="TITOLO_IT", max_length=2000)),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, db_column="TITOLO_EN", max_length=2000, null=True
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(blank=True, db_column="ORDINE", null=True),
                ),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_STRUTTURA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsArticoliRegolamento",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("testo_it", models.TextField(db_column="TESTO_IT")),
                (
                    "testo_en",
                    models.TextField(blank=True, db_column="TESTO_EN", null=True),
                ),
                ("note", models.TextField(blank=True, db_column="NOTE", null=True)),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "id_didattica_articoli_regolamento_struttura",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_ARTICOLI_REGOLAMENTO_STRUTTURA",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ricerca_app.didatticaarticoliregolamentostruttura",
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_ARTICOLI_REGOLAMENTO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsArticoliRegolamentoTestata",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("aa", models.IntegerField(db_column="AA")),
                ("note", models.TextField(blank=True, db_column="NOTE")),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "cds",
                    models.ForeignKey(
                        db_column="CDS_ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ricerca_app.didatticacds",
                    ),
                ),
                (
                    "id_user_mod",
                    models.ForeignKey(
                        db_column="ID_USER_MOD",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_ARTICOLI_REGOLAMENTO_TESTATA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsTipoCorso",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "tipo_corso_cod",
                    models.CharField(
                        blank=True, db_column="TIPO_CORSO_COD", max_length=10, null=True
                    ),
                ),
                (
                    "tipo_corso_des",
                    models.CharField(
                        blank=True, db_column="TIPO_CORSO_DES", max_length=80, null=True
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, db_column="NOTE", max_length=400, null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id_user_mod",
                    models.ForeignKey(
                        db_column="ID_USER_MOD",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_TIPO_CORSO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsTestataStatus",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "motivazione",
                    models.TextField(blank=True, db_column="MOTIVAZIONE", null=True),
                ),
                ("data_status", models.DateTimeField(db_column="DATA_STATUS")),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id_didattica_articoli_regolamento_status",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_ARTICOLI_REGOLAMENTO_STATUS",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ricerca_app.didatticaarticoliregolamentostatus",
                    ),
                ),
                (
                    "id_didattica_cds_articoli_regolamento_testata",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO_TESTATA",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ricerca_app.didatticacdsarticoliregolamentotestata",
                    ),
                ),
                (
                    "id_user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_user_mod",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_TESTATA_STATUS",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsSubArticoliRegolamento",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("ordine", models.PositiveIntegerField(db_column="ORDINE")),
                ("titolo_it", models.CharField(db_column="TITOLO_IT", max_length=1000)),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, db_column="TITOLO_EN", max_length=1000, null=True
                    ),
                ),
                ("testo_it", models.TextField(db_column="TESTO_IT")),
                (
                    "testo_en",
                    models.TextField(blank=True, db_column="TESTO_EN", null=True),
                ),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "id_didattica_cds_articoli_regolamento",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ricerca_app.didatticacdsarticoliregolamento",
                    ),
                ),
                (
                    "id_user_mod",
                    models.ForeignKey(
                        db_column="ID_USER_MOD",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_SUB_ARTICOLI_REGOLAMENTO",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="didatticacdsarticoliregolamento",
            name="id_didattica_cds_articoli_regolamento_testata",
            field=models.ForeignKey(
                db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO_TESTATA",
                on_delete=django.db.models.deletion.PROTECT,
                to="ricerca_app.didatticacdsarticoliregolamentotestata",
            ),
        ),
        migrations.AddField(
            model_name="didatticacdsarticoliregolamento",
            name="id_user_mod",
            field=models.ForeignKey(
                db_column="ID_USER_MOD",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoTitolo",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_titolo_it",
                    models.CharField(db_column="DESCR_TITOLO_IT", max_length=1000),
                ),
                (
                    "descr_titolo_en",
                    models.CharField(
                        blank=True,
                        db_column="DESCR_TITOLO_EN",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("ordine", models.IntegerField(db_column="ORDINE")),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id_user_mod",
                    models.ForeignKey(
                        db_column="ID_USER_MOD",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_TITOLO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoStrutturaTopic",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "ordine",
                    models.IntegerField(blank=True, db_column="ORDINE", null=True),
                ),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "id_did_art_regolamento_struttura",
                    models.ForeignKey(
                        db_column="ID_DID_ART_REGOLAMENTO_STRUTTURA",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ricerca_app.didatticaarticoliregolamentostruttura",
                    ),
                ),
                (
                    "id_sito_web_cds_topic",
                    models.ForeignKey(
                        db_column="ID_SITO_WEB_CDS_TOPIC",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ricerca_app.sitowebcdstopic",
                    ),
                ),
                (
                    "id_user_mod",
                    models.ForeignKey(
                        db_column="ID_USER_MOD",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_STRUTTURA_TOPIC",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="didatticaarticoliregolamentostruttura",
            name="id_didattica_articoli_regolamento_titolo",
            field=models.ForeignKey(
                db_column="ID_DIDATTICA_ARTICOLI_REGOLAMENTO_TITOLO",
                on_delete=django.db.models.deletion.PROTECT,
                to="ricerca_app.didatticaarticoliregolamentotitolo",
            ),
        ),
        migrations.AddField(
            model_name="didatticaarticoliregolamentostruttura",
            name="id_didattica_cds_tipo_corso",
            field=models.ForeignKey(
                db_column="ID_DIDATTICA_CDS_TIPO_CORSO",
                on_delete=django.db.models.deletion.PROTECT,
                to="ricerca_app.didatticacdstipocorso",
            ),
        ),
        migrations.AddField(
            model_name="didatticaarticoliregolamentostruttura",
            name="id_user_mod",
            field=models.ForeignKey(
                db_column="ID_USER_MOD",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
