# Generated by Django 4.2.13 on 2024-06-18 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ricerca_app", "0159_didatticaarticoliregolamentostatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitoWebArticoliRegolamentoStrutturaTopic",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("titolo_it", models.TextField(db_column="TITOLO_IT")),
                (
                    "titolo_en",
                    models.TextField(blank=True, db_column="TITOLO_EN", null=True),
                ),
                (
                    "ordine",
                    models.IntegerField(blank=True, db_column="ORDINE", null=True),
                ),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "id_did_art_regolamento_struttura",
                    models.ForeignKey(
                        db_column="ID_DID_ART_REGOLAMENTO_STRUTTURA",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ricerca_app.didatticaarticoliregolamentostruttura",
                    ),
                ),
            ],
            options={
                "db_table": "SITO_WEB_ARTICOLI_REGOLAMENTO_STRUTTURA_TOPIC",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SitoWebCdsSubArticoliRegolamento",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("titolo_it", models.CharField(db_column="TITOLO_IT", max_length=1000)),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, db_column="TITOLO_EN", max_length=1000, null=True
                    ),
                ),
                ("testo_it", models.TextField(db_column="TESTO_IT")),
                (
                    "testo_en",
                    models.TextField(blank=True, db_column="TESTO_EN", null=True),
                ),
                ("ordine", models.IntegerField(db_column="ORDINE")),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
            ],
            options={
                "db_table": "SITO_WEB_CDS_SUB_ARTICOLI_REGOLAMENTO",
                "managed": True,
            },
        ),
        migrations.AlterUniqueTogether(
            name="sitowebcdstopicarticolireg",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sitowebcdstopic",
            name="tag",
            field=models.CharField(
                blank=True, db_column="TAG", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitowebcdstopicarticolireg",
            name="id_didattica_cds_articoli_regolamento",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ricerca_app.didatticacdsarticoliregolamento",
            ),
        ),
        migrations.AddField(
            model_name="sitowebcdstopicarticolireg",
            name="testo_en",
            field=models.TextField(blank=True, db_column="TESTO_EN", null=True),
        ),
        migrations.AddField(
            model_name="sitowebcdstopicarticolireg",
            name="testo_it",
            field=models.TextField(blank=True, db_column="TESTO_IT", null=True),
        ),
        migrations.AlterField(
            model_name="sitowebcdstopicarticolireg",
            name="dt_mod",
            field=models.DateTimeField(db_column="DT_MOD"),
        ),
        migrations.AlterField(
            model_name="sitowebcdstopicarticolireg",
            name="id_sito_web_cds_oggetti_portale",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_SITO_WEB_CDS_OGGETTI_PORTALE",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ricerca_app.sitowebcdsoggettiportale",
            ),
        ),
        migrations.AlterField(
            model_name="sitowebcdstopicarticolireg",
            name="titolo_it",
            field=models.CharField(
                blank=True, db_column="TITOLO_IT", max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitowebcdstopicarticolireg",
            name="visibile",
            field=models.BooleanField(db_column="VISIBILE", default=False),
        ),
        migrations.AlterUniqueTogether(
            name="sitowebcdstopicarticolireg",
            unique_together={
                ("id_sito_web_cds_topic", "id_didattica_cds_articoli_regolamento")
            },
        ),
        migrations.DeleteModel(
            name="DidatticaArticoliRegolamentoStrutturaTopic",
        ),
        migrations.AddField(
            model_name="sitowebcdssubarticoliregolamento",
            name="id_sito_web_cds_topic_articoli_reg",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_SITO_WEB_CDS_TOPIC_ARTICOLI_REG",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ricerca_app.sitowebcdstopicarticolireg",
            ),
        ),
        migrations.AddField(
            model_name="sitowebcdssubarticoliregolamento",
            name="id_user_mod",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_USER_MOD",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitowebarticoliregolamentostrutturatopic",
            name="id_sito_web_cds_topic",
            field=models.ForeignKey(
                db_column="ID_SITO_WEB_CDS_TOPIC",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ricerca_app.sitowebcdstopic",
            ),
        ),
        migrations.AddField(
            model_name="sitowebarticoliregolamentostrutturatopic",
            name="id_user_mod",
            field=models.ForeignKey(
                db_column="ID_USER_MOD",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="sitowebcdstopicarticolireg",
            name="id_sito_web_cds_articoli_regolamento",
        ),
    ]
