# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoStatus",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "status_cod",
                    models.CharField(db_column="STATUS_COD", max_length=100),
                ),
                (
                    "status_desc",
                    models.TextField(blank=True, db_column="STATUS_DESC", null=True),
                ),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_STATUS",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoStruttura",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("aa", models.IntegerField(db_column="AA")),
                ("numero", models.PositiveIntegerField(db_column="NUMERO")),
                ("titolo_it", models.CharField(db_column="TITOLO_IT", max_length=2000)),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, db_column="TITOLO_EN", max_length=2000, null=True
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(blank=True, db_column="ORDINE", null=True),
                ),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_STRUTTURA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsArticoliRegolamento",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("testo_it", models.TextField(db_column="TESTO_IT")),
                (
                    "testo_en",
                    models.TextField(blank=True, db_column="TESTO_EN", null=True),
                ),
                ("note", models.TextField(blank=True, db_column="NOTE", null=True)),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "didattica_articoli_regolamento_struttura",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_ARTICOLI_REGOLAMENTO_STRUTTURA",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="regdid.didatticaarticoliregolamentostruttura",
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_ARTICOLI_REGOLAMENTO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsArticoliRegolamentoTestata",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("aa", models.IntegerField(db_column="AA")),
                ("note", models.TextField(blank=True, db_column="NOTE")),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "cds",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_CDS",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cds.didatticacds",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        db_column="user_mod_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_ARTICOLI_REGOLAMENTO_TESTATA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsTestataStatus",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "motivazione",
                    models.TextField(blank=True, db_column="MOTIVAZIONE", null=True),
                ),
                ("data_status", models.DateTimeField(db_column="DATA_STATUS")),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "didattica_articoli_regolamento_status",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_ARTICOLI_REGOLAMENTO_STATUS",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="regdid.didatticaarticoliregolamentostatus",
                    ),
                ),
                (
                    "didattica_cds_articoli_regolamento_testata",
                    models.ForeignKey(
                        db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO_TESTATA",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="regdid.didatticacdsarticoliregolamentotestata",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_TESTATA_STATUS",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DidatticaCdsSubArticoliRegolamento",
            fields=[
                ("visibile", models.BooleanField(db_column="VISIBILE", default=False)),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("ordine", models.PositiveIntegerField(db_column="ORDINE")),
                ("titolo_it", models.CharField(db_column="TITOLO_IT", max_length=1000)),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, db_column="TITOLO_EN", max_length=1000, null=True
                    ),
                ),
                ("testo_it", models.TextField(db_column="TESTO_IT")),
                (
                    "testo_en",
                    models.TextField(blank=True, db_column="TESTO_EN", null=True),
                ),
                ("dt_mod", models.DateTimeField(db_column="DT_MOD")),
                (
                    "didattica_cds_articoli_regolamento",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regdid.didatticacdsarticoliregolamento",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        db_column="user_mod_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_CDS_SUB_ARTICOLI_REGOLAMENTO",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="didatticacdsarticoliregolamento",
            name="didattica_cds_articoli_regolamento_testata",
            field=models.ForeignKey(
                db_column="ID_DIDATTICA_CDS_ARTICOLI_REGOLAMENTO_TESTATA",
                on_delete=django.db.models.deletion.PROTECT,
                to="regdid.didatticacdsarticoliregolamentotestata",
            ),
        ),
        migrations.AddField(
            model_name="didatticacdsarticoliregolamento",
            name="user_mod",
            field=models.ForeignKey(
                db_column="user_mod_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DidatticaArticoliRegolamentoTitolo",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_titolo_it",
                    models.CharField(db_column="DESCR_TITOLO_IT", max_length=1000),
                ),
                (
                    "descr_titolo_en",
                    models.CharField(
                        blank=True,
                        db_column="DESCR_TITOLO_EN",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("ordine", models.IntegerField(db_column="ORDINE")),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        db_column="user_mod_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "DIDATTICA_ARTICOLI_REGOLAMENTO_TITOLO",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="didatticaarticoliregolamentostruttura",
            name="didattica_articoli_regolamento_titolo",
            field=models.ForeignKey(
                db_column="ID_DIDATTICA_ARTICOLI_REGOLAMENTO_TITOLO",
                on_delete=django.db.models.deletion.PROTECT,
                to="regdid.didatticaarticoliregolamentotitolo",
            ),
        ),
        migrations.AddField(
            model_name="didatticaarticoliregolamentostruttura",
            name="didattica_cds_tipo_corso",
            field=models.ForeignKey(
                db_column="ID_DIDATTICA_CDS_TIPO_CORSO",
                on_delete=django.db.models.deletion.PROTECT,
                to="cds.didatticacdstipocorso",
            ),
        ),
        migrations.AddField(
            model_name="didatticaarticoliregolamentostruttura",
            name="user_mod",
            field=models.ForeignKey(
                db_column="user_mod_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="didatticacdsarticoliregolamentotestata",
            unique_together={("cds", "aa")},
        ),
        migrations.AlterUniqueTogether(
            name="didatticaarticoliregolamentostruttura",
            unique_together={("aa", "numero", "didattica_cds_tipo_corso")},
        ),
        migrations.AlterUniqueTogether(
            name="didatticacdsarticoliregolamento",
            unique_together={
                (
                    "didattica_cds_articoli_regolamento_testata",
                    "didattica_articoli_regolamento_struttura",
                )
            },
        ),
    ]
