# Generated by Django 4.2.20 on 2026-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RicercaDocenteGruppo',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dt_inizio', models.DateField(blank=True, db_column='DT_INIZIO', null=True)),
                ('dt_fine', models.DateField(blank=True, db_column='DT_FINE', null=True)),
            ],
            options={
                'db_table': 'RICERCA_DOCENTE_GRUPPO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RicercaGruppo',
            fields=[
                ('dt_ins', models.DateTimeField(auto_now_add=True, db_column='DT_INS')),
                ('dt_mod', models.DateTimeField(auto_now=True, db_column='DT_MOD', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=200)),
                ('descrizione', models.TextField(db_column='DESCRIZIONE')),
            ],
            options={
                'db_table': 'RICERCA_GRUPPO',
                'managed': False,
            },
        ),
    ]
