# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research_lines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RicercaGruppo",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(db_column="NOME", max_length=200)),
                ("descrizione", models.TextField(db_column="DESCRIZIONE")),
                (
                    "ricerca_erc1",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_RICERCA_ERC1",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="research_lines.ricercaerc1",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_rg",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_rg",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_GRUPPO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RicercaDocenteGruppo",
            fields=[
                ("dt_ins", models.DateTimeField(auto_now_add=True, db_column="DT_INS")),
                (
                    "dt_mod",
                    models.DateTimeField(auto_now=True, db_column="DT_MOD", null=True),
                ),
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dt_inizio",
                    models.DateField(blank=True, db_column="DT_INIZIO", null=True),
                ),
                (
                    "dt_fine",
                    models.DateField(blank=True, db_column="DT_FINE", null=True),
                ),
                (
                    "personale",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressbook.personale",
                    ),
                ),
                (
                    "ricerca_gruppo",
                    models.ForeignKey(
                        db_column="ID_RICERCA_GRUPPO",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research_groups.ricercagruppo",
                    ),
                ),
                (
                    "user_ins",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ins_rdg",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mod_rdg",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RICERCA_DOCENTE_GRUPPO",
                "managed": True,
            },
        ),
    ]
