# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_alter_personaleattivotuttiruoli_matricola'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubblicazioneautori',
            name='id',
        ),
        migrations.AlterField(
            model_name='docenteptaaltridati',
            name='matricola',
            field=models.OneToOneField(db_column='ID_PERSONALE_MATRICOLA', on_delete=django.db.models.deletion.CASCADE, related_name='docente_pta_altri_dati', to='addressbook.personale', to_field='matricola'),
        ),
        migrations.AlterField(
            model_name='pubblicazioneautori',
            name='codice_fiscale',
            field=models.CharField(blank=True, db_column='CODICE_FISCALE', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pubblicazioneautori',
            name='item',
            field=models.ForeignKey(db_column='ITEM_ID', on_delete=django.db.models.deletion.CASCADE, related_name='pubblicazioneautori', to='teachers.pubblicazionedatibase'),
        ),
    ]
