from django.urls import path
from .views import (
    advancedtraining_direttore_edit,
    advancedtraining_duplicate,
    advancedtraining_info_edit,
    advancedtraining_masters,
    advancedtraining_info_create,
    advancedtraining_info_delete,
    advancedtraining_proponente_edit,
    advancedtraining_status_change,
    advancedtraining_load_tab,
    consiglio_esterno_delete,
    consiglio_esterno_edit,
    consiglio_esterno_new,
    consiglio_interno_new,
    consiglio_interno_edit,
    consiglio_interno_delete,
    incarico_didattico_delete,
    incarico_didattico_edit,
    incarico_didattico_new,
    partner_delete,
    partner_edit,
    partner_new,
    piano_didattico_delete,
    piano_didattico_edit,
    piano_didattico_new,
)
from advanced_training.pdf_view import advancedtraining_export_pdf

app_name = "management"

prefix = "advanced-training"

urlpatterns = [
    path(f"{prefix}/", advancedtraining_masters, name="advanced-training"),
    path(
        f"{prefix}/<int:pk>/",
        advancedtraining_info_edit,
        name="advanced-training-detail",
    ),
    path(
        f"{prefix}/new/",
        advancedtraining_info_create,
        name="advanced-training-create",
    ),
    path(
        f"{prefix}/<int:pk>/delete/",
        advancedtraining_info_delete,
        name="advanced-training-delete",
    ),
    path(
        f"{prefix}/<int:pk>/status/<str:status_cod>/",
        advancedtraining_status_change,
        name="advanced-training-status-change",
    ),
    path(
        f"{prefix}/<int:pk>/duplicate/",
        advancedtraining_duplicate,
        name="advanced-training-duplicate",
    ),
    path(
        f"{prefix}/<int:pk>/load-tab/<str:tab_name>/",
        advancedtraining_load_tab,
        name="advanced-training-load-tab",
    ),
    path(
        "master/<int:master_id>/consiglio-interno/new/",
        consiglio_interno_new,
        name="consiglio-interno-new",
    ),
    path(
        "master/<int:master_id>/consiglio-interno/<int:consiglio_id>/edit/",
        consiglio_interno_edit,
        name="consiglio-interno-edit",
    ),
    path(
        "master/<int:master_id>/consiglio-interno/<int:consiglio_id>/delete/",
        consiglio_interno_delete,
        name="consiglio-interno-delete",
    ),
    path(
        f"{prefix}/<int:pk>/proponente/",
        advancedtraining_proponente_edit,
        name="advanced-training-proponente-edit",
    ),
    path(
        "<int:pk>/direttore-scientifico/",
        advancedtraining_direttore_edit,
        name="advanced-training-direttore-edit",
    ),
    path(
        f"{prefix}/<int:pk>/incarichi/new/",
        incarico_didattico_new,
        name="incarico-didattico-new",
    ),
    path(
        f"{prefix}/<int:pk>/incarichi/<int:incarico_id>/edit/",
        incarico_didattico_edit,
        name="incarico-didattico-edit",
    ),
    path(
        f"{prefix}/<int:pk>/incarichi/<int:incarico_id>/delete/",
        incarico_didattico_delete,
        name="incarico-didattico-delete",
    ),
    path(
        f"{prefix}/<int:pk>/piano-didattico/new/",
        piano_didattico_new,
        name="piano-didattico-new",
    ),
    path(
        f"{prefix}/<int:pk>/piano-didattico/<int:modulo_id>/edit/",
        piano_didattico_edit,
        name="piano-didattico-edit",
    ),
    path(
        f"{prefix}/<int:pk>/piano-didattico/<int:modulo_id>/delete/",
        piano_didattico_delete,
        name="piano-didattico-delete",
    ),
    path(f"{prefix}/<int:pk>/partner/new/", partner_new, name="partner-new"),
    path(
        f"{prefix}/<int:pk>/partner/<int:partner_id>/edit/",
        partner_edit,
        name="partner-edit",
    ),
    path(
        f"{prefix}/<int:pk>/partner/<int:partner_id>/delete/",
        partner_delete,
        name="partner-delete",
    ),
    path(
        f"{prefix}/<int:pk>/consiglio-esterno/new/",
        consiglio_esterno_new,
        name="consiglio-esterno-new",
    ),
    path(
        f"{prefix}/<int:pk>/consiglio-esterno/<int:cons_id>/edit/",
        consiglio_esterno_edit,
        name="consiglio-esterno-edit",
    ),
    path(
        f"{prefix}/<int:pk>/consiglio-esterno/<int:cons_id>/delete/",
        consiglio_esterno_delete,
        name="consiglio-esterno-delete",
    ),
    path(
        f"{prefix}/<int:pk>/export/pdf/",
        advancedtraining_export_pdf,
        name="advanced-training-export-pdf",
    ),
]
