# Generated by Django 4.2.20 on 2026-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidatticaPianiAfRegSce',
            fields=[
                ('af_reg_sce_id', models.IntegerField(db_column='AF_REG_SCE_ID', primary_key=True, serialize=False)),
                ('af_pds_id', models.IntegerField(blank=True, db_column='AF_PDS_ID', null=True)),
                ('aa_off_id_af_reg_sce', models.IntegerField(blank=True, db_column='AA_OFF_ID_AF_REG_SCE', null=True)),
                ('flag_statutaria', models.CharField(blank=True, db_column='FLAG_STATUTARIA', max_length=255, null=True)),
                ('flag_verifica_piani', models.CharField(blank=True, db_column='FLAG_VERIFICA_PIANI', max_length=255, null=True)),
                ('flag_controllo_anno_offerta', models.CharField(blank=True, db_column='FLAG_CONTROLLO_ANNO_OFFERTA', max_length=255, null=True)),
                ('dt_ins_mod', models.DateField(blank=True, db_column='DT_INS_MOD', null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_PIANI_AF_REG_SCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaPianiBloccoSce',
            fields=[
                ('blocco_sce_id', models.IntegerField(db_column='BLOCCO_SCE_ID', primary_key=True, serialize=False)),
                ('progressivo_blocco_sce', models.IntegerField(blank=True, db_column='PROGRESSIVO_BLOCCO_SCE', null=True)),
                ('lingua_cod', models.CharField(blank=True, db_column='LINGUA_COD', max_length=20, null=True)),
                ('ord_num_lingua', models.IntegerField(blank=True, db_column='ORD_NUM_LINGUA', null=True)),
                ('cond_blocco_sce_desc', models.TextField(blank=True, db_column='COND_BLOCCO_SCE_DESC', null=True)),
                ('dt_ins_mod', models.DateField(blank=True, db_column='DT_INS_MOD', null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_PIANI_BLOCCO_SCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaPianiRegSce',
            fields=[
                ('reg_sce_id', models.IntegerField(db_column='REG_SCE_ID', primary_key=True, serialize=False)),
                ('aa_off_id_reg_sce', models.IntegerField(blank=True, db_column='AA_OFF_ID_REG_SCE', null=True)),
                ('anno_corso_reg_sce', models.IntegerField(blank=True, db_column='ANNO_CORSO_REG_SCE', null=True)),
                ('progressivo_reg_sce', models.IntegerField(blank=True, db_column='PROGRESSIVO_REG_SCE', null=True)),
                ('tipo_reg_sce_cod', models.CharField(blank=True, db_column='TIPO_REG_SCE_COD', max_length=20, null=True)),
                ('tipo_um_reg_sce_cod', models.CharField(blank=True, db_column='TIPO_UM_REG_SCE_COD', max_length=20, null=True)),
                ('minimo', models.DecimalField(blank=True, db_column='MINIMO', decimal_places=2, max_digits=5, null=True)),
                ('massimo', models.DecimalField(blank=True, db_column='MASSIMO', decimal_places=2, max_digits=5, null=True)),
                ('anno_anticipo', models.IntegerField(blank=True, db_column='ANNO_ANTICIPO', null=True)),
                ('reg_sce_desc_ita', models.CharField(blank=True, db_column='REG_SCE_DESC_ITA', max_length=255, null=True)),
                ('reg_sce_desc_eng', models.CharField(blank=True, db_column='REG_SCE_DESC_ENG', max_length=255, null=True)),
                ('nota_pre_desc_ita', models.TextField(blank=True, db_column='NOTA_PRE_DESC_ITA', null=True)),
                ('nota_pre_desc_eng', models.TextField(blank=True, db_column='NOTA_PRE_DESC_ENG', null=True)),
                ('nota_post_desc_ita', models.TextField(blank=True, db_column='NOTA_POST_DESC_ITA', null=True)),
                ('nota_post_desc_eng', models.TextField(blank=True, db_column='NOTA_POST_DESC_ENG', null=True)),
                ('filtri_reg_sce_desc', models.TextField(blank=True, db_column='FILTRI_REG_SCE_DESC', null=True)),
                ('cond_reg_sce_desc', models.TextField(blank=True, db_column='COND_REG_SCE_DESC', null=True)),
                ('ateneo_id', models.IntegerField(blank=True, db_column='ATENEO_ID', null=True)),
                ('ateneo_des', models.CharField(blank=True, db_column='ATENEO_DES', max_length=255, null=True)),
                ('taf_cod', models.CharField(blank=True, db_column='TAF_COD', max_length=20, null=True)),
                ('id_ambito', models.IntegerField(blank=True, db_column='ID_AMBITO', null=True)),
                ('dt_ins_mod', models.DateField(blank=True, db_column='DT_INS_MOD', null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_PIANI_REG_SCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaPianiSchema',
            fields=[
                ('schema_piano_id', models.IntegerField(db_column='SCHEMA_PIANO_ID', primary_key=True, serialize=False)),
                ('schema_piano_cod', models.CharField(blank=True, db_column='SCHEMA_PIANO_COD', max_length=20, null=True)),
                ('schema_piano_desc_ita', models.CharField(blank=True, db_column='SCHEMA_PIANO_DESC_ITA', max_length=255, null=True)),
                ('schema_piano_desc_eng', models.CharField(blank=True, db_column='SCHEMA_PIANO_DESC_ENG', max_length=255, null=True)),
                ('flag_schema_visibile_web', models.CharField(blank=True, db_column='FLAG_SCHEMA_VISIBILE_WEB', max_length=255, null=True)),
                ('id_classe_miur', models.IntegerField(blank=True, db_column='ID_CLASSE_MIUR', null=True)),
                ('classe_miur_cod', models.CharField(blank=True, db_column='CLASSE_MIUR_COD', max_length=20, null=True)),
                ('classe_miur_desc_ita', models.CharField(blank=True, db_column='CLASSE_MIUR_DESC_ITA', max_length=255, null=True)),
                ('classe_miur_desc_eng', models.CharField(blank=True, db_column='CLASSE_MIUR_DESC_ENG', max_length=255, null=True)),
                ('dt_ins_mod', models.DateField(blank=True, db_column='DT_INS_MOD', null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_PIANI_SCHEMA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidatticaPianiStudio',
            fields=[
                ('piano_studio_id', models.IntegerField(db_column='PIANO_STUDIO_ID', primary_key=True, serialize=False)),
                ('piano_studio_cod', models.CharField(blank=True, db_column='PIANO_STUDIO_COD', max_length=20, null=True)),
                ('aa_coorte_id', models.IntegerField(blank=True, db_column='AA_COORTE_ID', null=True)),
                ('aa_revisione_id', models.IntegerField(blank=True, db_column='AA_REVISIONE_ID', null=True)),
                ('stato_piano_studio_cod', models.CharField(blank=True, db_column='STATO_PIANO_STUDIO_COD', max_length=20, null=True)),
                ('stato_piano_studio_desc_ita', models.CharField(blank=True, db_column='STATO_PIANO_STUDIO_DESC_ITA', max_length=255, null=True)),
                ('stato_piano_studio_desc_eng', models.CharField(blank=True, db_column='STATO_PIANO_STUDIO_DESC_ENG', max_length=255, null=True)),
                ('dt_ins_mod', models.DateField(blank=True, db_column='DT_INS_MOD', null=True)),
            ],
            options={
                'db_table': 'DIDATTICA_PIANI_STUDIO',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DidatticaPianoRegolamento',
        ),
        migrations.DeleteModel(
            name='DidatticaPianoSceltaAf',
        ),
        migrations.DeleteModel(
            name='DidatticaPianoSceltaFilAnd',
        ),
        migrations.RemoveField(
            model_name='didatticapianosceltaschepiano',
            name='sche_piano',
        ),
        migrations.DeleteModel(
            name='DidatticaPianoSceltaVincoli',
        ),
        migrations.AlterModelTable(
            name='didatticatestiregolamento',
            table='DIDATTICA_TESTI_REGOLAMENTO_ID',
        ),
        migrations.DeleteModel(
            name='DidatticaPianoSceltaSchePiano',
        ),
        migrations.DeleteModel(
            name='DidatticaPianoSche',
        ),
    ]
