# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didatticaambiti',
            options={'managed': True, 'verbose_name': 'Scope', 'verbose_name_plural': 'Scopes'},
        ),
        migrations.AlterModelOptions(
            name='didatticaattivitaformativa',
            options={'managed': True, 'ordering': ('ciclo_des',), 'verbose_name': 'Study activity', 'verbose_name_plural': 'Study activities'},
        ),
        migrations.AlterModelOptions(
            name='didatticaattivitaformativamodalita',
            options={'managed': True, 'verbose_name': 'Study activity mode', 'verbose_name_plural': 'Study activity modes'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdsaltridati',
            options={'managed': True, 'verbose_name': 'Cds other data', 'verbose_name_plural': 'Cds other data'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdsaltridatiufficio',
            options={'managed': True, 'ordering': ('ordine',), 'verbose_name': 'Cds office other data', 'verbose_name_plural': 'Cds office other data'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdsgruppi',
            options={'managed': True, 'ordering': ('ordine',), 'verbose_name': 'Cds group', 'verbose_name_plural': 'Cds groups'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdsgruppicomponenti',
            options={'managed': True, 'ordering': ('ordine',), 'verbose_name': 'Cds group member', 'verbose_name_plural': 'Cds group members'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdslingua',
            options={'managed': True, 'verbose_name': 'Cds language', 'verbose_name_plural': 'Cds languages'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdsperiodi',
            options={'managed': True, 'verbose_name': 'Study course period', 'verbose_name_plural': 'Study course periods'},
        ),
        migrations.AlterModelOptions(
            name='didatticacdstipocorso',
            options={'managed': True, 'verbose_name': 'Cds course type', 'verbose_name_plural': 'Cds course types'},
        ),
        migrations.AlterModelOptions(
            name='didatticaclasselaurea',
            options={'managed': True, 'verbose_name': 'Classe laurea', 'verbose_name_plural': 'Classi laurea'},
        ),
        migrations.AlterModelOptions(
            name='didatticacopertura',
            options={'managed': True, 'verbose_name': 'Teaching coverage', 'verbose_name_plural': 'Teaching coverages'},
        ),
        migrations.AlterModelOptions(
            name='didatticacoperturadettaglioore',
            options={'managed': True, 'verbose_name': 'Teaching coverage hours detail', 'verbose_name_plural': 'Teaching coverage hours details'},
        ),
        migrations.AlterModelOptions(
            name='didatticapdsregolamento',
            options={'managed': True, 'verbose_name': 'Academic pathway', 'verbose_name_plural': 'Academic pathways'},
        ),
        migrations.AlterModelOptions(
            name='didatticapianoregolamento',
            options={'managed': True, 'verbose_name': 'Regulation study plan', 'verbose_name_plural': 'Regulation study plans'},
        ),
        migrations.AlterModelOptions(
            name='didatticapianosceltaaf',
            options={'managed': True, 'ordering': ('ciclo_des',), 'verbose_name': 'Study plan study activity choice', 'verbose_name_plural': 'Study plan study activity choices'},
        ),
        migrations.AlterModelOptions(
            name='didatticapianosceltafiland',
            options={'managed': True, 'verbose_name': 'Study plan choice filter', 'verbose_name_plural': 'Study plan choice filters'},
        ),
        migrations.AlterModelOptions(
            name='didatticapianosceltaschepiano',
            options={'managed': True, 'verbose_name': 'Study plan sheet choice plan', 'verbose_name_plural': 'Study plan sheet choice plans'},
        ),
        migrations.AlterModelOptions(
            name='didatticapianosceltavincoli',
            options={'managed': True, 'verbose_name': 'Study plan constraint choice', 'verbose_name_plural': 'Study plan constraint choices'},
        ),
        migrations.AlterModelOptions(
            name='didatticapianosche',
            options={'managed': True, 'verbose_name': 'Study plan sheet', 'verbose_name_plural': 'Study plan sheets'},
        ),
        migrations.AlterModelOptions(
            name='didatticaregolamento',
            options={'managed': True, 'verbose_name': 'Didactic regulation', 'verbose_name_plural': 'Didactic regulations'},
        ),
        migrations.AlterModelOptions(
            name='didatticaregolamentoaltridati',
            options={'managed': True, 'verbose_name': 'Didactic regulation other data', 'verbose_name_plural': 'Didactic regulation other data'},
        ),
        migrations.AlterModelOptions(
            name='didatticaregolamentotipologiaaltridati',
            options={'managed': True, 'verbose_name': 'Didactic regulation other data type', 'verbose_name_plural': 'Didactic regulation other data types'},
        ),
        migrations.AlterModelOptions(
            name='didatticassd',
            options={'managed': True, 'verbose_name': 'SSD', 'verbose_name_plural': 'SSD'},
        ),
        migrations.AlterModelOptions(
            name='didatticatestiaf',
            options={'managed': True, 'verbose_name': 'Study activity text', 'verbose_name_plural': 'Study activity texts'},
        ),
        migrations.AlterModelOptions(
            name='didatticatestiregolamento',
            options={'managed': True, 'verbose_name': 'Didactic regulation text', 'verbose_name_plural': 'Didactic regulation texts'},
        ),
        migrations.AlterField(
            model_name='didatticapianosceltaschepiano',
            name='sche_piano',
            field=models.OneToOneField(db_column='SCHE_PIANO_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='didatticapianosceltaschepiano', serialize=False, to='cds.didatticapianosche'),
        ),
        migrations.AlterField(
            model_name='didatticapianosche',
            name='regpiani',
            field=models.ForeignKey(db_column='REGPIANI_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='didatticapianosche', to='cds.didatticapianoregolamento'),
        ),
        migrations.AlterField(
            model_name='didatticatestiaf',
            name='af',
            field=models.ForeignKey(db_column='AF_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='didatticaf', serialize=False, to='cds.didatticaattivitaformativa'),
        ),
        migrations.AlterField(
            model_name='didatticatestiaf',
            name='testi_af_id',
            field=models.IntegerField(blank=True, db_column='TESTI_AF_ID', null=True),
        ),
    ]
