# Generated by Django 4.2.20 on 2026-06-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_didatticapianiafregsce_didatticapianibloccosce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDidatticaAfPianiStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_pds_id', models.IntegerField(db_column='AF_PDS_ID')),
                ('id_cds', models.IntegerField(blank=True, db_column='ID_CDS', null=True)),
                ('cds_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='CDS_COD', max_length=20, null=True)),
                ('ord_id', models.IntegerField(blank=True, db_column='ORD_ID', null=True)),
                ('ord_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ORD_COD', max_length=20, null=True)),
                ('aa_ord_id', models.IntegerField(blank=True, db_column='AA_ORD_ID', null=True)),
                ('regdid_id', models.IntegerField(blank=True, db_column='REGDID_ID', null=True)),
                ('regdid_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='REGDID_COD', max_length=20, null=True)),
                ('aa_regdid_id', models.IntegerField(blank=True, db_column='AA_REGDID_ID', null=True)),
                ('anno_di_scelta_percorso', models.DecimalField(blank=True, db_column='ANNO_DI_SCELTA_PERCORSO', decimal_places=0, max_digits=2, null=True)),
                ('lingua_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='LINGUA_COD', max_length=20, null=True)),
                ('ana_af_id', models.IntegerField(blank=True, db_column='ANA_AF_ID', null=True)),
                ('ana_af_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ANA_AF_COD', max_length=20, null=True)),
                ('ana_af_desc_ita', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ANA_AF_DESC_ITA', max_length=255, null=True)),
                ('ana_af_capog_id', models.IntegerField(blank=True, db_column='ANA_AF_CAPOG_ID', null=True)),
                ('ana_af_capog_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ANA_AF_CAPOG_COD', max_length=20, null=True)),
                ('ana_af_capog_desc_ita', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ANA_AF_CAPOG_DESC_ITA', max_length=255, null=True)),
                ('ana_af_capog_desc_eng', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='ANA_AF_CAPOG_DESC_ENG', max_length=255, null=True)),
                ('flag_obbl', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='FLAG_OBBL', max_length=255, null=True)),
                ('flag_raggruppamento', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='FLAG_RAGGRUPPAMENTO', max_length=255, null=True)),
                ('flag_capogruppo', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='FLAG_CAPOGRUPPO', max_length=255, null=True)),
                ('flag_raggruppata', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='FLAG_RAGGRUPPATA', max_length=255, null=True)),
                ('flag_no_raggr_o_capog', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='FLAG_NO_RAGGR_O_CAPOG', max_length=255, null=True)),
                ('mod_did_cod', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='MOD_DID_COD', max_length=20, null=True)),
                ('mod_did_desc_ita', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='MOD_DID_DESC_ITA', max_length=255, null=True)),
                ('mod_did_desc_eng', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='MOD_DID_DESC_ENG', max_length=255, null=True)),
                ('flag_segmento', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', db_column='FLAG_SEGMENTO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'V_DIDATTICA_AF_PIANI_STUDIO',
                'managed': False,
            },
        ),
    ]
