# Generated by Django 4.2.16 on 2024-10-21 11:17

import companies.settings
from django.db import migrations, models
import django.db.models.deletion
import generics.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpinoffStartupAreaInnovazioneS3Calabria",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_area_s3",
                    models.CharField(db_column="DESCR_AREA_S3", max_length=1000),
                ),
            ],
            options={
                "db_table": "SPINOFF_STARTUP_AREA_INNOVAZIONE_S3_CALABRIA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpinoffStartupDatiBase",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "piva",
                    models.CharField(
                        db_column="PIVA",
                        max_length=30,
                        unique=True,
                        validators=[generics.validators.validate_piva],
                    ),
                ),
                (
                    "nome_azienda",
                    models.CharField(db_column="NOME_AZIENDA", max_length=1000),
                ),
                (
                    "nome_file_logo",
                    models.FileField(
                        blank=True,
                        db_column="NOME_FILE_LOGO",
                        max_length=1000,
                        null=True,
                        upload_to=companies.settings.companies_media_path,
                        validators=[
                            generics.validators.validate_image_file_extension,
                            generics.validators.validate_file_size,
                        ],
                    ),
                ),
                ("descrizione_ita", models.TextField(db_column="DESCRIZIONE_ITA")),
                (
                    "descrizione_eng",
                    models.TextField(
                        blank=True, db_column="DESCRIZIONE_ENG", null=True
                    ),
                ),
                (
                    "url_sito_web",
                    models.URLField(
                        blank=True, db_column="URL_SITO_WEB", max_length=4000, null=True
                    ),
                ),
                (
                    "referente_unical",
                    models.CharField(db_column="REFERENTE_UNICAL", max_length=1000),
                ),
                (
                    "ceo",
                    models.CharField(
                        blank=True, db_column="CEO", max_length=1000, null=True
                    ),
                ),
                (
                    "is_startup",
                    models.BooleanField(db_column="IS_STARTUP", default=False),
                ),
                (
                    "is_spinoff",
                    models.BooleanField(db_column="IS_SPINOFF", default=False),
                ),
                ("is_active", models.BooleanField(db_column="ATTIVO", default=True)),
                ("ordinamento", models.IntegerField(db_column="ORDINE", default=10)),
                (
                    "area_innovazione_s3_calabria",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_AREA_INNOVAZIONE_S3_CALABRIA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.spinoffstartupareainnovaziones3calabria",
                    ),
                ),
            ],
            options={
                "db_table": "SPINOFF_STARTUP_DATI_BASE",
                "ordering": ["ordinamento"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TipologiaAreaTecnologica",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descr_area_ita",
                    models.CharField(db_column="DESCR_AREA_ITA", max_length=1000),
                ),
                (
                    "descr_area_eng",
                    models.CharField(
                        blank=True,
                        db_column="DESCR_AREA_ENG",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "TIPOLOGIA_AREA_TECNOLOGICA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpinoffStartupDipartimento",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_origine_dipartimento",
                    models.CharField(
                        db_column="NOME_ORIGINE_DIPARTIMENTO", max_length=1000
                    ),
                ),
                (
                    "didattica_dipartimento",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_DIDATTICA_DIPARTIMENTO",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.didatticadipartimento",
                    ),
                ),
                (
                    "spinoff_startup_dati_base",
                    models.ForeignKey(
                        db_column="ID_SPINOFF_STARTUP_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.spinoffstartupdatibase",
                    ),
                ),
            ],
            options={
                "db_table": "SPINOFF_STARTUP_DIPARTIMENTO",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="spinoffstartupdatibase",
            name="area_tecnologica",
            field=models.ForeignKey(
                db_column="ID_AREA_TECNOLOGICA",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="companies.tipologiaareatecnologica",
            ),
        ),
        migrations.AddField(
            model_name="spinoffstartupdatibase",
            name="matricola_referente_unical",
            field=models.ForeignKey(
                blank=True,
                db_column="MATRICOLA_REFERENTE_UNICAL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
    ]
