# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffstartupdipartimento',
            name='spinoff_startup_dati_base',
            field=models.ForeignKey(blank=True, db_column='ID_SPINOFF_STARTUP_DATI_BASE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spinoffstartupdipartimento', to='companies.spinoffstartupdatibase'),
        ),
    ]
