# MAPPING LABEL

LABEL_MAPPING = {
    'en': {
        'RegDidId': 'Teaching Regulation ID',
        'RegDidState': 'Teaching Regulation State',
        'CdSId': 'Course of Study ID',
        'CdSCod': 'Course of Study Code',
        'AcademicYear': 'Academic Year',
        'CdSName': 'Course of Study Name',
        'DepartmentId': 'Department ID',
        'DepartmentName': 'Department',
        'DepartmentNameShort': 'Department Name Short',
        'CourseType': 'Course Type',
        'CourseTypeDescription': 'Course Type',
        'CourseClassCod': 'Course Class Cod',
        'CourseClassName': 'Course Class Name',
        'CourseInterClassCod': 'Course InterClass Cod',
        'CourseInterClassDes': 'Course InterClass Name',
        'CdSLanguage': 'Language',
        'CdSDuration': 'Duration',
        'CdSECTS': 'ECTS',
        'CdSAttendance': 'Attendance',
        'CdSIntro': 'Intro',
        'CdSDoc': 'Document',
        'CdSVideo': 'Video',
        'CdSGoals': 'Objectives of the course',
        'CdSAccess': 'Access',
        'CdSAdmission': 'Admission',
        'CdSProfiles': 'Professional profiles and employment opportunities',
        'CdSFinalTest': 'Final Test',
        'CdSFinalTestMode': 'Final Test Mode',
        'CdSSatisfactionSurvey': 'Satisfaction Survey',
        'JointDegree': 'Joint Degree',
        'LaboratoryId': 'Laboratory Id',
        'LaboratoryName': 'Laboratory Name',
        'Area': 'Area',
        'Dimension': 'Dimension',
        'ScientificDirector': 'Scientific Director',
        'ScientificDirectors': 'Scientific Directors',
        'ScientificDirectorId': 'Id Scientific Director',
        'StudyPlanId': 'Study Plan ID',
        'StudyPlanName': 'Study Plan Name',
        'StudyPlanCod': 'Study Plan Code',
        'StudyActivities': 'Study Activities',
        'StudyActivityRegDidId': 'Teaching Regulation ID',
        'StudyActivityID': 'Study Activity ID',
        'StudyActivityCod': 'Study Activity Cod',
        'StudyActivityName': 'Study Activity',
        'StudyActivityCdSID': 'Course of Study ID',
        'StudyActivityCdSCod': 'Course of study Code',
        'StudyActivityYear': 'Year',
        'StudyActivityErogationYear': 'Erogation Year',
        'StudyActivitySemester': 'Semester',
        'StudyActivityECTS': 'ECTS',
        'StudyActivitySSD': 'SSD',
        'StudyActivitySSDCod': 'SSD Code',
        'StudyActivityCompulsory': 'Compulsory',
        'StudyActivityCdSName': 'Course of Study',
        'StudyActivityTeachingUnitType': 'Teaching Unit Type',
        'StudyActivityTeacherID': 'Teacher ID',
        'StudyActivityTeacherName': 'Teacher',
        'StudyActivityContent': 'Content',
        'StudyActivityProgram': 'Program',
        'StudyActivityLearningOutcomes': 'Learning Outcomes',
        'StudyActivityMethodology': 'Methodology',
        'StudyActivityEvaluation': 'Evaluation',
        'StudyActivityTextbooks': 'Textbooks',
        'StudyActivityWorkload': 'Workload',
        'StudyActivityElearningLink': 'E-Learning Link',
        'StudyActivityElearningInfo': 'E-Learning Info',
        'StudyActivityPrerequisites': 'Prerequisites',
        'StudyActivitiesModules': 'Partition',
        'StudyActivityAA': 'Academic Year',
        'StudyActivityLanguage': 'Language',
        'StudyActivityRoot': 'Study Activity Root',
        'StudyActivityBorrowedFrom': 'Borrowed from',
        'StudyActivitiesBorrowedFromThis': 'Borrowed from this',
        'StudyActivityPartitionCod': 'Study Activity Partition Cod',
        'StudyActivityPartitionDescription': 'Study Activity Partition Description',
        'SingleStudyActivityPartitionCod': 'Single Study Activity Partition Cod',
        'SingleStudyActivityPartitionDescription': 'Single Study Activity Partition Description',
        'StudyActivityPartitionType': 'Study Activity Partition Type',
        'StudyActivityPartitionStart': 'Study Activity Start of Partition',
        'StudyActivityPartitionEnd': 'Study Activity End of Partition',
        'Teacher': 'Teacher Web Page',
        'TeacherID': 'Teacher ID',
        'TeacherName': 'Name',
        'TeacherRole': 'Role',
        'TeacherRoleDescription': 'Role',
        'TeacherSSD': 'SSD',
        'TeacherDepartmentID': 'Department ID',
        'TeacherDepartmentCod': 'Department Cod',
        'TeacherDepartmentName': 'Department',
        'TeacherSSDCod': 'SSD',
        'TeacherSSDDescription': 'SSD',
        'TeacherCode': 'Teacher Code',
        'TeacherFirstName': 'First Name',
        'TeacherLastName': 'Last Name',
        'TeacherOffice': 'Office',
        'TeacherOfficeReference': 'Office Reference',
        'TeacherEmail': 'Email',
        'TeacherPEC': 'PEC',
        'TeacherPrivateEmail': 'Private Email',
        'TeacherTelOffice': 'Office Phone',
        'TeacherTelCelOffice': 'Office Mobile Phone',
        'TeacherTelCel': 'Mobile Phone',
        'TeacherTelDomicile': 'Domicile Phone',
        'TeacherTelResidence': 'Residence Phone',
        'TeacherFax': 'Fax',
        'TeacherSkype': 'Skype',
        'TeacherWebSite': 'URL Web Site',
        'TeacherCV': 'Curriculum Vitae',
        'TeacherFunctions': 'Administrative roles',
        'Office': 'Office',
        'OfficeReference': 'Office Reference',
        'Email': 'Email',
        'PEC': 'PEC',
        'PrivateEmail': 'Private Email',
        'TelOffice': 'Office Phone',
        'TelCelOffice': 'Office Mobile Phone',
        'TelCel': 'Mobile Phone',
        'TelDomicile': 'Domicile Phone',
        'TelResidence': 'Residence Phone',
        'Fax': 'Fax',
        'Skype': 'Skype',
        'WebSite': 'URL Web Site',
        'CV': 'Curriculum Vitae',
        'Contacts': 'Contacts',
        'ContactType' : 'Contact Type',
        'Contact' : 'Contact',
        'Function': 'Function',
        'Structure': 'Structure',
        'Role': 'Role',
        'RoleDescription': 'Role',
        'ID': 'ID',
        'IdErc1': 'Id Erc1',
        'IdErc0': 'IdErc0',
        'Name': 'Name',
        'RGroupID': 'Group ID',
        'RGroupName': 'Group Name',
        'RGroupDescription': 'Group Description',
        'RLineID': 'Research Line ID',
        'RLineDescription': 'Description',
        'RLineResults': 'Results',
        'RLineERC0Id': 'ERC0 ID',
        'RLineERC0Name': 'ERC0 Name',
        'RLineERC1Id': 'ERC1 ID',
        'RLineERC1Name': 'ERC1 Name',
        'DepartmentID': 'Department ID',
        'DepartmentCod': 'Department Code',
        'PhdCdsCOD': 'Course of Study Code',
        'PhdCdsName': 'Course of Study Name',
        'PhdRegID': 'PhD Regulation ID',
        'PhdRegCOD': 'PhD Regulation Code',
        'PhdCdSDuration': 'Duration',
        'PhdCdSECTS': 'ECTS',
        'PhdCdSAttendance': 'Attendance',
        'CourseName': 'Course Name',
        'CycleNumber': 'Cycle Number',
        'StudyPlanCOD': 'Study Plan Code',
        'StudyPlanDes': 'Study Plan Description',
        'FUNZIONI': 'Tasks',
        'COMPETENZE': 'Skills',
        'SBOCCHI': 'Career opportunities',
        'StructureCod': 'Structure Cod',
        'StructureTypeName': 'Type',
        'StructureName': 'Name',
        'StructureTypeCOD': 'Type',
        'StructureFatherId': 'Reference Structure',
        'StructureFatherName': 'Reference Structure',
        'StructureEmail': 'Email',
        'StructurePec': 'Pec',
        'StructureTfr': 'Phone',
        'StructurePersonnelFunctions': 'Administrative Staff',
        'LaboratoryId': 'ID',
        'Interdepartmental': 'Interdepartmental',
        'InfrastructureName': 'Infrastructure Name',
        'ExtraDepartments': 'Other Departments',
        'CompletionReferentName': 'Completion Referent Name',
        'CompletionReferentId': 'Completion Referent ID',
        'ScientificDirectorId': 'Scientific Director',
        'ScientificDirectorName': 'Scientific Director',
        'LaboratoryName': 'Name',
        'LaboratoryAcronym': 'Acronym',
        'LaboratoryLogo': 'Logo',
        'LaboratoryURL': 'Web Page',
        'LaboratoryEquipment': 'Equipment',
        'DepartmentReferentId': 'Department Referent ID',
        'DepartmentReferentCod': 'Department Referent Cod',
        'DepartmentReferentName': 'Department',
        'DepartmentURL': 'URL',
        'StructureURL': 'URL',
        'StructureChilds': 'Sub-structures',
        'LaboratoryScope': 'Scope',
        'LaboratoryServicesScope': 'Services Scope',
        'LaboratoryResearchScope': 'Research Scope',
        'LaboratoryTeachingScope': 'Teaching Scope',
        'LaboratoryActivities': 'Activities',
        'LaboratoryErc1': 'Erc 1',
        'LaboratoryResearchPersonnel': 'Research Scope',
        'LaboratoryTechPersonnel': 'Tech Personnel',
        'LaboratoryOfferedServices': 'Services',
        'LaboratoryLocation': 'Location',
        'LocationBuilding': 'Building',
        'LocationFloor': 'Floor',
        'LocationNotes': 'Notes',
        'ServiceName': 'Name',
        'ServiceDescription': 'Description',
        'TechPersonnelID': 'ID',
        'TechPersonnelName': 'Name',
        'TechPersonnelRole': 'Role',
        'ResearchPersonnelID': 'ID',
        'ResearchPersonnelName': 'Name',
        'LaboratoryErc1Cod': 'Erc1 Code',
        'LaboratoryErc1Description': 'Erc1 Description',
        'LaboratoryErc0Cod': 'Erc0 Code',
        'LaboratoryErc0Description': 'Erc0 Description',
        'LaboratoryActivityType': 'Activity Type',
        'Description': 'Description',
        'PublicationId': 'ID',
        'PublicationTitle': 'Title',
        'PublicationAbstract': 'Abstract',
        'PublicationCollection': 'Collection',
        'PublicationCommunity': 'Type',
        'Publication': 'Publication',
        'PublicationLabel': 'Publication Type',
        'PublicationContributors': 'All Authors',
        'PublicationAuthors': 'Unical Authors',
        'PublicationYear': 'Publication Year',
        'AuthorId': 'ID',
        'AuthorName': 'Name',
        'CommunityId': 'Id',
        'CommunityName': 'Name',
        'PublicationReferenceAuthor': 'Reference Author',
        'Erc1List':'Erc1 List',
        'Erc2List': 'Erc2 List',
        'PublicationUrl': 'Publication Url',
        'TeacherCVFull':'Teacher CV Full',
        'TeacherCVShort':'Teacher CV Short',
        'Teachers': 'Teachers',
        'RLineErc2ID': 'Erc2 Cod',
        'RLineErc2Name': 'Erc2 Name',
        'RYear': 'Research Year',
        'RLineAster2ID': 'Research Aster 2 ID',
        'RLineAster2Name': 'Research Aster 2 Name',
        'Hours': 'Hours',
        'Cover': 'Cover',
        'CodErc2': 'Erc2 Cod',
        'RLineAster2Id': 'Aster2 Cod',
        'RLineAster2Name': 'Aster2 Name',
        'StructureMission': 'Structure Mission',
        'InfrastructureId' : 'Infrastructure Id',
        'InfrastructureDescription': 'Referent Infrastructure',
        'LaboratoryScopes': 'Laboratory Scopes',
        'ScopeID': 'Scope ID',
        'ScopeDescription': 'Scope Description',
        'PatentId': 'Patent Id',
        'PatentInitialTRL': 'Initial TRL',
        'PatentUpdatedTRL': 'Updated TRL',
        'PatentEnhancement': 'Enhancement',
        'PatentUniqueId': 'Patent Unique Id',
        'PatentTitle': 'Patent Title',
        'PatentImage': 'Patent Image',
        'PatentAbstract': 'Patent Abstract',
        'PatentUrlKnowledgeShare': 'Patent Knowledge Share',
        'PatentTechAreaId': 'Patent Tech-Area Id',
        'PatentAreaDescription': 'Area Description',
        'PatentInventors': 'Patent Inventors',
        'SpinoffId': 'Spinoff Id',
        'SpinoffPIva': 'Spinoff P.Iva',
        'SpinoffAgencyName': 'Spinoff Agency Name',
        'SpinoffImage': 'Spinoff Image',
        'SpinoffDescription': 'Spinoff Description',
        'SpinoffUnicalReferent': 'Unical Referent Spinoff',
        'SpinoffUnicalReferentId': 'Unical Referent Id',
        'TechAreaId': 'Spinoff Tech Area Id',
        'TechAreaDescription': 'Tech Area',
        'SpinoffAgencyUrl': 'Spinoff Agency Url',
        'IsSpinoff': 'Is Spinoff',
        'IsStartup': 'Is Startup',
        'PersonFunctions': ' Funzioni Persona',
        'ProjectId': 'Project Id',
        'TerritorialScopeId': 'Territorial Scope Id',
        'TerritorialScopeDescription': 'Territorial Scope',
        'TypeProgramId': 'Type Program Id',
        'TypeProgramDescription': 'Program Description',
        'ProjectTitle': 'Project Title',
        'ProjectDescription': 'Description',
        'ProjectAbstract': 'Abstract',
        'ProjectImage': 'Project Image',
        'ProjectYear': 'Project Year',
        'ProjectDepartmentId': 'Project Department Id',
        'FunctionDescription': 'Function Description',
        'FunctionCod': 'Function Cod',
        'AreaCds': 'Course Area',
        'CdsUrl': 'Course URL',
        'Researchers': 'Researchers',
        'ResearcherId': 'ResearcherId',
        'ResearcherName': 'ResearcherName',
        'CF': 'Fiscal Code',
        'MasterTitle': 'Master Title',
        'HighFormationTypeId': 'High Formation Type Id',
        'HighFormationErogationMode': 'High Formation Erogation Mode',
        'HighFormationErogationModeDescription': 'Erogation mode',
        'HighFormationHours': 'Hours',
        'HighFormationMonths': 'Months',
        'HighFormationCourseStructure': 'Course Structure',
        'HighFormationMinParticipants': 'Minimum Participants',
        'HighFormationMaxParticipants': 'Maximum Participants',
        'ListenersAccepted': 'Listeners Accepted',
        'MaxListeners': 'Maximum Listeners',
        'AdmissionRequirements': 'Admission Requirements',
        'TitleIssued': 'Title Issued',
        'DoubleTitle': 'Double Title',
        'SubscriptionFee': 'Subscription Fee',
        'ListenersFee': 'Listeners Fee',
        'WorkFunction': 'Work Function',
        'FormationObjectivesSummerSchool': 'Formation Objectives Summer School',
        'Skills': 'Skills',
        'JobOpportunities': 'Career opportunities',
        'CourseObjectives': 'Course objectives',
        'FinalTestMode': 'Final Test Mode',
        'NumModules': 'Nummber of Modules',
        'Internship': 'Internship',
        'InternshipHours': 'Internship Hours',
        'InternshipCFU': 'Internship CFU',
        'InternshipMonths': 'Internship Months',
        'TypeCompaniesInternship': 'Type Companies Internship',
        'ContentTimesCriteriaCFU': 'Content Times Criteria CFU',
        'ProjectWork': 'Project Work',
        'HighFormationMasterPartners': 'High Formation Master Partners',
        'PartnerDenomination': 'Partner Denomination',
        'PartnerURL': 'Partner URL',
        'PartnerType': 'Partner Type',
        'HighFormationMasterSelectionModes': 'High Formation Master Selection Modes',
        'SelectionType': 'Selection Type',
        'SelectionId': 'Selection Mode Id',
        'HighFormationMasterInternalCouncil': 'High Formation Master Internal Council',
        'PersonId': 'Person Id',
        'PersonName': 'Name',
        'HighFormationMasterExternalCouncil': 'High Formation Master External Council',
        'Institution': 'Institution',
        'PartnerId': 'Partner Id',
        'HighFormationMasterTeachingPlans': 'High Formation Master Teaching Plans',
        'TeachingPlanCFU': 'CFU',
        'TeachingPlanFinalTest': 'Final Test',
        'TeachingPlanSSD': 'SSD',
        'TeachingPlanModule': 'Module',
        'TeachingPlanHours': 'Hours',
        'HighFormationMasterTeachingAssignments': 'High Formation Master Teaching Assignments',
        'TeachingAssignmentsModule': 'Module',
        'TeachingAssignmentsHours': 'Hours',
        'TeachingAssignmentsTeachers': 'Teachers',
        'TeachingAssignmentsQualification': 'Qualification',
        'TeachingAssignmentsInstitution': 'Institution',
        'TeachingAssignmentsType': 'Type',
        'IdAster1': 'Aster 1 Id',
        'IdAster2' : 'Aster 2 Id',
        'Aster1List': 'Aster1 List',
        'Aster2List': 'Aster2 List',
        'HighFormationMasterYear': ' Academic Year',
        'OtherData': 'Other Data',
        'OfficesData': 'Offices Data',
        'DirectorId': 'Director Id',
        'DirectorName': 'Coordinator',
        'DeputyDirectorId': 'Deputy Director Id',
        'DeputyDirectorName': 'Deputy Coordinator',
        'SeatsNumber': 'Seats Number',
        # 'RegistrationMode': 'Registration Mode',
        'Order': 'Order',
        'OfficeName': 'Office Name',
        'OfficeDirector': 'Office Director',
        'OfficeDirectorName': 'Office Director Name',
        'Building': 'Building',
        'Floor': 'Floor',
        'Timetables': 'Timetables',
        'OnlineCounter': 'Online Counter',
        'StudyActivityTeachingUnitTypeCod': 'Study Activity Teaching Unit Type Cod',
        'StudyActivityInterclassTeachingUnitTypeCod': 'Study Activity Interclass Teaching Unit Type Cod',
        'StudyActivityInterclassTeachingUnitType': 'Study Activity Interclass Teaching Unit Type',
        'ActivityType': 'Activity Type',
        'StudyActivityHours': 'Study Activity Hours',
        'StudyActivityAcademicYear': 'Study Activity Academic Year',
        'StudyActivityDevelopmentGoal': 'Study Activity Development Goal',
        'StudyActivityModalities': 'Study Activity Modalities',
        'ModalityActivityId': 'Modality Activity Id',
        'ModalityActivityCod': 'Modality Activity Cod',
        'ModalityActivityDescription': 'Modality Activity Description',
        'StudyActivityPartitionCod': 'Study Activity Partition Code',
        'StudyActivityPartitionDes': 'Study Activity Partition Description',
        'StudyActivityExtendedPartitionCod': 'Study Activity Extended Partition Code',
        'StudyActivityExtendedPartitionDes': 'Study Activity Extended Partition Description',
        'HighFormationLanguage': 'Language',
        'ProfileId': 'Profile',
        'ProfileDescription': 'Profile Description',
        'ProfileShortDescription': 'Profile Short Description',
        'HighFormationTypeDescription': 'High Formation Type Description',
        'HighFormationErogationModeDescription': 'High Formation Erogation Mode Description',
        'ActivityName': "Activity Name",
        'SSD': "SSD",
        'Cycle': "Cycle",
        'CFU': "CFU",
        'ActivityType': "Acticity Type",
        'ReferentPhd': "Referent PhD",
        'ReferentStructureId': "Structure Id",
        'ReferentStructureName': "Structure",
        'ActivityContents': "Activity Contents",
        'Prerequisities': "Prerequisities",
        'MinStudents': "Min Students",
        'MaxStudents': "Max Students",
        'FinalTest': "Final Test",
        'MainTeachers': 'Main Teachers',
        'OtherTeachers': 'Other Teachers',
        'ErogationMode': 'Erogation Mode',
        'Departments': 'Departments',
        'Roles': 'Roles',
        'Context': 'Context',
        'Priority': 'Priority',
        'ContextDescription': 'Context Description',
        'OfficeBuilding': 'Office Building',
        'StudyActivityGroups': 'Study Activity Groups',
        'StudyActivityPdsCod': 'Study Activity Pds Cod',
        'StudyActivityPdsDes': 'Study Activity Pds Description',
        'StudyActivityFather': 'Study Activity Father',
        'StudyActivityFatherName': 'Study Activity Father Name',
        'StudyActivityFatherCode': 'Study Activity Father Code',
        'Title': 'Title',
        'Text': 'Text',
        'TextUrl': 'URL',
        'Order': 'Teaching Material Order',
        'Active': 'Teaching Material Active',
        'PublicationDate': 'Teaching Material Publication Date',
        'ValidityStartDate': 'Teaching Material Validity Start Date',
        'ValidityEndDate': 'Teaching Material Validity End Date',
        'TeachingMaterials': 'Teaching Materials',
        'PhotoPath': 'Photo Path',
        'CVPathIta': 'CV Path Ita',
        'CVPathEn': 'CV Path Eng',
        'ShortBio': 'Short BIO',
        'ReceptionHours': 'Reception Hours',
        'ORCID': 'ORCID',
        'TeacherOtherData': 'Teacher Other Data',
        'TeacherBoard': 'Teacher Board',
        'TextType': 'Text Type',
        'ActivityStart': 'Activity Start',
        'ActivityEnd': 'Activity End',
        'ClassroomsTimetable': 'Classrooms Timetable',
        'ShowTimetable': 'Show Timetable',
        'Notes': 'Notes',
        'StudyActivityErogationLanguage': 'Erogation language',
        'CDSId': 'Course Id',
        'CDSCOD': 'Course Code',
        'CDSAcademicYear': 'Course Academic Year',
        'CDSName': 'Course Name',
        'CDSCourseClassName': 'Course Class Name',
        'CDSCourseInterClassDes': 'Course InterClass Description',
        'CDSLanguage': 'Language',
        'CDSDuration': 'Duration',
        'CDSVideo': 'Course Video',
        'CDSIntro': 'Course Intro',
        'CDSAdmission': 'Admission',
        'CDSGoals': 'Course objectives',
        'CDSJobOpportunities': 'Career opportunities',
        'CDSTaxes': 'Course Fees',
        'CDSScholarships': 'Scholarships',
        'CDSConcessions': 'Tax benefits',
        'CDSShortDescription': 'Course Short Description',
        'CDSStudyPlan': 'Course Study Plan',
        'CDSEnrollmentMode': 'Course Enrollment Mode',
        'CDSUrl': 'Course URL',
        'CDSUrlStatus': 'Course Url Status',
        'CDSExStudents': 'Course Ex Students',
        'CDSLinks': 'Course Links',
        'CDSSliders': 'Course Sliders',
        'CDSSeatsNumber': 'Seats Number',
        'StudentId': 'Student Id',
        'StudentName': 'Student Name',
        'StudentOrder': 'Student Order',
        'StudentProfile': 'Student Profile',
        'StudentLink': 'Student Link',
        'LinkId': 'Link Id',
        'LinkOrder': 'Link Order',
        'LinkDescription': 'Link Description',
        'Link': 'Link',
        'SliderId': 'Slider Id',
        'SliderOrder': 'Slider Order',
        'SliderDescription': 'Slider Description',
        'StudentPhoto': 'Student Photo',
        'StudyManifesto': 'Study manifesto',
        'DidacticRegulation': 'Didactic regulation',
        'TopicId': 'Topic Id',
        'TopicCod': 'Topic Cod',
        'TopicDescription': 'Topic Description',
        'ArticleNumber': 'Article Number',
        'ArticleId': 'Article Id',
        'ArticleTitle': 'Article Title',
        'ArticleDescription': 'Article Description',
        'Articles': 'Articles',
        'CdsArticle': 'Course Article',
        'Id': 'Id',
        'YearRegdidID':'Year Regdid ID',
        'ObjectId': 'Object Id',
        'ClassId': 'Class Id',
        'ObjectTitle': 'Object Title',
        'ObjectText': 'Object Text',
        'ObjectOrder': 'Object Order',
        'ObjectStatus': 'Object Status',
        'ArticleObjects': 'Article Objects',
        'Visible': 'Visible',
        'CdsObject': 'Course Object',
        'YearRegDidID': 'Year RegDidID',
        'ClassObjectId': 'Class Object Id',
        'StudyManifesto': 'Study manifesto',
        'DidacticRegulation': 'Didactic regulation',
        'RegPlanId': 'Reg Plan ID',
        'RelevanceCod': 'Relevance COD',
        'YearCoorteId': 'Year Coorte Id',
        'YearRegPlanId': 'Regulation Plan Id',
        'RegPlanDes': 'Regulation Plan Description',
        'DefFlg': 'Def Flg',
        'StatusCod': 'Status COD',
        'StatusDes': 'Status Description',
        'RegPlansPdrId': 'Regulation Plans Pdr ID',
        'RegPlansPdrCod': 'Regulation Plans Pdr COD',
        'RegPlansPdrDes': 'Regulation Plans Pdr Description',
        'RegPlansPdrCoorteIdYear': 'Regulation Plans Pdr Coorte Year ID',
        'RegPlansPdrYear': 'Regulation Plans Pdr Year',
        'FlgExpSegStu': 'Flg Exp Seg Stu',
        'PlanTabs': 'Plan Tabs',
        'PlanTabId': 'Plan Tab ID',
        'PlanTabDes': 'Plan Tab Description',
        'PlanTabCod': 'Plan Tab COD',
        'PdsCod': 'Pds COD',
        'PdsDes': 'Pds Description',
        'CommonFlg': 'Common Flag',
        'AfRequired': 'Required Educational Activities',
        'AfChoices': 'Choices Educational Activities',
        'Year': 'Year',
        'CycleDes': 'Cycle Description',
        'AfDescription': 'Activity Description',
        'AfId': 'Activity Id',
        'AfType': 'Activity Type',
        'AfScope': 'Activity Scope',
        'SettCod': 'Sett COD',
        'CreditValue': 'Credit Value',
        'ScopeId': 'Scope ID',
        'SceId': 'Choice ID',
        'SceDes': 'Choice Description',
        'ScopeDes': 'Scope Description',
        'MinUnt': 'Min Unt',
        'MaxUnt': 'Max Unt',
        'TypeSceCod': 'Choice Type COD',
        'TypeSceDes': 'Choice Type Des',
        'TypeRegSceCod': 'Choice Regulation Type COD',
        'TypeRegsceDes': 'Choice Regulation Type Description',
        'TypeUmRegsceCod': 'Choice UM Regulation Type COD',
        'VinSceDes': 'Constraint Description',
        'VinId': 'Constraint ID',
        'ElectiveCourses': 'Elective Courses',
        'TeachingSystem': 'Teaching system',
        'TeachingSystemYear': 'Teaching system year',
        'Required': 'Required',
        'Choices': 'Choices',
        'FilAnd': 'FilAnd',
        'NotFlg': 'Not Flag'
    },
    'it': {
        'RegDidId': 'ID Regolamento Didattico',
        'RegDidState': 'Stato del Regolamento Didattico',
        'CdSId': 'ID Corso di Studi',
        'CdSCod': 'Codice Corso di Studi',
        'AcademicYear': 'Anno Accademico',
        'CdSName': 'Nome Corso di Studi',
        'DepartmentId': 'ID Dipartimento',
        'DepartmentCod': 'Codice Dipartimento',
        'DepartmentName': 'Nome Dipartimento',
        'DepartmentNameShort': 'Nome Dipartimento Breve',
        'CourseType': 'Tipologia Corso',
        'CourseTypeDescription': 'Tipologia Corso',
        'CourseClassCod': 'Codice Classe Corso',
        'CourseClassName': 'Classe Corso',
        'CourseInterClassCod': 'Codice Interclasse Corso',
        'CourseInterClassDes': 'Interclasse Corso',
        'CdSLanguage': 'Lingua',
        'CdSDuration': 'Durata',
        'CdSECTS': 'ECTS',
        'CdSAttendance': 'Frequenza Obbligatoria',
        'CdSIntro': 'Descrizione',
        'CdSDoc': 'Documento',
        'CdSVideo': 'Video',
        'CdSGoals': 'Obiettivi',
        'CdSAccess': 'Accesso',
        'CdSAdmission': 'Ammissione',
        'CdSProfiles': 'Profili professionali e sbocchi occupazionali',
        'CdSFinalTest': 'Prova Finale',
        'CdSFinalTestMode': 'Modalità Prova Finale',
        'CdSSatisfactionSurvey': 'Soddisfazione e condizione occupazionale dei laureati (Almalaurea)',
        'JointDegree' : 'Titolo Congiunto',
        'LaboratoryId': 'Id Laboratorio',
        'LaboratoryName': 'Nome Laboratorio',
        'LaboratoryURL': 'Pagina Web',
        'LaboratoryEquipment': 'Strumentazione',
        'Interdepartmental': 'Interdipartimentale',
        'InfrastructureName': 'Infrastruttura di Riferimento',
        'ExtraDepartments': 'Altri dipartimenti',
        'Area': 'Ambito',
        'Dimension': 'Dimensione',
        'ScientificDirector': 'Responsabile Scientifico',
        'ScientificDirectorId': 'Id Responsabile Scientifico',
        'StudyPlanId': 'ID Piano di Studi',
        'StudyPlanName': 'Piano di Studi',
        'StudyPlanCod': 'Codice Piano di Studi',
        'StudyActivities': 'Attività Formative',
        'StudyActivityID': 'ID Attività Formativa',
        'StudyActivityCod': 'Codice Attività Formativa',
        'StudyActivityRegDidId': 'ID Regolamento Didattico',
        'StudyActivityName': 'Nome Attività Formativa',
        'StudyActivityCdSID': 'Id Corso di Studi',
        'StudyActivityCdSCod': 'Codice Corso di Studi',
        'StudyActivityYear': 'Anno Corso',
        'StudyActivityErogationYear': 'Anno di erogazione',
        'StudyActivitySemester': 'Semestre',
        'StudyActivityECTS': 'ECTS',
        'StudyActivitySSD': 'SSD',
        'StudyActivitySSDCod': 'Codice SSD',
        'StudyActivityCompulsory': 'Frequenza Obbligatoria',
        'StudyActivityCdSName': 'Corso di Studi',
        'StudyActivityTeachingUnitType': 'Tipologia Insegnamento',
        'StudyActivityTeacherID': 'Matricola Docente',
        'StudyActivityTeacherName': 'Docente',
        'StudyActivityContent': 'Contenuti',
        'StudyActivityProgram': 'Programma',
        'StudyActivityLearningOutcomes': 'Obiettivi Formativi',
        'StudyActivityMethodology': 'Metodologie Didattiche',
        'StudyActivityEvaluation': 'Metodi di Valutazione',
        'StudyActivityTextbooks': 'Testi di Riferimento',
        'StudyActivityWorkload': 'Carico di Lavoro',
        'StudyActivityElearningLink': 'Link Aula Virtuale',
        'StudyActivityElearningInfo': 'Info per l\'Accesso all\'Aula Virtuale',
        'StudyActivityPrerequisites': 'Prerequisiti',
        'StudyActivitiesModules': 'Suddivisione',
        'StudyActivityAA': 'Anno Accademico',
        'StudyActivityLanguage': 'Lingua',
        'StudyActivityRoot': 'Attività Formativa Principale',
        'StudyActivityBorrowedFrom': 'Mutuata da',
        'StudyActivitiesBorrowedFromThis': 'Mutuate da questa',
        'StudyActivityPartitionCod': 'Codice Partizione',
        'StudyActivityPartitionDescription': 'Descrizione Partizione',
        'SingleStudyActivityPartitionCod': 'Codice Singola Partizione ',
        'SingleStudyActivityPartitionDescription': 'Descrizione Singola Partizione',
        'StudyActivityPartitionType': 'Tipologia Partizione',
        'StudyActivityPartitionStart': 'Inizio della Partizione',
        'StudyActivityPartitionEnd': 'Fine della Partizione',
        'Teacher': 'Pagina Docente',
        'TeacherID': 'ID Docente',
        'TeacherName': 'Nome',
        'TeacherRole': 'Ruolo',
        'TeacherRoleDescription': 'Ruolo',
        'TeacherSSD': 'SSD',
        'TeacherDepartmentID': 'ID Dipartimento',
        'TeacherDepartmentCod': 'Codice Dipartimento',
        'TeacherDepartmentName': 'Dipartimento',
        'TeacherSSDCod': 'SSD',
        'TeacherSSDDescription': 'SSD',
        'TeacherCode': 'Codice Fiscale',
        'TeacherFirstName': 'Nome',
        'TeacherLastName': 'Cognome',
        'TeacherOffice': 'Ufficio',
        'TeacherOfficeReference': 'Riferimento Ufficio',
        'TeacherEmail': 'Posta Elettronica',
        'TeacherPEC': 'Posta Elettronica Certificata',
        'TeacherPrivateEmail': 'Posta Elettronica Privata',
        'TeacherTelOffice': 'Telefono Ufficio',
        'TeacherTelCelOffice': 'Telefono Cellulare Ufficio',
        'TeacherTelCel': 'Telefono Cellulare',
        'TeacherTelDomicile': 'Telefono Domicilio',
        'TeacherTelResidence': 'Telefono Residenza',
        'TeacherFax': 'Fax',
        'TeacherSkype': 'Skype',
        'TeacherWebSite': 'URL Sito WEB',
        'TeacherCV': 'Curriculum Vitae',
        'TeacherFunctions': 'Ruoli Amministrativi',
        'Office': 'Ufficio',
        'OfficeReference': 'Riferimento Ufficio',
        'Email': 'Posta Elettronica',
        'PEC': 'Posta Elettronica Certificata',
        'PrivateEmail': 'Posta Elettronica Privata',
        'TelOffice': 'Telefono Ufficio',
        'TelCelOffice': 'Telefono Cellulare Ufficio',
        'TelCel': 'Telefono Cellulare',
        'TelDomicile': 'Telefono Domicilio',
        'TelResidence': 'Telefono Residenza',
        'Fax': 'Fax',
        'Skype': 'Skype',
        'WebSite': 'URL Sito WEB',
        'CV': 'Curriculum Vitae',
        'Contacts': 'Contatti',
        'ContactType': 'Tipo Contatto',
        'Contact': 'Contatto',
        'Function': 'Funzione',
        'Structure': 'Struttura',
        'Role': 'Ruolo',
        'RoleDescription': 'Ruolo',
        'ID': 'ID',
        'IdErc1': 'Id Erc1',
        'IdErc0': 'IdErc0',
        'IdAster1': 'Id Aster 1',
        'IdAster2' : 'Id Aster 2',
        'Name': 'Nome',
        'RGroupID': 'ID Gruppo di Ricerca',
        'RGroupName': 'Nome Gruppo di Ricerca',
        'RGroupDescription': 'Descrizione Gruppo di Ricerca',
        'RLineID': 'ID Linea di Ricerca',
        'RLineDescription': 'Descrizione Linea di Ricerca',
        'RLineResults': 'Risultati Linea di Ricerca',
        'RLineERC0Id': 'ID Linea di Ricerca ERC0',
        'RLineERC0Name': 'Nome Linea di Ricerca ERC0',
        'RLineERC1Id': 'ID Linea di Ricerca ERC1',
        'RLineERC1Name': 'Nome Linea di Ricerca ERC1',
        'DepartmentID': 'ID Dipartimento',
        'PhdCdsCOD': 'Codice Corso di Studi',
        'PhdCdsName': 'Nome Corso di Studi',
        'PhdRegID': 'ID Regolamento Dottorato',
        'PhdRegCOD': 'Codice Regolamento Dottorato',
        'PhdCdSDuration': 'Durata',
        'PhdCdSECTS': 'ECTS',
        'PhdCdSAttendance': 'Frequenza Obbligatoria',
        'CourseName': 'Nome Corso',
        'CycleNumber': 'Numero Ciclo',
        'StudyPlanCOD': 'Codice Piano di Studi',
        'StudyPlanDes': 'Descrizione Piano di Studi',
        'FUNZIONI': 'Funzioni',
        'COMPETENZE': 'Competenze',
        'SBOCCHI': 'Sbocchi',
        'StructureCod': 'Codice Struttura',
        'StructureTypeName': 'Tipologia',
        'StructureName': 'Nome',
        'StructureTypeCOD': 'Tipologia',
        'StructureFatherId': 'Struttura Riferimento',
        'StructureFatherName': 'Struttura Riferimento',
        'StructureEmail': 'Email',
        'StructurePec': 'Pec',
        'StructureTfr': 'Telefono',
        'StructurePersonnelFunctions': 'Personale Amministrativo',
        'LaboratoryId': 'ID',
        'CompletionReferentName': 'Referente Compilazione',
        'CompletionReferentId': 'Referente Compilazione',
        'ScientificDirectorId': 'Responsabile Scientifico',
        'ScientificDirectorName': 'Responsabile Scientifico',
        'LaboratoryName': 'Nome',
        'LaboratoryAcronym': 'Acronimo',
        'LaboratoryLogo': 'Logo',
        'DepartmentReferentId': 'Dipartimento di Riferimento',
        'DepartmentReferentCod': 'Codice Dipartimento di Riferimento',
        'DepartmentReferentName': 'Dipartimento di Riferimento',
        'DepartmentURL': 'URL',
        'StructureURL': 'URL',
        'StructureChilds': 'Sotto-strutture',
        'LaboratoryScope': 'Ambito',
        'LaboratoryServicesScope': 'Finalità  dei servizi',
        'LaboratoryResearchScope': 'Finalità Ricerca',
        'LaboratoryTeachingScope': 'Finalità Didattica',
        'LaboratoryActivities': 'Attività',
        'LaboratoryErc1': 'Erc 1',
        'LaboratoryResearchPersonnel': 'Finalità di ricerca',
        'LaboratoryTechPersonnel': 'Personale Tecnico',
        'LaboratoryOfferedServices': 'Servizi Offerti',
        'LaboratoryLocation': 'Ubicazione',
        'LocationBuilding': 'Edificio',
        'LocationFloor': 'Piano',
        'LocationNotes': 'Note',
        'ServiceName': 'Nome',
        'ServiceDescription': 'Descrizione',
        'TechPersonnelID': 'ID',
        'TechPersonnelName': 'Nome',
        'TechPersonnelRole': 'Ruolo',
        'ResearchPersonnelID': 'ID',
        'ResearchPersonnelName': 'Nome',
        'LaboratoryErc1Cod': 'Codice Erc1',
        'LaboratoryErc1Description': 'Descrizione Erc1',
        'LaboratoryErc0Cod': 'Codice Erc0',
        'LaboratoryErc0Description': 'Descrizione Erc0',
        'LaboratoryActivityType': 'Tipologia Attività',
        'Description': 'Descrizione',
        'PublicationId': 'ID',
        'PublicationTitle': 'Titolo',
        'PublicationAbstract': 'Abstract',
        'PublicationCollection': 'Collection',
        'PublicationCommunity': 'Tipologia',
        'Publication': 'Pubblicazione',
        'PublicationLabel': 'Tipologia Pubblicazione',
        'PublicationContributors': 'Tutti gli autori',
        'PublicationAuthors': 'Autori Unical',
        'PublicationYear': 'Anno di Pubblicazione',
        'AuthorId': 'ID',
        'AuthorName': 'Nome',
        'CommunityId': 'Id',
        'CommunityName': 'Nome',
        'PublicationReferenceAuthor': 'Autore Principale',
        'Erc1List': 'Lista Erc1 Associati',
        'Erc2List': 'Lista Erc2 Associati',
        'PublicationUrl': 'Url Pubblicazione',
        'TeacherCVFull':'CV completo',
        'TeacherCVShort':'CV breve',
        'Teachers': 'Docenti',
        'RLineErc2ID': 'Codice Erc2',
        'RLineErc2Name': 'Nome Erc2',
        'RYear': 'Anno di ricerca',
        'RLineAster2ID': 'ID Aster2',
        'RLineAster2Name': 'Nome Aster2',
        'Hours': 'Ore',
        'Cover': 'Peso',
        'CodErc2': 'Codice Erc2',
        'RLineAster2Id': 'Codice Aster2',
        'RLineAster2Name': 'Nome Aster2',
        'StructureMission': 'Obiettivo Struttura',
        'InfrastructureId' : 'Id Infrastruttura',
        'InfrastructureDescription': 'Struttura di Riferimento',
        'LaboratoryScopes': 'Finalità Laboratorio',
        'ScopeID': 'ID Finalità',
        'ScopeDescription': 'Descrizione Finalità',
        'PatentId': 'Id Brevetto',
        'PatentInitialTRL': 'Initial TRL',
        'PatentUpdatedTRL': 'Updated TRL',
        'PatentEnhancement': 'Valorizzazione',
        'PatentUniqueId': 'Id Univoco Brevetto',
        'PatentTitle': 'Titolo Brevetto',
        'PatentImage': 'Immagine Brevetto',
        'PatentAbstract': 'Abstract Brevetto',
        'PatentUrlKnowledgeShare': 'Scheda Knowledge Share',
        'PatentTechAreaId': 'Area Tecnologica Brevetto',
        'PatentAreaDescription': 'Area Tecnologica',
        'PatentInventors': 'Inventori Brevetto',
        'SpinoffId': 'Id Spinoff',
        'SpinoffPIva': 'P. Iva Spinoff',
        'SpinoffAgencyName': 'Nome Azienda Spinoff',
        'SpinoffImage': 'Immagine Spinoff',
        'SpinoffDescription': 'Descrizione Spinoff',
        'SpinoffUnicalReferent': 'Referente Unical Spinoff',
        'SpinoffUnicalReferentId': 'Matricola Referente Unical',
        'TechAreaId': 'Id Area Tecnologica Spinoff',
        'TechAreaDescription': 'Area Tecnologica',
        'SpinoffAgencyUrl': 'Url Azienda Spinoff',
        'IsSpinoff': 'Spinoff',
        'IsStartup': 'Startup',
        'PersonFunctions': ' Funzioni Persona',
        'ProjectId': 'Id Progetto',
        'TerritorialScopeId': 'Id Ambito Territoriale',
        'TerritorialScopeDescription': 'Ambito Territoriale',
        'TypeProgramId': 'Id Tipologia Programma',
        'TypeProgramDescription': 'Programma',
        'ProjectTitle': 'Titolo Progetto',
        'ProjectDescription': 'Descrizione',
        'ProjectAbstract': 'Abstract',
        'ProjectImage': 'Immagine Progetto',
        'ScientificDirectors': 'Responsabili Scientifici',
        'ProjectYear': 'Anno Avvio',
        'ProjectDepartmentId': 'Dipartimento Progetto',
        'FunctionDescription': 'Descrizione Funzione',
        'FunctionCod': 'Codice Funzione',
        'AreaCds': 'Area Cds',
        'CdsUrl': 'Url Cds',
        'Researchers': 'Ricercatori',
        'ResearcherId': 'Matricola Ricercatore',
        'ResearcherName': 'Nome Ricercatore',
        'CF': 'Codice Fiscale',
        'MasterTitle': 'Titolo Master',
        'HighFormationTypeId': 'Alta Formazione ID',
        'HighFormationErogationMode': 'Modalità di erogazione',
        'HighFormationHours': 'Ore',
        'HighFormationMonths': 'Mesi',
        'HighFormationCourseStructure': 'Sede Corso',
        'HighFormationMinParticipants': 'Numero Minimo Partecipanti',
        'HighFormationMaxParticipants': 'Numero Massimo Partecipanti',
        'ListenersAccepted': 'Uditori Ammessi',
        'MaxListeners': 'Numero Massimo Uditori',
        'AdmissionRequirements': 'Requisiti di Ammissione',
        'TitleIssued': 'Titolo Rilasciato',
        'DoubleTitle': 'Doppio Titolo',
        'SubscriptionFee': 'Quota di Iscrizione',
        'ListenersFee': 'Quota di Uditori',
        'WorkFunction': 'Funzione Lavoro',
        'FormationObjectivesSummerSchool': 'Obiettivi Formativi High School',
        'Skills': 'Competenze',
        'JobOpportunities': 'Sbocchi Occupazionali',
        'CourseObjectives': 'Obiettivi Formativi Corso',
        'FinalTestMode': 'Modalità Svolgimento Prova Finale',
        'NumModules': 'Numero Moduli',
        'Internship': 'Stage/Tirocinio',
        'InternshipHours': 'Ore Stage/Tirocinio',
        'InternshipCFU': 'CFU Stage/Tirocinio',
        'InternshipMonths': 'Mesi Stage/Tirocinio',
        'TypeCompaniesInternship': 'Tipologia Aziende Enti Tirocinio',
        'ContentTimesCriteriaCFU': 'Contenuti, Tempi e Criteri CFU',
        'ProjectWork': 'Progetto di Lavoro',
        'HighFormationMasterPartners': 'Partner del Master',
        'PartnerDenomination': 'Denominazione del Partner',
        'PartnerURL': 'Sito Web del Partner',
        'PartnerType': 'Tipologia del Partner',
        'HighFormationErogationModeDescription': 'Descrizione Modalità Erogazione',
        'HighFormationMasterSelectionModes': 'Modalità di Selezione Master',
        'SelectionType': 'Tipologia Selezione',
        'SelectionId': 'Id Modalita Selezione',
        'HighFormationMasterInternalCouncil': 'Consiglio Scientifico Interno',
        'HighFormationMasterYear': ' Anno Accademico',
        'PersonId': 'Matricola Persona',
        'PersonName': 'Nome',
        'HighFormationMasterExternalCouncil': 'Consiglio Scientifico Esterno',
        'Institution': 'Ente',
        'PartnerId': 'Id Partner',
        'HighFormationMasterTeachingPlans': 'Piani Didattici',
        'TeachingPlanCFU': 'CFU',
        'TeachingPlanFinalTest': 'Prova Finale',
        'TeachingPlanSSD': 'SSD',
        'TeachingPlanModule': 'Modulo',
        'TeachingPlanHours': 'Ore',
        'HighFormationMasterTeachingAssignments': 'Alta Formazione Incarichi Didattici',
        'TeachingAssignmentsModule': 'Modulo',
        'TeachingAssignmentsHours': 'Ore',
        'TeachingAssignmentsTeachers': 'Docenti',
        'TeachingAssignmentsQualification': 'Qualifica',
        'TeachingAssignmentsInstitution': 'Ente',
        'TeachingAssignmentsType': 'Tipologia',
        'Aster1List': 'Lista Aster1',
        'Aster2List': 'Lista Aster2',
        'OtherData': 'Altri Dati',
        'OfficesData': 'Altri Dati Ufficio',
        'DirectorId': 'Matricola Coordinatore',
        'DirectorName': 'Coordinatore',
        'DeputyDirectorId': 'Matricola Coordinatore Vicario',
        'DeputyDirectorName': 'Coordinatore Vicario',
        'SeatsNumber': 'Numero Posti',
        # 'RegistrationMode': 'Modalità Iscrizione',
        'Order': 'Ordine',
        'OfficeName': 'Nome Ufficio',
        'OfficeDirector': 'Matricola Riferimento Ufficio',
        'OfficeDirectorName': 'Nome Riferimento Ufficio',
        'Building': 'Edificio',
        'Floor': 'Piano',
        'Timetables': 'Orari',
        'OnlineCounter': 'Sportello Online',
        'StudyActivityTeachingUnitTypeCod': 'Codice Tipologia Insegnamento',
        'StudyActivityInterclassTeachingUnitTypeCod': 'Codice Tipologia Insegnamento Interclasse',
        'StudyActivityInterclassTeachingUnitType': 'Tipologia Insegnamento Interclasse',
        'ActivityType': 'Tipologia Attività Didattica',
        'StudyActivityHours': 'Ore Attività Didattica',
        'StudyActivityAcademicYear': 'Anno Accademico Attività Didattica',
        'StudyActivityDevelopmentGoal': 'Obiettivo Attività Didattica',
        'StudyActivityModalities': 'Modalità Attività Didattica',
        'ModalityActivityId': 'Id Modalità Attività Didattica',
        'ModalityActivityCod': 'Codice Modalità Attività Didattica',
        'ModalityActivityDescription': 'Descrizione Modalità Attività Didattica',
        'StudyActivityPartitionCod': 'Codice Partizionamento',
        'StudyActivityPartitionDes': 'Descrizione Partizionamento',
        'StudyActivityExtendedPartitionCod': 'Codice Esteso Partizionamento',
        'StudyActivityExtendedPartitionDes': 'Descrizione Estesa Partizionamento',
        'HighFormationLanguage': 'Lingua',
        'ProfileId': 'Profilo',
        'ProfileDescription': 'Descrizione Profilo',
        'ProfileShortDescription': 'Descrizione Breve Profilo',
        'HighFormationTypeDescription': 'Alta Formazione Descrizione Tipo Corso',
        'HighFormationErogationModeDescription': 'Alta Formazione Descrizione Modalità Erogazione',
        'ActivityName': "Nome Attività",
        'SSD': "SSD",
        'Cycle': "Ciclo",
        'CFU': "CFU",
        'ActivityType': "Tipologia Attività",
        'ReferentPhd': "Dottorato di Riferimento",
        'ReferentStructureId': "Id Struttura",
        'ReferentStructureName': "Struttura",
        'ActivityContents': "Contenuti Attività",
        'Prerequisities': "Prerequisiti",
        'MinStudents': "Numero Minimo Studenti",
        'MaxStudents': "Numero Massimo Studenti",
        'FinalTest': "Test Finale",
        'FinalTestMode': "Modalità Test Finale",
        'MainTeachers': 'Docenti Principali',
        'OtherTeachers': 'Altri Docenti',
        'HighFormationErogationModeDescription': 'Modalità di erogazione',
        'ErogationMode': 'Modalità Erogazione',
        'Departments': 'Dipartimenti',
        'Roles': 'Ruoli',
        'Context': 'Inquadramento',
        'Priority': 'Priorità',
        'ContextDescription': 'Descrizione Inquadramento',
        'OfficeBuilding': 'Edificio',
        'StudyActivityGroups': 'Gruppi Attività',
        'StudyActivityPdsCod': 'Codice Pds Attività',
        'StudyActivityPdsDes': 'Descrizione Pds Attività',
        'StudyActivityFather': 'Attività Formativa Padre',
        'StudyActivityFatherName': 'Nome Attività Formativa Padre',
        'StudyActivityFatherCode': 'Codice Attività Formativa Padre',
        'Title': 'Titolo',
        'Text': 'Testo',
        'TextUrl': 'URL',
        'Order': 'Ordine',
        'Active': 'Attivo',
        'PublicationDate': 'Data Pubblicazione',
        'ValidityStartDate': 'Data Inizio Validità',
        'ValidityEndDate': 'Data Fine Validità',
        'TeachingMaterials': 'Materiale Didattico',
        'PhotoPath': 'Photo Path',
        'CVPathIta': 'CV Path Ita',
        'CVPathEn': 'CV Path Eng',
        'ShortBio': 'Breve BIO',
        'ReceptionHours': 'Orario Ricevimento',
        'ORCID': 'ORCID',
        'TeacherOtherData': 'Docente Altri Dati',
        'TeacherBoard': 'Bacheca Docente',
        'TextType': 'Tipo Testo',
        'ActivityStart': 'Avvio Attività',
        'ActivityEnd': 'Fine Attività',
        'ClassroomsTimetable': 'Orario',
        'ShowTimetable': 'Mostra Orario',
        'Notes': 'Note',
        'StudyActivityErogationLanguage': 'Lingua erogazione',
        'CDSId': 'Id Cds',
        'CDSCOD': 'Codice Cds',
        'CDSAcademicYear': 'Anno Accademico',
        'CDSName': 'Nome',
        'CDSCourseClassName': 'Classe Corso',
        'CDSCourseInterClassDes': 'Interclasse',
        'CDSLanguage': 'Lingua',
        'CDSDuration': 'Durata',
        'CDSVideo': 'Video',
        'CDSIntro': 'Descrizione',
        'CDSAdmission': 'Ammissione',
        'CDSGoals': 'Obiettivi del corso',
        'CDSJobOpportunities': 'Sbocchi professionali',
        'CDSTaxes': 'Tasse',
        'CDSScholarships': 'Borse di studio',
        'CDSConcessions': 'Agevolazioni',
        'CDSShortDescription': 'Breve descrizione',
        'CDSStudyPlan': 'Piano di studio',
        'CDSEnrollmentMode': 'Iscrizione',
        'CDSUrl': 'Url',
        'CDSUrlStatus': 'Stato Url',
        'CDSExStudents': 'Ex Studenti',
        'CDSLinks': 'Link',
        'CDSSliders': 'Slider',
        'CDSSeatsNumber': 'Numero posti',
        'StudentId': 'Id',
        'StudentName': 'Nome',
        'StudentOrder': 'Ordine',
        'StudentProfile': 'Profilo',
        'StudentLink': 'Link',
        'LinkId': 'Id',
        'LinkOrder': 'Ordine',
        'LinkDescription': 'Descrizione',
        'Link': 'Link',
        'SliderId': 'Id',
        'SliderOrder': 'Ordine',
        'SliderDescription': 'Descrizione',
        'StudentPhoto': 'Foto Studente',
        'StudyManifesto': 'Manifesto degli studi',
        'DidacticRegulation': 'Regolamento didattico',
        'TopicId': 'Id Topic',
        'TopicCod': 'Codice Topic',
        'TopicDescription': 'Descrizione Topic',
        'ArticleNumber': 'Numero Articolo',
        'ArticleId': 'Id Articolo',
        'ArticleTitle': 'Titolo Articolo',
        'ArticleDescription': 'Descrizione Articolo',
        'Articles': 'Articoli',
        'CdsArticle': 'Articolo Cds',
        'Id': 'Id',
        'YearRegdidID':'Anno Regolamento Didattico',
        'ObjectId': 'Id Oggetto',
        'ClassId': 'Id Classe Oggetto',
        'ObjectTitle': 'Title',
        'ObjectText': 'Testo',
        'ObjectOrder': 'Order',
        'ObjectStatus': 'Status',
        'ArticleObjects': 'Oggetti Articoli',
        'Visible': 'Visibile',
        'CdsObject': 'Oggetto Cds',
        'YearRegDidID': 'Anno regolamento didattico',
        'ClassObjectId': 'Id Classe Oggetto',
        'StudyManifesto': 'Manifesto degli studi',
        'DidacticRegulation': 'Regolamento didattico',
        'TeachingSystem': 'Ordinamento didattico',
        'TeachingSystemYear': 'Anno ordinamento didattico',
        'RegPlanId': 'ID Regolamento',
        'RelevanceCod': 'COD Regolamento',
        'YearCoorteId': 'ID Anno Coorte',
        'YearRegPlanId': 'ID Anno Regolamento',
        'RegPlanDes': 'Descrizione Regolamento',
        'DefFlg': 'Flag Def',
        'StatusCod': 'COD Stato',
        'StatusDes': 'Descrizione Stato',
        'RegPlansPdrId': 'ID Regolamento PDR',
        'RegPlansPdrCod': 'Regolamento PDR COD',
        'RegPlansPdrDes': 'Descrizione Regolamento PDR',
        'RegPlansPdrCoorteIdYear': 'ID Anno Coorte Regolamento PDR',
        'RegPlansPdrYear': 'Anno Regolamento PDR',
        'FlgExpSegStu': 'Flag Esposizione Segmento Studente',
        'PlanTabs': 'Schede Piano',
        'PlanTabId': 'ID Scheda Piano',
        'PlanTabDes': 'Descrizione Scheda Piano',
        'PlanTabCod': 'COD Scheda Piano',
        'PdsCod': 'COD PDS',
        'PdsDes': 'Descrizione PDS',
        'CommonFlg': 'Flag Comune',
        'AfRequired': 'Attività Formative Obbligatorie',
        'AfChoices': 'Attività Formative a Scelta',
        'Year': 'Anno',
        'CycleDes': 'Descrizione Ciclo',
        'AfDescription': 'Descrizione Attività',
        'AfId': 'ID Attività',
        'AfType': 'Tipo Attività',
        'AfScope': 'Ambito Attività',
        'SettCod': 'COD Sett',
        'CreditValue': 'Valore Crediti',
        'ScopeId': 'ID Ambito',
        'SceId': 'ID Scelta',
        'SceDes': 'Descrizione Scelta',
        'ScopeDes': 'Descrizione Ambito',
        'MinUnt': 'Min Unt',
        'MaxUnt': 'Max Unt',
        'TypeSceCod': 'COD Tipo Scelta',
        'TypeSceDes': 'Descrizione Tipo Scelta',
        'TypeRegSceCod': 'Tipo Regolamento Scelta COD',
        'TypeRegsceDes': 'Descrizione Regolamento Scelta',
        'TypeUmRegsceCod': 'Regolamento UM Scelta COD',
        'VinSceDes': 'Descrizione Vincolo',
        'VinId': 'ID Vincolo',
        'ElectiveCourses': 'Corsi a scelta',
        'Required': 'Required',
        'Choices': 'Choices',
        'FilAnd': 'FilAnd',
        'NotFlg': 'Not Flag'
    }
}
