
"""
Django settings for ricerca project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""


import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = '82^w&ie47r^!c8f6yeui@#6e*myi*o4sf3^u*o7+#3qk!tn^=s'
ALLOWED_HOSTS = ['*']
ADMIN_PATH = 'test_admin'
INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'accounts.apps.AccountsConfig',
    'rest_framework',
    'ricerca_app',
    # 'silk',
    # 'ricerca_app.apps.RicercaAppConfig',
]
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    #'silk.middleware.SilkyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # SameSite Cookie workaround
    #  'djangosaml2.middleware.SamlSessionMiddleware'
]

# GETTEXT LOCALIZATION
MIDDLEWARE.append('django.middleware.locale.LocaleMiddleware')
LOCALE_PATHS = (
    os.path.join(BASE_DIR, "locale"),
)
#

ROOT_URLCONF = 'ricerca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ricerca.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

LABEL_MAPPING = {
    'en': {
        'RegDidId': 'Teaching Regulation ID',
        'CdSId': 'Course of Study ID',
        'AcademicYear': 'Academic Year',
        'CdSName': 'Course of Study Name',
        'DepartmentId': 'Department ID',
        'DepartmentName': 'Department Name',
        'CourseType': 'Course Type',
        'CourseClassId': 'Course Class ID',
        'CourseClassName': 'Course Class Name',
        'CdSLanguage': 'Language',
        'CdSDuration': 'Duration',
        'CdSECTS': 'ECTS',
        'CdSAttendance': 'Attendance',
        'CdSIntro': 'Intro',
        'CdSGoals': 'Goals',
        'CdSAccess': 'Access',
        'CdSAdmission': 'Admission',
        'CdSProfiles': 'Profiles',
        'CdSFinalTest': 'Final Test',
        'CdSFinalTestMode': 'Final Test Mode',
        'CdSSatisfactionSurvey': 'Satisfaction Survey',
        'StudyPlanId': 'Study Plan ID',
        'StudyPlanName': 'Study Plan Name',
        'StudyPlanCod': 'Study Plan Code',
        'StudyActivityID': 'Study Activity ID',
        'StudyActivityName': 'Study Activity Name',
        'StudyActivityCdSID': 'Course of Study ID',
        'StudyActivityYear': 'Year',
        'StudyActivitySemester': 'Semester',
        'StudyActivityECTS': 'ECTS',
        'StudyActivitySSD': 'Description',
        'StudyActivityCompulsory': 'Compulsory',
        'StudyActivityCdSName': 'Course of Study Name',
        'StudyActivityTeachingUnitType': 'Teaching Unit Type',
        'StudyActivityTeacherID': 'Teacher ID',
        'StudyActivityTeacherName': 'Teacher Name',
        'StudyActivityContent': 'Content',
        'StudyActivityProgram': 'Program',
        'StudyActivityLearningOutcomes': 'Learning Outcomes',
        'StudyActivityMethodology': 'Methodology',
        'StudyActivityEvaluation': 'Evaluation',
        'StudyActivityTextbooks': 'Textbooks',
        'StudyActivityWorkload': 'Workload',
        'StudyActivityElearningLink': 'E-Learning Link',
        'StudyActivityElearningInfo': 'E-Learning Info',
        'StudyActivityPrerequisites': 'Prerequisites',
        'StudyActivitiesModules': 'Modules',
        'StudyActivityAA': 'Academic Year',
        'StudyActivityLanguage': 'Language',
        'TeacherID': 'Teacher ID',
        'TeacherName': 'Teacher Name',
        'TeacherRole': 'Role',
        'TeacherSSD': 'SSD',
        'TeacherDepartmentID': 'Department ID',
        'TeacherDepartmentName': 'Department Name',
        'TeacherSSDCod': 'SSD Code',
        'TeacherSSDDescription': 'SSD Description',
        'TeacherCode': 'Teacher Code',
        'TeacherFirstName': 'First Name',
        'TeacherLastName': 'Last Name',
        'TeacherEmail': 'Email',
        'TeacherTel': 'Phone Number',
        'TeacherOffice': 'Office',
        'RGroupID': 'Group ID',
        'RGroupName': 'Group Name',
        'RGroupDescription': 'Group Description',
        'R&SLineID': 'Research Line ID',
        'R&SLineDescription': 'Description',
        'R&SLineResults': 'Results',
        'R&SLineERC0Id': 'ERC0 ID',
        'R&SLineERC0Name': 'ERC0 Name',
        'DepartmentID': 'Department ID',
        'DoctorateCdsCOD': 'Course of Study Code',
        'DoctorateCdsName': 'Course of Study Name',
        'DoctorateRegID': 'Doctorate Regulation ID',
        'DoctorateRegCOD': 'Doctorate Regulation Code',
        'DoctorateCdSDuration': 'Duration',
        'DoctorateCdSECTS': 'ECTS',
        'DoctorateCdSAttendance': 'Attendance',
        'CourseName': 'Course Name',
        'CycleNumber': 'Cycle Number',
        'StudyPlanCOD': 'Study Plan Code',
        'StudyPlanDes': 'Study Plan Description',
        'FUNZIONI': 'Tasks',
        'COMPETENZE': 'Skills',
        'SBOCCHI': 'Job Opportunities',
    },
    'it': {
        'RegDidId': 'ID Regolamento Didattico',
        'CdSId': 'ID Corso di Studi',
        'AcademicYear': 'Anno Accademico',
        'CdSName': 'Nome Corso di Studi',
        'DepartmentId': 'ID Dipartimento',
        'DepartmentName': 'Nome Dipartimento',
        'CourseType': 'Tipologia Corso',
        'CourseClassId': 'ID Classe Corso',
        'CourseClassName': 'Nome Classe Corso',
        'CdSLanguage': 'Lingua Corso di Studi',
        'CdSDuration': 'Durata Corso di Studi',
        'CdSECTS': 'ECTS Corso di Studi',
        'CdSAttendance': 'Frequenza Obbligatoria',
        'CdSIntro': 'Descrizione',
        'CdSGoals': 'Obiettivi',
        'CdSAccess': 'Accesso',
        'CdSAdmission': 'Ammissione',
        'CdSProfiles': 'Profili',
        'CdSFinalTest': 'Test Finale',
        'CdSFinalTestMode': 'Modalità Test Finale',
        'CdSSatisfactionSurvey': 'Codice Accesso Indagine Almalaurea',
        'StudyPlanId': 'ID Piano di Studi',
        'StudyPlanName': 'Nome Piano di Studi',
        'StudyPlanCod': 'Codice Piano di Studi',
        'StudyActivityID': 'ID Attività Formativa',
        'StudyActivityName': 'Nome Attività Formativa',
        'StudyActivityCdSID': 'Codice Corso di Studi',
        'StudyActivityYear': 'Anno Corso',
        'StudyActivitySemester': 'Semestre',
        'StudyActivityECTS': 'ECTS',
        'StudyActivitySSD': 'Descrizione',
        'StudyActivityCompulsory': 'Frequenza Obbligatoria',
        'StudyActivityCdSName': 'Nome Corso di Studi',
        'StudyActivityTeachingUnitType': 'Tipologia Insegnamento',
        'StudyActivityTeacherID': 'Matricola Docente',
        'StudyActivityTeacherName': 'Nome Docente',
        'StudyActivityContent': 'Contenuti',
        'StudyActivityProgram': 'Programma',
        'StudyActivityLearningOutcomes': 'Obiettivi Formativi',
        'StudyActivityMethodology': 'Metodologie Didattiche',
        'StudyActivityEvaluation': 'Metodi di Valutazione',
        'StudyActivityTextbooks': 'Testi di Riferimento',
        'StudyActivityWorkload': 'Carico di Lavoro',
        'StudyActivityElearningLink': 'Link Aula Virtuale',
        'StudyActivityElearningInfo': 'Info per l\'Accesso all\'Aula Virtuale',
        'StudyActivityPrerequisites': 'Prerequisiti',
        'StudyActivitiesModules': 'Moduli',
        'StudyActivityAA': 'Anno Accademico',
        'StudyActivityLanguage': 'Lingua',
        'TeacherID': 'ID Docente',
        'TeacherName': 'Nome Docente',
        'TeacherRole': 'Ruolo Docente',
        'TeacherSSD': 'Codice SSD',
        'TeacherDepartmentID': 'ID Dipartimento',
        'TeacherDepartmentName': 'Nome Dipartimento',
        'TeacherSSDCod': 'Codice SSD',
        'TeacherSSDDescription': 'Descrizione SSD',
        'TeacherCode': 'Codice Fiscale',
        'TeacherFirstName': 'Nome',
        'TeacherLastName': 'Cognome',
        'TeacherEmail': 'Email',
        'TeacherTel': 'Telefono',
        'TeacherOffice': 'Ufficio',
        'RGroupID': 'ID Gruppo di Ricerca',
        'RGroupName': 'Nome Gruppo di Ricerca',
        'RGroupDescription': 'Descrizione Gruppo di Ricerca',
        'R&SLineID': 'ID Linea di Ricerca',
        'R&SLineDescription': 'Descrizione Linea di Ricerca',
        'R&SLineResults': 'Risultati Linea di Ricerca',
        'R&SLineERC0Id': 'ID Linea di Ricerca ERC0',
        'R&SLineERC0Name': 'Nome Linea di Ricerca ERC0',
        'DepartmentID': 'ID Dipartimento',
        'DoctorateCdsCOD': 'Codice Corso di Studi',
        'DoctorateCdsName': 'Nome Corso di Studi',
        'DoctorateRegID': 'ID Regolamento Dottorato',
        'DoctorateRegCOD': 'Codice Regolamento Dottorato',
        'DoctorateCdSDuration': 'Durata',
        'DoctorateCdSECTS': 'ECTS',
        'DoctorateCdSAttendance': 'Frequenza Obbligatoria',
        'CourseName': 'Nome Corso',
        'CycleNumber': 'Numero Ciclo',
        'StudyPlanCOD': 'Codice Piano di Studi',
        'StudyPlanDes': 'Descrizione Piano di Studi',
        'FUNZIONI': 'Funzioni',
        'COMPETENZE': 'Competenze',
        'SBOCCHI': 'Sbocchi',
    }
}

DEBUG=True
