# Generated by Django 4.2.16 on 2024-10-21 11:17

import cds_brochure.settings
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generics.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CdsBrochure",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "aa",
                    models.PositiveIntegerField(blank=True, db_column="AA", null=True),
                ),
                (
                    "cds_cod",
                    models.CharField(
                        blank=True, db_column="CDS_COD", max_length=100, null=True
                    ),
                ),
                (
                    "num_posti",
                    models.IntegerField(blank=True, db_column="NUM_POSTI", null=True),
                ),
                (
                    "descrizione_corso_it",
                    models.TextField(
                        blank=True, db_column="DESCRIZIONE_CORSO_IT", null=True
                    ),
                ),
                (
                    "descrizione_corso_en",
                    models.TextField(
                        blank=True, db_column="DESCRIZIONE_CORSO_EN", null=True
                    ),
                ),
                (
                    "accesso_corso_it",
                    models.TextField(
                        blank=True, db_column="ACCESSO_CORSO_IT", null=True
                    ),
                ),
                (
                    "accesso_corso_en",
                    models.TextField(
                        blank=True, db_column="ACCESSO_CORSO_EN", null=True
                    ),
                ),
                (
                    "obiettivi_corso_it",
                    models.TextField(
                        blank=True, db_column="OBIETTIVI_CORSO_IT", null=True
                    ),
                ),
                (
                    "obiettivi_corso_en",
                    models.TextField(
                        blank=True, db_column="OBIETTIVI_CORSO_EN", null=True
                    ),
                ),
                (
                    "sbocchi_professionali_it",
                    models.TextField(
                        blank=True, db_column="SBOCCHI_PROFESSIONALI_IT", null=True
                    ),
                ),
                (
                    "sbocchi_professionali_en",
                    models.TextField(
                        blank=True, db_column="SBOCCHI_PROFESSIONALI_EN", null=True
                    ),
                ),
                (
                    "tasse_contributi_esoneri_it",
                    models.TextField(
                        blank=True, db_column="TASSE_CONTRIBUTI_ESONERI_IT", null=True
                    ),
                ),
                (
                    "tasse_contributi_esoneri_en",
                    models.TextField(
                        blank=True, db_column="TASSE_CONTRIBUTI_ESONERI_EN", null=True
                    ),
                ),
                (
                    "borse_studio_it",
                    models.TextField(
                        blank=True, db_column="BORSE_STUDIO_IT", null=True
                    ),
                ),
                (
                    "borse_studio_en",
                    models.TextField(
                        blank=True, db_column="BORSE_STUDIO_EN", null=True
                    ),
                ),
                (
                    "agevolazioni_it",
                    models.TextField(
                        blank=True, db_column="AGEVOLAZIONI_IT", null=True
                    ),
                ),
                (
                    "agevolazioni_en",
                    models.TextField(
                        blank=True, db_column="AGEVOLAZIONI_EN", null=True
                    ),
                ),
                (
                    "corso_in_pillole_it",
                    models.TextField(
                        blank=True, db_column="CORSO_IN_PILLOLE_IT", null=True
                    ),
                ),
                (
                    "corso_in_pillole_en",
                    models.TextField(
                        blank=True, db_column="CORSO_IN_PILLOLE_EN", null=True
                    ),
                ),
                (
                    "cosa_si_studia_it",
                    models.TextField(
                        blank=True, db_column="COSA_SI_STUDIA_IT", null=True
                    ),
                ),
                (
                    "cosa_si_studia_en",
                    models.TextField(
                        blank=True, db_column="COSA_SI_STUDIA_EN", null=True
                    ),
                ),
                (
                    "come_iscriversi_it",
                    models.TextField(
                        blank=True, db_column="COME_ISCRIVERSI_IT", null=True
                    ),
                ),
                (
                    "come_iscriversi_en",
                    models.TextField(
                        blank=True, db_column="COME_ISCRIVERSI_EN", null=True
                    ),
                ),
                ("dt_mod", models.DateField(blank=True, db_column="DT_MOD", null=True)),
                (
                    "cds",
                    models.OneToOneField(
                        db_column="ID_DIDATTICA_CDS",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brochure",
                        to="cds.didatticacds",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CDS_BROCHURE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CdsBrochureSlider",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "ordine",
                    models.IntegerField(blank=True, db_column="ORDINE", null=True),
                ),
                (
                    "slider_it",
                    models.TextField(blank=True, db_column="SLIDER_IT", null=True),
                ),
                (
                    "slider_en",
                    models.TextField(blank=True, db_column="SLIDER_EN", null=True),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "cds_brochure",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_CDS_BROCHURE",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cds_brochure.cdsbrochure",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CDS_BROCHURE_SLIDER",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CdsBrochureLink",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "ordine",
                    models.PositiveIntegerField(
                        blank=True, db_column="ORDINE", null=True
                    ),
                ),
                (
                    "descrizione_link_it",
                    models.CharField(db_column="DESCRIZIONE_LINK_IT", max_length=2000),
                ),
                (
                    "descrizione_link_en",
                    models.CharField(
                        blank=True,
                        db_column="DESCRIZIONE_LINK_EN",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "link_it",
                    models.CharField(
                        blank=True, db_column="LINK_IT", max_length=2000, null=True
                    ),
                ),
                (
                    "link_en",
                    models.CharField(
                        blank=True, db_column="LINK_EN", max_length=2000, null=True
                    ),
                ),
                ("dt_mod", models.DateField(blank=True, db_column="DT_MOD", null=True)),
                (
                    "cds_brochure",
                    models.ForeignKey(
                        db_column="ID_CDS_BROCHURE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cds_brochure.cdsbrochure",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CDS_BROCHURE_LINK",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CdsBrochureExStudenti",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome",
                    models.CharField(db_column="NOME", max_length=1000, null=True),
                ),
                ("ordine", models.PositiveIntegerField(db_column="ORDINE", null=True)),
                (
                    "profilo_it",
                    models.TextField(blank=True, db_column="PROFILO_IT", null=True),
                ),
                (
                    "profilo_en",
                    models.TextField(blank=True, db_column="PROFILO_EN", null=True),
                ),
                (
                    "link_it",
                    models.CharField(
                        blank=True, db_column="LINK_IT", max_length=2000, null=True
                    ),
                ),
                (
                    "link_en",
                    models.CharField(
                        blank=True, db_column="LINK_EN", max_length=2000, null=True
                    ),
                ),
                ("dt_mod", models.DateField(blank=True, db_column="DT_MOD", null=True)),
                (
                    "foto",
                    models.FileField(
                        blank=True,
                        db_column="FOTO",
                        max_length=1000,
                        null=True,
                        upload_to=cds_brochure.settings.cds_brochure_exstudents_media_path,
                        validators=[
                            generics.validators.validate_image_file_extension,
                            generics.validators.validate_file_size,
                        ],
                    ),
                ),
                (
                    "cds_brochure",
                    models.ForeignKey(
                        db_column="ID_CDS_BROCHURE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cds_brochure.cdsbrochure",
                    ),
                ),
                (
                    "user_mod",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_mod_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CDS_BROCHURE_EX_STUDENTI",
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="cdsbrochure",
            constraint=models.UniqueConstraint(
                fields=("cds_cod",), name="unique_cds_cod"
            ),
        ),
    ]
