# Generated by Django 4.2.20 on 2026-01-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds_brochure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdsbrochure',
            name='tolc_label',
            field=models.CharField(blank=True, db_column='TOLC_LABEL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cdsbrochure',
            name='tolc_url',
            field=models.URLField(blank=True, db_column='TOLC_URL', null=True),
        ),
    ]
