# Generated by Django 4.2.20 on 2026-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds_brochure', '0002_cdsbrochure_tolc_label_cdsbrochure_tolc_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdsbrochure',
            name='tolc_label',
        ),
        migrations.RemoveField(
            model_name='cdsbrochure',
            name='tolc_url',
        ),
        migrations.AddField(
            model_name='cdsbrochure',
            name='access_test_label',
            field=models.CharField(blank=True, db_column='ACCESS_TEST_LABEL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cdsbrochure',
            name='access_test_url',
            field=models.URLField(blank=True, db_column='ACCESS_TEST_URL', null=True),
        ),
    ]
