# Generated by Django 4.2.16 on 2024-10-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structures", "0001_initial"),
        ("addressbook", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AltaFormazioneDatiBase",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "titolo_it",
                    models.CharField(
                        blank=True, db_column="TITOLO_IT", max_length=512, null=True
                    ),
                ),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, db_column="TITOLO_EN", max_length=512, null=True
                    ),
                ),
                (
                    "anno_erogazione",
                    models.IntegerField(
                        blank=True, db_column="ANNO_EROGAZIONE", null=True
                    ),
                ),
                (
                    "lingua",
                    models.CharField(
                        blank=True, db_column="LINGUA", max_length=512, null=True
                    ),
                ),
                ("ore", models.IntegerField(blank=True, db_column="ORE", null=True)),
                ("mesi", models.IntegerField(blank=True, db_column="MESI", null=True)),
                (
                    "data_inizio",
                    models.DateField(blank=True, db_column="DATA_INIZIO", null=True),
                ),
                (
                    "data_fine",
                    models.DateField(blank=True, db_column="DATA_FINE", null=True),
                ),
                (
                    "sede_corso",
                    models.CharField(
                        blank=True, db_column="SEDE_CORSO", max_length=2000, null=True
                    ),
                ),
                (
                    "num_min_partecipanti",
                    models.IntegerField(
                        blank=True, db_column="NUM_MIN_PARTECIPANTI", null=True
                    ),
                ),
                (
                    "num_max_partecipanti",
                    models.IntegerField(
                        blank=True, db_column="NUM_MAX_PARTECIPANTI", null=True
                    ),
                ),
                (
                    "uditori_ammessi",
                    models.CharField(
                        blank=True,
                        db_column="UDITORI_AMMESSI",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "num_max_uditori",
                    models.IntegerField(
                        blank=True, db_column="NUM_MAX_UDITORI", null=True
                    ),
                ),
                (
                    "requisiti_ammissione",
                    models.TextField(
                        blank=True, db_column="REQUISITI_AMMISSIONE", null=True
                    ),
                ),
                (
                    "titolo_rilasciato",
                    models.TextField(
                        blank=True, db_column="TITOLO_RILASCIATO", null=True
                    ),
                ),
                (
                    "doppio_titolo",
                    models.TextField(blank=True, db_column="DOPPIO_TITOLO", null=True),
                ),
                (
                    "nome_origine_direttore_scientifico",
                    models.TextField(
                        blank=True,
                        db_column="NOME_ORIGINE_DIRETTORE_SCIENTIFICO",
                        null=True,
                    ),
                ),
                (
                    "quota_iscrizione",
                    models.FloatField(
                        blank=True, db_column="QUOTA_ISCRIZIONE", null=True
                    ),
                ),
                (
                    "quota_uditori",
                    models.FloatField(blank=True, db_column="QUOTA_UDITORI", null=True),
                ),
                (
                    "funzione_lavoro",
                    models.TextField(
                        blank=True, db_column="FUNZIONE_LAVORO", null=True
                    ),
                ),
                (
                    "obiettivi_formativi_summer_school",
                    models.TextField(
                        blank=True,
                        db_column="OBIETTIVI_FORMATIVI_SUMMER_SCHOOL",
                        null=True,
                    ),
                ),
                (
                    "competenze",
                    models.TextField(blank=True, db_column="COMPETENZE", null=True),
                ),
                (
                    "sbocchi_occupazionali",
                    models.TextField(
                        blank=True, db_column="SBOCCHI_OCCUPAZIONALI", null=True
                    ),
                ),
                (
                    "obiettivi_formativi_corso",
                    models.TextField(
                        blank=True, db_column="OBIETTIVI_FORMATIVI_CORSO", null=True
                    ),
                ),
                (
                    "modalita_svolgimento_prova_finale",
                    models.TextField(
                        blank=True,
                        db_column="MODALITA_SVOLGIMENTO_PROVA_FINALE",
                        null=True,
                    ),
                ),
                (
                    "numero_moduli",
                    models.FloatField(blank=True, db_column="NUMERO_MODULI", null=True),
                ),
                (
                    "stage_tirocinio",
                    models.TextField(
                        blank=True, db_column="STAGE_TIROCINIO", null=True
                    ),
                ),
                (
                    "ore_stage_tirocinio",
                    models.IntegerField(
                        blank=True, db_column="ORE_STAGE_TIROCINIO", null=True
                    ),
                ),
                (
                    "cfu_stage",
                    models.IntegerField(blank=True, db_column="CFU_STAGE", null=True),
                ),
                (
                    "mesi_stage",
                    models.IntegerField(blank=True, db_column="MESI_STAGE", null=True),
                ),
                (
                    "tipo_aziende_enti_tirocinio",
                    models.TextField(
                        blank=True, db_column="TIPO_AZIENDE_ENTI_TIROCINIO", null=True
                    ),
                ),
                (
                    "project_work",
                    models.TextField(blank=True, db_column="PROJECT_WORK", null=True),
                ),
                (
                    "contenuti_tempi_criteri_cfu",
                    models.TextField(
                        blank=True, db_column="CONTENUTI_TEMPI_CRITERI_CFU", null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_DATI_BASE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneModalitaErogazione",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=1000),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_MODALITA_EROGAZIONE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneTipoCorso",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "tipo_corso_descr",
                    models.CharField(db_column="TIPO_CORSO_DESCR", max_length=256),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_TIPO_CORSO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazionePianoDidattico",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("modulo", models.TextField(db_column="MODULO")),
                (
                    "ssd",
                    models.CharField(
                        blank=True, db_column="SSD", max_length=500, null=True
                    ),
                ),
                (
                    "num_ore",
                    models.IntegerField(blank=True, db_column="NUM_ORE", null=True),
                ),
                ("cfu", models.IntegerField(blank=True, db_column="CFU", null=True)),
                (
                    "verifica_finale",
                    models.IntegerField(
                        blank=True, db_column="VERIFICA_FINALE", null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_PIANO_DIDATTICO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazionePartner",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "denominazione",
                    models.CharField(db_column="DENOMINAZIONE", max_length=1000),
                ),
                (
                    "tipologia",
                    models.CharField(
                        blank=True, db_column="TIPOLOGIA", max_length=1000, null=True
                    ),
                ),
                (
                    "sito_web",
                    models.CharField(
                        blank=True, db_column="SITO_WEB", max_length=2000, null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_PARTNER",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneModalitaSelezione",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "tipo_selezione",
                    models.CharField(db_column="TIPO_SELEZIONE", max_length=100),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_MODALITA_SELEZIONE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneIncaricoDidattico",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("modulo", models.TextField(blank=True, db_column="MODULO", null=True)),
                (
                    "num_ore",
                    models.CharField(
                        blank=True, db_column="NUM_ORE", max_length=5, null=True
                    ),
                ),
                (
                    "docente",
                    models.CharField(
                        blank=True, db_column="DOCENTE", max_length=2000, null=True
                    ),
                ),
                (
                    "qualifica",
                    models.CharField(
                        blank=True, db_column="QUALIFICA", max_length=2000, null=True
                    ),
                ),
                ("ente", models.TextField(blank=True, db_column="ENTE", null=True)),
                (
                    "tipologia",
                    models.CharField(
                        blank=True, db_column="TIPOLOGIA", max_length=1000, null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
                (
                    "alta_formazione_piano_didattico",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_ALTA_FORMAZIONE_PIANO_DIDATTICO",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="advanced_training.altaformazionepianodidattico",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_INCARICO_DIDATTICO",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="alta_formazione_mod_erogazione",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_ALTA_FORMAZIONE_MOD_EROGAZIONE",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="advanced_training.altaformazionemodalitaerogazione",
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="alta_formazione_tipo_corso",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_ALTA_FORMAZIONE_TIPO_CORSO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="advanced_training.altaformazionetipocorso",
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="dipartimento_riferimento",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_DIPARTIMENTO_RIFERIMENTO",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="structures.didatticadipartimento",
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="matricola_direttore_scientifico",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_PERSONALE_MATRICOLA_DIRETTORE_SCIENTIFICO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
        migrations.CreateModel(
            name="AltaFormazioneConsiglioScientificoInterno",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_origine_cons",
                    models.CharField(db_column="NOME_ORIGINE_CONS", max_length=1000),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
                (
                    "matricola_cons",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_PERSONALE_MATRICOLA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_CONSIGLIO_SCIENTIFICO_INTERNO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneConsiglioScientificoEsterno",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("nome_cons", models.CharField(db_column="NOME_CONS", max_length=1000)),
                (
                    "ruolo_cons",
                    models.CharField(
                        blank=True, db_column="RUOLO_CONS", max_length=1000, null=True
                    ),
                ),
                (
                    "ente_cons",
                    models.CharField(
                        blank=True, db_column="ENTE_CONS", max_length=1000, null=True
                    ),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                (
                    "alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_CONSIGLIO_SCIENTIFICO_ESTERNO",
                "managed": True,
            },
        ),
        migrations.AlterUniqueTogether(
            name="altaformazionedatibase",
            unique_together={("titolo_it", "data_inizio")},
        ),
        migrations.CreateModel(
            name="AltaFormazioneAttivitaFormative",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="NOME", max_length=500, null=True
                    ),
                ),
                (
                    "programma",
                    models.TextField(blank=True, db_column="PROGRAMMA", null=True),
                ),
                (
                    "bibliografia",
                    models.TextField(blank=True, db_column="BIBLIOGRAFIA", null=True),
                ),
                (
                    "modalita_verifica_finale",
                    models.TextField(
                        blank=True, db_column="MODALITA_VERIFICA_FINALE", null=True
                    ),
                ),
                (
                    "alta_formazione_attivita_formativa_padre",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_ALTA_FORMAZIONE_ATTIVITA_FORMATIVA_PADRE",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="advanced_training.altaformazioneattivitaformative",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_ATTIVITA_FORMATIVE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneFinestraTemporale",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("titolo", models.CharField(db_column="TITOLO", max_length=256)),
                ("data_inizio", models.DateField(db_column="DATA_INIZIO")),
                ("data_fine", models.DateField(db_column="DATA_FINE")),
                (
                    "anno_accademico",
                    models.CharField(db_column="ANNO_ACCADEMICO", max_length=9),
                ),
                ("note", models.TextField(blank=True, db_column="NOTE", null=True)),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_FINESTRA_TEMPORALE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneStatus",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("status_cod", models.CharField(db_column="STATUS_COD", max_length=50)),
                (
                    "status_desc",
                    models.CharField(db_column="STATUS_DESC", max_length=256),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_STATUS",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneTipologiaDocente",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(db_column="DESCRIZIONE", max_length=500),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_TIPOLOGIA_DOCENTE",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="altaformazioneconsiglioscientificoesterno",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazioneconsiglioscientificointerno",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="cognome_proponente",
            field=models.CharField(
                blank=True, db_column="COGNOME_PROPONENTE", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="matricola_proponente",
            field=models.ForeignKey(
                blank=True,
                db_column="MATRICOLA_PROPONENTE",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proponente",
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="nome_proponente",
            field=models.CharField(
                blank=True, db_column="NOME_PROPONENTE", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="path_doc_delibera",
            field=models.FileField(
                blank=True,
                db_column="PATH_DOC_DELIBERA",
                max_length=500,
                null=True,
                upload_to=advanced_training.settings.advanced_training_media_path,
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="path_piano_finanziario",
            field=models.FileField(
                blank=True,
                db_column="PATH_PIANO_FINANZIARIO",
                max_length=500,
                null=True,
                upload_to=advanced_training.settings.advanced_training_media_path,
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazioneincaricodidattico",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazionemodalitaerogazione",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazionemodalitaselezione",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazionepartner",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazionepianodidattico",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="altaformazionetipocorso",
            name="user_mod_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="altaformazionedatibase",
            name="matricola_direttore_scientifico",
            field=models.ForeignKey(
                blank=True,
                db_column="ID_PERSONALE_MATRICOLA_DIRETTORE_SCIENTIFICO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direttore_scientifico",
                to="addressbook.personale",
                to_field="matricola",
            ),
        ),
        migrations.CreateModel(
            name="AltaFormazioneStatusStorico",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "motivazione",
                    models.TextField(blank=True, db_column="MOTIVAZIONE", null=True),
                ),
                (
                    "data_status",
                    models.DateField(blank=True, db_column="DATA_STATUS", null=True),
                ),
                (
                    "dt_mod",
                    models.DateTimeField(blank=True, db_column="DT_MOD", null=True),
                ),
                ("user_mod_id", models.IntegerField(blank=True, null=True)),
                (
                    "id_alta_formazione_dati_base",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionedatibase",
                    ),
                ),
                (
                    "id_alta_formazione_status",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_STATUS",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazionestatus",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_STATUS_STORICO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AltaFormazioneAttivitaFormativeDocenti",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_docente",
                    models.CharField(
                        blank=True, db_column="NOME_DOCENTE", max_length=200, null=True
                    ),
                ),
                (
                    "cognome_docente",
                    models.CharField(
                        blank=True,
                        db_column="COGNOME_DOCENTE",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "durata_in_ore",
                    models.IntegerField(
                        blank=True, db_column="DURATA_IN_ORE", null=True
                    ),
                ),
                (
                    "ssd",
                    models.CharField(
                        blank=True, db_column="SSD", max_length=100, null=True
                    ),
                ),
                ("cfu", models.IntegerField(blank=True, db_column="CFU", null=True)),
                (
                    "argomento",
                    models.TextField(blank=True, db_column="ARGOMENTO", null=True),
                ),
                (
                    "alta_formazione_attivita_formative",
                    models.ForeignKey(
                        db_column="ID_ALTA_FORMAZIONE_ATTIVITA_FORMATIVE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advanced_training.altaformazioneattivitaformative",
                    ),
                ),
                (
                    "matricola_docente",
                    models.ForeignKey(
                        blank=True,
                        db_column="MATRICOLA_DOCENTE",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addressbook.personale",
                        to_field="matricola",
                    ),
                ),
                (
                    "tipologia_docente",
                    models.ForeignKey(
                        blank=True,
                        db_column="ID_TIPOLOGIA_DOCENTE",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="advanced_training.altaformazionetipologiadocente",
                    ),
                ),
            ],
            options={
                "db_table": "ALTA_FORMAZIONE_ATTIVITA_FORMATIVE_DOCENTI",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="altaformazioneattivitaformative",
            name="alta_formazione_dati_base",
            field=models.ForeignKey(
                db_column="ID_ALTA_FORMAZIONE_DATI_BASE",
                on_delete=django.db.models.deletion.CASCADE,
                to="advanced_training.altaformazionedatibase",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="altaformazionedatibase",
                    name="anno_erogazione",
                    field=models.IntegerField(
                        blank=True, db_column="ANNO_EROGAZIONE", null=True
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="tipo_selezione",
            field=models.CharField(
                blank=True, db_column="TIPO_SELEZIONE", max_length=100, null=True
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="altaformazionedatibase",
                    name="anno_erogazione",
                    field=models.IntegerField(
                        blank=True, db_column="ANNO_EROGAZIONE", null=True
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="altaformazionedatibase",
            name="tipo_selezione",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Altro", "Altro"),
                    ("Colloquio", "Colloquio"),
                    ("Titoli", "Titoli"),
                ],
                db_column="TIPO_SELEZIONE",
                max_length=100,
                null=True,
            ),
        ),
    ]
