# Generated by Django 4.2.20 on 2026-06-04 12:02

import advanced_training.settings
import django.core.validators
from django.db import migrations, models
import generics.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltaFormazioneAttivitaFormative',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=500, null=True)),
                ('programma', models.TextField(blank=True, db_column='PROGRAMMA', null=True)),
                ('bibliografia', models.TextField(blank=True, db_column='BIBLIOGRAFIA', null=True)),
                ('modalita_verifica_finale', models.TextField(blank=True, db_column='MODALITA_VERIFICA_FINALE', null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_ATTIVITA_FORMATIVE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneAttivitaFormativeDocenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_docente', models.CharField(blank=True, db_column='NOME_DOCENTE', max_length=200, null=True)),
                ('cognome_docente', models.CharField(blank=True, db_column='COGNOME_DOCENTE', max_length=200, null=True)),
                ('durata_in_ore', models.IntegerField(blank=True, db_column='DURATA_IN_ORE', null=True)),
                ('ssd', models.CharField(blank=True, db_column='SSD', max_length=100, null=True)),
                ('cfu', models.IntegerField(blank=True, db_column='CFU', null=True)),
                ('argomento', models.TextField(blank=True, db_column='ARGOMENTO', null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_ATTIVITA_FORMATIVE_DOCENTI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneConsiglioScientificoEsterno',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_cons', models.CharField(db_column='NOME_CONS', max_length=1000)),
                ('ruolo_cons', models.CharField(blank=True, db_column='RUOLO_CONS', max_length=1000, null=True)),
                ('ente_cons', models.CharField(blank=True, db_column='ENTE_CONS', max_length=1000, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_CONSIGLIO_SCIENTIFICO_ESTERNO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneConsiglioScientificoInterno',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_origine_cons', models.CharField(db_column='NOME_ORIGINE_CONS', max_length=1000)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_CONSIGLIO_SCIENTIFICO_INTERNO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneDatiBase',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titolo_it', models.CharField(blank=True, db_column='TITOLO_IT', max_length=512, null=True)),
                ('titolo_en', models.CharField(blank=True, db_column='TITOLO_EN', max_length=512, null=True)),
                ('anno_erogazione', models.IntegerField(blank=True, db_column='ANNO_EROGAZIONE', null=True)),
                ('lingua', models.CharField(blank=True, db_column='LINGUA', max_length=512, null=True)),
                ('tipo_selezione', models.CharField(blank=True, choices=[('Altro', 'Altro'), ('Colloquio', 'Colloquio'), ('Titoli', 'Titoli')], db_column='TIPO_SELEZIONE', max_length=100, null=True)),
                ('ore', models.IntegerField(blank=True, db_column='ORE', null=True)),
                ('mesi', models.IntegerField(blank=True, db_column='MESI', null=True)),
                ('data_inizio', models.DateField(blank=True, db_column='DATA_INIZIO', null=True)),
                ('data_fine', models.DateField(blank=True, db_column='DATA_FINE', null=True)),
                ('sede_corso', models.CharField(blank=True, db_column='SEDE_CORSO', max_length=2000, null=True)),
                ('num_min_partecipanti', models.IntegerField(blank=True, db_column='NUM_MIN_PARTECIPANTI', null=True)),
                ('num_max_partecipanti', models.IntegerField(blank=True, db_column='NUM_MAX_PARTECIPANTI', null=True)),
                ('uditori_ammessi', models.BooleanField(db_column='UDITORI_AMMESSI', default=False)),
                ('num_max_uditori', models.IntegerField(blank=True, db_column='NUM_MAX_UDITORI', null=True)),
                ('requisiti_ammissione', models.TextField(blank=True, db_column='REQUISITI_AMMISSIONE', null=True)),
                ('titolo_rilasciato', models.TextField(blank=True, db_column='TITOLO_RILASCIATO', null=True)),
                ('doppio_titolo', models.BooleanField(db_column='DOPPIO_TITOLO', default=False)),
                ('nome_origine_direttore_scientifico', models.CharField(blank=True, db_column='NOME_ORIGINE_DIRETTORE_SCIENTIFICO', max_length=100, null=True)),
                ('quota_iscrizione', models.FloatField(blank=True, db_column='QUOTA_ISCRIZIONE', null=True)),
                ('quota_uditori', models.FloatField(blank=True, db_column='QUOTA_UDITORI', null=True)),
                ('funzione_lavoro', models.TextField(blank=True, db_column='FUNZIONE_LAVORO', null=True)),
                ('obiettivi_formativi_summer_school', models.TextField(blank=True, db_column='OBIETTIVI_FORMATIVI_SUMMER_SCHOOL', null=True)),
                ('competenze', models.TextField(blank=True, db_column='COMPETENZE', null=True)),
                ('sbocchi_occupazionali', models.TextField(blank=True, db_column='SBOCCHI_OCCUPAZIONALI', null=True)),
                ('obiettivi_formativi_corso', models.TextField(blank=True, db_column='OBIETTIVI_FORMATIVI_CORSO', null=True)),
                ('modalita_svolgimento_prova_finale', models.TextField(blank=True, db_column='MODALITA_SVOLGIMENTO_PROVA_FINALE', null=True)),
                ('numero_moduli', models.FloatField(blank=True, db_column='NUMERO_MODULI', null=True)),
                ('stage_tirocinio', models.BooleanField(db_column='STAGE_TIROCINIO', default=False)),
                ('ore_stage_tirocinio', models.PositiveIntegerField(blank=True, db_column='ORE_STAGE_TIROCINIO', null=True)),
                ('cfu_stage', models.FloatField(blank=True, db_column='CFU_STAGE', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('cfu_prova_finale', models.FloatField(blank=True, db_column='CFU_PROVA_FINALE', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('mesi_stage', models.PositiveIntegerField(blank=True, db_column='MESI_STAGE', null=True)),
                ('tipo_aziende_enti_tirocinio', models.TextField(blank=True, db_column='TIPO_AZIENDE_ENTI_TIROCINIO', null=True)),
                ('project_work', models.BooleanField(db_column='PROJECT_WORK', default=False)),
                ('prova_finale', models.BooleanField(db_column='PROVA_FINALE', default=False)),
                ('rinnovo', models.BooleanField(db_column='RINNOVO', default=False)),
                ('contenuti_tempi_criteri_cfu', models.TextField(blank=True, db_column='CONTENUTI_TEMPI_CRITERI_CFU', null=True)),
                ('path_piano_finanziario', models.FileField(blank=True, db_column='PATH_PIANO_FINANZIARIO', max_length=500, null=True, upload_to=advanced_training.settings.advanced_training_media_path, validators=[generics.validators.validate_pdf_file_extension, generics.validators.validate_file_size])),
                ('path_doc_delibera', models.FileField(blank=True, db_column='PATH_DOC_DELIBERA', max_length=500, null=True, upload_to=advanced_training.settings.advanced_training_media_path, validators=[generics.validators.validate_pdf_file_extension, generics.validators.validate_file_size])),
                ('cognome_proponente', models.CharField(blank=True, db_column='COGNOME_PROPONENTE', max_length=200, null=True)),
                ('nome_proponente', models.CharField(blank=True, db_column='NOME_PROPONENTE', max_length=200, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_DATI_BASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneFinestraTemporale',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titolo', models.CharField(db_column='TITOLO', max_length=256)),
                ('data_inizio', models.DateField(db_column='DATA_INIZIO')),
                ('data_fine', models.DateField(db_column='DATA_FINE')),
                ('anno_accademico', models.CharField(db_column='ANNO_ACCADEMICO', max_length=9)),
                ('note', models.TextField(blank=True, db_column='NOTE', null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_FINESTRA_TEMPORALE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneIncaricoDidattico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('modulo', models.TextField(blank=True, db_column='MODULO', null=True)),
                ('num_ore', models.CharField(blank=True, db_column='NUM_ORE', max_length=5, null=True)),
                ('docente', models.CharField(blank=True, db_column='DOCENTE', max_length=2000, null=True)),
                ('qualifica', models.CharField(blank=True, db_column='QUALIFICA', max_length=2000, null=True)),
                ('ente', models.TextField(blank=True, db_column='ENTE', null=True)),
                ('tipologia', models.CharField(blank=True, db_column='TIPOLOGIA', max_length=1000, null=True)),
                ('path_cv', models.FileField(blank=True, db_column='CV', max_length=500, null=True, upload_to=advanced_training.settings.advanced_training_cv_media_path, validators=[generics.validators.validate_pdf_file_extension, generics.validators.validate_file_size])),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_INCARICO_DIDATTICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneModalitaErogazione',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=1000)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_MODALITA_EROGAZIONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneModalitaSelezione',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_selezione', models.CharField(db_column='TIPO_SELEZIONE', max_length=100)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_MODALITA_SELEZIONE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazionePartner',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('denominazione', models.CharField(db_column='DENOMINAZIONE', max_length=1000)),
                ('tipologia', models.CharField(blank=True, db_column='TIPOLOGIA', max_length=1000, null=True)),
                ('sito_web', models.CharField(blank=True, db_column='SITO_WEB', max_length=2000, null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_PARTNER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazionePianoDidattico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('modulo', models.TextField(db_column='MODULO')),
                ('ssd', models.CharField(blank=True, db_column='SSD', max_length=500, null=True)),
                ('num_ore', models.IntegerField(blank=True, db_column='NUM_ORE', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cfu', models.FloatField(blank=True, db_column='CFU', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('verifica_finale', models.IntegerField(blank=True, db_column='VERIFICA_FINALE', null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_PIANO_DIDATTICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneStatus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status_cod', models.CharField(db_column='STATUS_COD', max_length=50)),
                ('status_desc', models.CharField(db_column='STATUS_DESC', max_length=256)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_STATUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneStatusStorico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('motivazione', models.TextField(blank=True, db_column='MOTIVAZIONE', null=True)),
                ('data_status', models.DateField(blank=True, db_column='DATA_STATUS', null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
                ('dipartimento_utente', models.CharField(blank=True, db_column='DIPARTIMENTO_UTENTE', max_length=200, null=True)),
                ('dipartimento_master', models.CharField(blank=True, db_column='DIPARTIMENTO_MASTER', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_STATUS_STORICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneTipoCorso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_corso_descr', models.CharField(db_column='TIPO_CORSO_DESCR', max_length=256)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_TIPO_CORSO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneTipologiaDocente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=500)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_TIPOLOGIA_DOCENTE',
                'managed': False,
            },
        ),
    ]
