# Generated by Django 4.2.20 on 2025-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_alter_personaleattivotuttiruoli_matricola'),
        ('advanced_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaFormazioneAttivitaFormative',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=500, null=True)),
                ('programma', models.TextField(blank=True, db_column='PROGRAMMA', null=True)),
                ('bibliografia', models.TextField(blank=True, db_column='BIBLIOGRAFIA', null=True)),
                ('modalita_verifica_finale', models.TextField(blank=True, db_column='MODALITA_VERIFICA_FINALE', null=True)),
                ('alta_formazione_attivita_formativa_padre', models.ForeignKey(blank=True, db_column='ID_ALTA_FORMAZIONE_ATTIVITA_FORMATIVA_PADRE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='advanced_training.altaformazioneattivitaformative')),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_ATTIVITA_FORMATIVE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneFinestraTemporale',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titolo', models.CharField(db_column='TITOLO', max_length=256)),
                ('data_inizio', models.DateField(db_column='DATA_INIZIO')),
                ('data_fine', models.DateField(db_column='DATA_FINE')),
                ('anno_accademico', models.CharField(db_column='ANNO_ACCADEMICO', max_length=9)),
                ('note', models.TextField(blank=True, db_column='NOTE', null=True)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_FINESTRA_TEMPORALE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneStatus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status_cod', models.CharField(db_column='STATUS_COD', max_length=50)),
                ('status_desc', models.CharField(db_column='STATUS_DESC', max_length=256)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_STATUS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneTipologiaDocente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='DESCRIZIONE', max_length=500)),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_TIPOLOGIA_DOCENTE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='altaformazioneconsiglioscientificoesterno',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazioneconsiglioscientificointerno',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='cognome_proponente',
            field=models.CharField(blank=True, db_column='COGNOME_PROPONENTE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='matricola_proponente',
            field=models.ForeignKey(blank=True, db_column='MATRICOLA_PROPONENTE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proponente', to='addressbook.personale', to_field='matricola'),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='nome_proponente',
            field=models.CharField(blank=True, db_column='NOME_PROPONENTE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='path_doc_delibera',
            field=models.CharField(blank=True, db_column='PATH_DOC_DELIBERA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='path_piano_finanziario',
            field=models.CharField(blank=True, db_column='PATH_PIANO_FINANZIARIO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionedatibase',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazioneincaricodidattico',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionemodalitaerogazione',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionemodalitaselezione',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionepartner',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionepianodidattico',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionetipocorso',
            name='user_mod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='matricola_direttore_scientifico',
            field=models.ForeignKey(blank=True, db_column='ID_PERSONALE_MATRICOLA_DIRETTORE_SCIENTIFICO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direttore_scientifico', to='addressbook.personale', to_field='matricola'),
        ),
        migrations.CreateModel(
            name='AltaFormazioneStatusStorico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('motivazione', models.TextField(blank=True, db_column='MOTIVAZIONE', null=True)),
                ('data_status', models.DateField(blank=True, db_column='DATA_STATUS', null=True)),
                ('dt_mod', models.DateTimeField(blank=True, db_column='DT_MOD', null=True)),
                ('user_mod_id', models.IntegerField(blank=True, null=True)),
                ('id_alta_formazione_dati_base', models.ForeignKey(db_column='ID_ALTA_FORMAZIONE_DATI_BASE', on_delete=django.db.models.deletion.CASCADE, to='advanced_training.altaformazionedatibase')),
                ('id_alta_formazione_status', models.ForeignKey(db_column='ID_ALTA_FORMAZIONE_STATUS', on_delete=django.db.models.deletion.CASCADE, to='advanced_training.altaformazionestatus')),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_STATUS_STORICO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AltaFormazioneAttivitaFormativeDocenti',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_docente', models.CharField(blank=True, db_column='NOME_DOCENTE', max_length=200, null=True)),
                ('cognome_docente', models.CharField(blank=True, db_column='COGNOME_DOCENTE', max_length=200, null=True)),
                ('durata_in_ore', models.IntegerField(blank=True, db_column='DURATA_IN_ORE', null=True)),
                ('ssd', models.CharField(blank=True, db_column='SSD', max_length=100, null=True)),
                ('cfu', models.IntegerField(blank=True, db_column='CFU', null=True)),
                ('argomento', models.TextField(blank=True, db_column='ARGOMENTO', null=True)),
                ('alta_formazione_attivita_formative', models.ForeignKey(db_column='ID_ALTA_FORMAZIONE_ATTIVITA_FORMATIVE', on_delete=django.db.models.deletion.CASCADE, to='advanced_training.altaformazioneattivitaformative')),
                ('matricola_docente', models.ForeignKey(blank=True, db_column='MATRICOLA_DOCENTE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='addressbook.personale', to_field='matricola')),
                ('tipologia_docente', models.ForeignKey(blank=True, db_column='ID_TIPOLOGIA_DOCENTE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='advanced_training.altaformazionetipologiadocente')),
            ],
            options={
                'db_table': 'ALTA_FORMAZIONE_ATTIVITA_FORMATIVE_DOCENTI',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='altaformazioneattivitaformative',
            name='alta_formazione_dati_base',
            field=models.ForeignKey(db_column='ID_ALTA_FORMAZIONE_DATI_BASE', on_delete=django.db.models.deletion.CASCADE, to='advanced_training.altaformazionedatibase'),
        ),
    ]
