# Generated by Django 4.2.20 on 2026-04-21 16:38

import advanced_training.settings
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advanced_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='doppio_titolo',
            field=models.BooleanField(db_column='DOPPIO_TITOLO', default=False),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='project_work',
            field=models.BooleanField(db_column='PROJECT_WORK', default=False),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='stage_tirocinio',
            field=models.BooleanField(db_column='STAGE_TIROCINIO', default=False),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='uditori_ammessi',
            field=models.BooleanField(db_column='UDITORI_AMMESSI', default=False),
        ),
    ]
