# Generated by Django 4.2.20 on 2026-04-22 07:59

import advanced_training.settings
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advanced_training', '0002_altaformazionestatusstorico_dipartimento_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='cfu_stage',
            field=models.FloatField(blank=True, db_column='CFU_STAGE', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='mesi_stage',
            field=models.PositiveIntegerField(blank=True, db_column='MESI_STAGE', null=True),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='ore_stage_tirocinio',
            field=models.PositiveIntegerField(blank=True, db_column='ORE_STAGE_TIROCINIO', null=True),
        ),
        migrations.AlterField(
            model_name='altaformazionepianodidattico',
            name='cfu',
            field=models.FloatField(blank=True, db_column='CFU', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='altaformazionepianodidattico',
            name='num_ore',
            field=models.IntegerField(blank=True, db_column='NUM_ORE', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
