# Generated by Django 4.2.27 on 2026-02-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_training", "0002_altaformazioneattivitaformative_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="altaformazionedatibase",
            name="anno_rilevazione",
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="anno_erogazione",
            field=models.IntegerField(
                blank=True, db_column="ANNO_EROGAZIONE", null=True
            ),
        ),
    ]
