# Generated by Django 4.2.20 on 2026-04-22 08:02

import advanced_training.settings
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advanced_training', '0003_altaformazionestatusstorico_dipartimento_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altaformazionestatusstorico',
            name='dipartimento_master',
            field=models.CharField(blank=True, db_column='DIPARTIMENTO_MASTER', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionestatusstorico',
            name='dipartimento_utente',
            field=models.CharField(blank=True, db_column='DIPARTIMENTO_UTENTE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='altaformazionestatusstorico',
            name='utente_cambio_stato',
            field=models.ForeignKey(blank=True, db_column='UTENTE_CAMBIO_STATO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='nome_origine_direttore_scientifico',
            field=models.CharField(blank=True, db_column='NOME_ORIGINE_DIRETTORE_SCIENTIFICO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='path_doc_delibera',
            field=models.FileField(blank=True, db_column='PATH_DOC_DELIBERA', max_length=500, null=True, upload_to=advanced_training.settings.advanced_training_media_path, validators=[generics.validators.validate_pdf_file_extension, generics.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='altaformazionedatibase',
            name='path_piano_finanziario',
            field=models.FileField(blank=True, db_column='PATH_PIANO_FINANZIARIO', max_length=500, null=True, upload_to=advanced_training.settings.advanced_training_media_path, validators=[generics.validators.validate_pdf_file_extension, generics.validators.validate_file_size]),
        ),
    ]
