# Generated by Django 4.2.20 on 2026-04-27 11:40

import advanced_training.settings
from django.db import migrations, models
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_training', '0004_altaformazionestatusstorico_dipartimento_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altaformazioneincaricodidattico',
            name='path_cv',
            field=models.FileField(blank=True, db_column='CV', max_length=500, null=True, upload_to=advanced_training.settings.advanced_training_cv_media_path, validators=[generics.validators.validate_pdf_file_extension, generics.validators.validate_file_size]),
        ),
    ]
