# Generated by Django 4.2.27 on 2026-04-27 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_training", "0005_altaformazioneincaricodidattico_path_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="cfu_prova_finale",
            field=models.FloatField(
                blank=True,
                db_column="CFU_PROVA_FINALE",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="prova_finale",
            field=models.BooleanField(db_column="PROVA_FINALE", default=False),
        ),
        migrations.AddField(
            model_name="altaformazionedatibase",
            name="rinnovo",
            field=models.BooleanField(db_column="RINNOVO", default=False),
        ),
    ]
